In [29]:
import pandas as pd
import numpy as np

In [30]:
fbref_data = pd.read_csv("fbref_standard_2425.csv")

In [31]:
fbref_data.head()

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,nation,pos,age,born,Playing Time,Playing Time.1,...,Performance.3,Performance.4,Performance.5,Performance.6,Performance.7,Per 90 Minutes,Per 90 Minutes.1,Per 90 Minutes.2,Per 90 Minutes.3,Per 90 Minutes.4
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MP,Starts,...,G-PK,PK,PKatt,CrdY,CrdR,Gls,Ast,G+A,G-PK,G+A-PK
1,league,season,team,player,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,ENG-Premier League,2122,Arsenal,Aaron Ramsdale,ENG,GK,23.0,1998.0,34,34,...,0,0,0,1,0,0.0,0.0,0.0,0.0,0.0
3,ENG-Premier League,2122,Arsenal,Ainsley Maitland-Niles,ENG,MF,23.0,1997.0,8,2,...,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0
4,ENG-Premier League,2122,Arsenal,Albert Sambi Lokonga,BEL,MF,21.0,1999.0,19,12,...,0,0,0,5,0,0.0,0.0,0.0,0.0,0.0

In [32]:
fbref_data.size

287975

In [33]:
fbref_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11519 entries, 0 to 11518
Data columns (total 25 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Unnamed: 0        9481 non-null   object
 1   Unnamed: 1        11518 non-null  object
 2   Unnamed: 2        11518 non-null  object
 3   Unnamed: 3        11518 non-null  object
 4   nation            11513 non-null  object
 5   pos               11517 non-null  object
 6   age               11516 non-null  float64
 7   born              11516 non-null  float64
 8   Playing Time      11518 non-null  object
 9   Playing Time.1    11518 non-null  object
 10  Playing Time.2    11518 non-null  object
 11  Playing Time.3    11518 non-null  object
 12  Performance       11518 non-null  object
 13  Performance.1     11518 non-null  object
 14  Performance.2     11518 non-null  object
 15  Performance.3     11518 non-null  object
 16  Performance.4     11518 non-null  object
 17  Performance.5     11518 non-null  object
 18  Performance.6     11518 non-null  object
 19  Performance.7     11518 non-null  object
 20  Per 90 Minutes    11518 non-null  object
 21  Per 90 Minutes.1  11518 non-null  object
 22  Per 90 Minutes.2  11518 non-null  object
 23  Per 90 Minutes.3  11518 non-null  object
 24  Per 90 Minutes.4  11518 non-null  object
dtypes: float64(2), object(23)
memory usage: 2.2+ MB

In [34]:
fbref_data.columns

Index(['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'nation', 'pos',
       'age', 'born', 'Playing Time', 'Playing Time.1', 'Playing Time.2',
       'Playing Time.3', 'Performance', 'Performance.1', 'Performance.2',
       'Performance.3', 'Performance.4', 'Performance.5', 'Performance.6',
       'Performance.7', 'Per 90 Minutes', 'Per 90 Minutes.1',
       'Per 90 Minutes.2', 'Per 90 Minutes.3', 'Per 90 Minutes.4'],
      dtype='object')

In [35]:
fbref_data.iloc[0]

Unnamed: 0             NaN
Unnamed: 1             NaN
Unnamed: 2             NaN
Unnamed: 3             NaN
nation                 NaN
pos                    NaN
age                    NaN
born                   NaN
Playing Time            MP
Playing Time.1      Starts
Playing Time.2         Min
Playing Time.3         90s
Performance            Gls
Performance.1          Ast
Performance.2          G+A
Performance.3         G-PK
Performance.4           PK
Performance.5        PKatt
Performance.6         CrdY
Performance.7         CrdR
Per 90 Minutes         Gls
Per 90 Minutes.1       Ast
Per 90 Minutes.2       G+A
Per 90 Minutes.3      G-PK
Per 90 Minutes.4    G+A-PK
Name: 0, dtype: object

In [36]:
len(fbref_data.columns)

25

In [37]:
fbref_data.reset_index(drop=True, inplace=True)

In [45]:
fbref_data = fbref_data.iloc[2:].copy()

In [52]:

new_column_name = {
    "Unnamed: 0": "league",
    "Unnamed: 1": "season",
    "Unnamed: 2": "team",
    "Unnamed: 3": "player",
    "pos": "position",
    "Playing Time": "matches_played",
    "Playing Time.1": "starts",
    "Playing Time.2": "minutes",
    "Playing Time.3": "nineties",
    "Performance": "goals",
    "Performance.1": "assists",
    "Performance.2": "goal_contributions",
    "Performance.3": "non_penalty_goals",
    "Performance.4": "penalty_goals",
    "Performance.5": "penalty_attempts",
    "Performance.6": "yellow_cards",
    "Performance.7": "red_cards",
    "Per 90 Minutes": "goals_per90",
    "Per 90 Minutes.1": "assists_per90",
    "Per 90 Minutes.2": "ga_per90",
    "Per 90 Minutes.3": "npg_per90",
    "Per 90 Minutes.4": "npga_per90"
}

fbref_data.rename(columns=new_column_name,
          inplace=True)

In [53]:
fbref_data.head(5)

,league,season,team,player,nation,position,age,born,matches_played,starts,...,non_penalty_goals,penalty_goals,penalty_attempts,yellow_cards,red_cards,goals_per90,assists_per90,ga_per90,npg_per90,npga_per90
2,ENG-Premier League,2122,Arsenal,Aaron Ramsdale,ENG,GK,23.0,1998.0,34,34,...,0,0,0,1,0,0.0,0.0,0.0,0.0,0.0
3,ENG-Premier League,2122,Arsenal,Ainsley Maitland-Niles,ENG,MF,23.0,1997.0,8,2,...,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0
4,ENG-Premier League,2122,Arsenal,Albert Sambi Lokonga,BEL,MF,21.0,1999.0,19,12,...,0,0,0,5,0,0.0,0.0,0.0,0.0,0.0
5,ENG-Premier League,2122,Arsenal,Alexandre Lacazette,FRA,"FW,MF",30.0,1991.0,30,20,...,2,2,3,0,0,0.2,0.35,0.56,0.1,0.45
6,ENG-Premier League,2122,Arsenal,Ben White,ENG,DF,23.0,1997.0,32,32,...,0,0,0,3,0,0.0,0.0,0.0,0.0,0.0

In [54]:
fbref_data['season'].value_counts()

season
2122    2922
2223    2889
2425    2854
2324    2852
Name: count, dtype: int64

In [55]:
fbref_data['position'].value_counts()

position
MF       3540
DF       2898
FW       1534
MF,FW     869
GK        840
FW,MF     712
DF,MF     648
MF,DF     460
DF,FW      14
FW,DF       2
Name: count, dtype: int64

Save dataframe to a new csv file. Reference: https://www.datacamp.com/tutorial/save-as-csv-pandas-dataframe

In [56]:
fbref_copy.to_csv("fbref_clean.csv", index=False)