In [142]:
import pandas as pd
import numpy as np

In [143]:
#fbref_data = pd.read_csv("fbref_standard_2425.csv")
fbref_data = pd.read_csv("/Users/kachi/Documents/Thesis/data/raw/fbref_raw.csv")

In [144]:
fbref_data.head()

,league,season,team,player,nation,pos,age,born,Playing Time,Playing Time.1,...,Performance.3,Performance.4,Performance.5,Performance.6,Performance.7,Per 90 Minutes,Per 90 Minutes.1,Per 90 Minutes.2,Per 90 Minutes.3,Per 90 Minutes.4
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MP,Starts,...,G-PK,PK,PKatt,CrdY,CrdR,Gls,Ast,G+A,G-PK,G+A-PK
1,ENG-Premier League,2122.0,Arsenal,Aaron Ramsdale,ENG,GK,23.0,1998.0,34,34,...,0,0,0,1,0,0.0,0.0,0.0,0.0,0.0
2,ENG-Premier League,2122.0,Arsenal,Ainsley Maitland-Niles,ENG,MF,23.0,1997.0,8,2,...,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0
3,ENG-Premier League,2122.0,Arsenal,Albert Sambi Lokonga,BEL,MF,21.0,1999.0,19,12,...,0,0,0,5,0,0.0,0.0,0.0,0.0,0.0
4,ENG-Premier League,2122.0,Arsenal,Alexandre Lacazette,FRA,"FW,MF",30.0,1991.0,30,20,...,2,2,3,0,0,0.2,0.35,0.56,0.1,0.45

In [145]:
fbref_data.shape

(11518, 25)

In [146]:
fbref_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11518 entries, 0 to 11517
Data columns (total 25 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   league            11517 non-null  object
 1   season            11517 non-null  float64
 2   team              11517 non-null  object
 3   player            11517 non-null  object
 4   nation            11513 non-null  object
 5   pos               11517 non-null  object
 6   age               11516 non-null  float64
 7   born              11516 non-null  float64
 8   Playing Time      11518 non-null  object
 9   Playing Time.1    11518 non-null  object
 10  Playing Time.2    11518 non-null  object
 11  Playing Time.3    11518 non-null  object
 12  Performance       11518 non-null  object
 13  Performance.1     11518 non-null  object
 14  Performance.2     11518 non-null  object
 15  Performance.3     11518 non-null  object
 16  Performance.4     11518 non-null  object
 17  Performance.5     11518 non-null  object
 18  Performance.6     11518 non-null  object
 19  Performance.7     11518 non-null  object
 20  Per 90 Minutes    11518 non-null  object
 21  Per 90 Minutes.1  11518 non-null  object
 22  Per 90 Minutes.2  11518 non-null  object
 23  Per 90 Minutes.3  11518 non-null  object
 24  Per 90 Minutes.4  11518 non-null  object
dtypes: float64(3), object(22)
memory usage: 2.2+ MB

In [147]:
fbref_data.columns

Index(['league', 'season', 'team', 'player', 'nation', 'pos', 'age', 'born',
       'Playing Time', 'Playing Time.1', 'Playing Time.2', 'Playing Time.3',
       'Performance', 'Performance.1', 'Performance.2', 'Performance.3',
       'Performance.4', 'Performance.5', 'Performance.6', 'Performance.7',
       'Per 90 Minutes', 'Per 90 Minutes.1', 'Per 90 Minutes.2',
       'Per 90 Minutes.3', 'Per 90 Minutes.4'],
      dtype='object')

In [148]:
print(fbref_data["season"].min())
print(fbref_data["season"].max())

2122.0
2425.0

In [149]:
fbref_data["season"].describe()

count    11517.000000
mean      2272.443258
std        113.058586
min       2122.000000
25%       2122.000000
50%       2223.000000
75%       2324.000000
max       2425.000000
Name: season, dtype: float64

In [150]:
fbref_data["season"].astype("Int64")

0        <NA>
1        2122
2        2122
3        2122
4        2122
         ...
11513    2425
11514    2425
11515    2425
11516    2425
11517    2425
Name: season, Length: 11518, dtype: Int64

In [151]:
season = fbref_data["season"].copy()

season = season.astype(int)

print(season.dtype)

IntCastingNaNError: Cannot convert non-finite values (NA or inf) to integer

In [152]:
fbref_data.iloc[0]

league                 NaN
season                 NaN
team                   NaN
player                 NaN
nation                 NaN
pos                    NaN
age                    NaN
born                   NaN
Playing Time            MP
Playing Time.1      Starts
Playing Time.2         Min
Playing Time.3         90s
Performance            Gls
Performance.1          Ast
Performance.2          G+A
Performance.3         G-PK
Performance.4           PK
Performance.5        PKatt
Performance.6         CrdY
Performance.7         CrdR
Per 90 Minutes         Gls
Per 90 Minutes.1       Ast
Per 90 Minutes.2       G+A
Per 90 Minutes.3      G-PK
Per 90 Minutes.4    G+A-PK
Name: 0, dtype: object

In [153]:
fbref_data[fbref_data.isna().all(axis=1)]

Empty DataFrame
Columns: [league, season, team, player, nation, pos, age, born, Playing Time, Playing Time.1, Playing Time.2, Playing Time.3, Performance, Performance.1, Performance.2, Performance.3, Performance.4, Performance.5, Performance.6, Performance.7, Per 90 Minutes, Per 90 Minutes.1, Per 90 Minutes.2, Per 90 Minutes.3, Per 90 Minutes.4]
Index: []

[0 rows x 25 columns]

In [154]:
fbref_data[fbref_data["season"].isna()]

,league,season,team,player,nation,pos,age,born,Playing Time,Playing Time.1,...,Performance.3,Performance.4,Performance.5,Performance.6,Performance.7,Per 90 Minutes,Per 90 Minutes.1,Per 90 Minutes.2,Per 90 Minutes.3,Per 90 Minutes.4
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MP,Starts,...,G-PK,PK,PKatt,CrdY,CrdR,Gls,Ast,G+A,G-PK,G+A-PK

In [155]:
fbref_data = fbref_data[
    fbref_data["season"].notna()
].reset_index(drop=True)

In [156]:
fbref_data["season"] = fbref_data["season"].astype(int)

In [157]:
fbref_data.head()

,league,season,team,player,nation,pos,age,born,Playing Time,Playing Time.1,...,Performance.3,Performance.4,Performance.5,Performance.6,Performance.7,Per 90 Minutes,Per 90 Minutes.1,Per 90 Minutes.2,Per 90 Minutes.3,Per 90 Minutes.4
0,ENG-Premier League,2122,Arsenal,Aaron Ramsdale,ENG,GK,23.0,1998.0,34,34,...,0,0,0,1,0,0.0,0.0,0.0,0.0,0.0
1,ENG-Premier League,2122,Arsenal,Ainsley Maitland-Niles,ENG,MF,23.0,1997.0,8,2,...,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0
2,ENG-Premier League,2122,Arsenal,Albert Sambi Lokonga,BEL,MF,21.0,1999.0,19,12,...,0,0,0,5,0,0.0,0.0,0.0,0.0,0.0
3,ENG-Premier League,2122,Arsenal,Alexandre Lacazette,FRA,"FW,MF",30.0,1991.0,30,20,...,2,2,3,0,0,0.2,0.35,0.56,0.1,0.45
4,ENG-Premier League,2122,Arsenal,Ben White,ENG,DF,23.0,1997.0,32,32,...,0,0,0,3,0,0.0,0.0,0.0,0.0,0.0

In [158]:
len(fbref_data.columns)

25

In [159]:
fbref_data["league"].isna().sum()

np.int64(0)

In [28]:
#fbref_data.reset_index(drop=True, inplace=True)

In [160]:
fbref_data = fbref_data.iloc[2:].copy()

In [161]:

new_column_name = {
    #"Unnamed: 0": "league",
    #"Unnamed: 1": "season",
    #"Unnamed: 2": "team",
    #"Unnamed: 3": "player",
    "pos": "position",
    "Playing Time": "matches_played",
    "Playing Time.1": "starts",
    "Playing Time.2": "minutes",
    "Playing Time.3": "nineties",
    "Performance": "goals",
    "Performance.1": "assists",
    "Performance.2": "goal_contributions",
    "Performance.3": "non_penalty_goals",
    "Performance.4": "penalty_goals",
    "Performance.5": "penalty_attempts",
    "Performance.6": "yellow_cards",
    "Performance.7": "red_cards",
    "Per 90 Minutes": "goals_per90",
    "Per 90 Minutes.1": "assists_per90",
    "Per 90 Minutes.2": "ga_per90",
    "Per 90 Minutes.3": "npg_per90",
    "Per 90 Minutes.4": "npga_per90"
}

fbref_data.rename(columns=new_column_name,
          inplace=True)

In [162]:
fbref_data.head(5)

,league,season,team,player,nation,position,age,born,matches_played,starts,...,non_penalty_goals,penalty_goals,penalty_attempts,yellow_cards,red_cards,goals_per90,assists_per90,ga_per90,npg_per90,npga_per90
2,ENG-Premier League,2122,Arsenal,Albert Sambi Lokonga,BEL,MF,21.0,1999.0,19,12,...,0,0,0,5,0,0.0,0.0,0.0,0.0,0.0
3,ENG-Premier League,2122,Arsenal,Alexandre Lacazette,FRA,"FW,MF",30.0,1991.0,30,20,...,2,2,3,0,0,0.2,0.35,0.56,0.1,0.45
4,ENG-Premier League,2122,Arsenal,Ben White,ENG,DF,23.0,1997.0,32,32,...,0,0,0,3,0,0.0,0.0,0.0,0.0,0.0
5,ENG-Premier League,2122,Arsenal,Bernd Leno,GER,GK,29.0,1992.0,4,4,...,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0
6,ENG-Premier League,2122,Arsenal,Bukayo Saka,ENG,"MF,FW",19.0,2001.0,38,36,...,9,2,2,6,0,0.33,0.21,0.54,0.27,0.48

In [163]:
fbref_data["season"].isna().sum()

np.int64(0)

In [164]:
fbref_data[
    fbref_data["season"].isna()
].head()

Empty DataFrame
Columns: [league, season, team, player, nation, position, age, born, matches_played, starts, minutes, nineties, goals, assists, goal_contributions, non_penalty_goals, penalty_goals, penalty_attempts, yellow_cards, red_cards, goals_per90, assists_per90, ga_per90, npg_per90, npga_per90]
Index: []

[0 rows x 25 columns]

In [165]:
fbref_data["season"].value_counts(dropna=False).sort_index()

season
2122    2920
2223    2889
2324    2852
2425    2854
Name: count, dtype: int64

In [166]:
fbref_data['league'].unique()

array(['ENG-Premier League', 'ESP-La Liga', 'FRA-Ligue 1', 'ITA-Serie A',
       'GER-Bundesliga'], dtype=object)

In [167]:
fbref_data['season'].value_counts()

season
2122    2920
2223    2889
2425    2854
2324    2852
Name: count, dtype: int64

In [168]:
fbref_data['position'].value_counts()

position
MF       3536
DF       2898
FW       1532
MF,FW     869
GK        839
FW,MF     717
DF,MF     648
MF,DF     460
DF,FW      14
FW,DF       2
Name: count, dtype: int64

In [169]:
fbref_data['league'].unique()

array(['ENG-Premier League', 'ESP-La Liga', 'FRA-Ligue 1', 'ITA-Serie A',
       'GER-Bundesliga'], dtype=object)

In [170]:
fbref_data["league"].isna().sum()

np.int64(0)

In [171]:
fbref_data.loc[
    fbref_data["league"].isna(),
    ["season", "team"]
].drop_duplicates().sort_values(["season", "team"])

Empty DataFrame
Columns: [season, team]
Index: []

Save dataframe to a new csv file. Reference: https://www.datacamp.com/tutorial/save-as-csv-pandas-dataframe

In [173]:
fbref_data.to_csv("/Users/kachi/Documents/Thesis/data/processed/fbref_clean_data.csv", index=False)