In [31]:
import pandas as pd
import numpy as np

In [32]:
standard = pd.read_csv("/Users/kachi/Documents/Thesis/data/raw/fbref_raw.csv")
shooting = pd.read_csv("/Users/kachi/Documents/Thesis/data/raw/fbref_shooting.csv")
playing_time = pd.read_csv("/Users/kachi/Documents/Thesis/data/raw/fbref_playing_time.csv")
misc = pd.read_csv("/Users/kachi/Documents/Thesis/data/raw/fbref_misc.csv")
keeper = pd.read_csv("/Users/kachi/Documents/Thesis/data/raw/fbref_keeper.csv")

In [33]:
print("standard: ", standard.shape)
print("shooting: ", shooting.shape)
print("playing time: ", playing_time.shape)
print("misc: ", misc.shape)
print("keeper: ", keeper.shape)

standard:  (11518, 25)
shooting:  (11518, 19)
playing time:  (14139, 25)
misc:  (11518, 21)
keeper:  (842, 27)

In [34]:
print("standard: ", standard.columns)
print("="*50)
print("shooting: ", shooting.columns)
print("="*50)
print("playing time: ", playing_time.columns)
print("="*50)
print("misc: ", misc.columns)
print("="*50)
print("keeper: ", keeper.columns)

standard:  Index(['league', 'season', 'team', 'player', 'nation', 'pos', 'age', 'born',
       'Playing Time', 'Playing Time.1', 'Playing Time.2', 'Playing Time.3',
       'Performance', 'Performance.1', 'Performance.2', 'Performance.3',
       'Performance.4', 'Performance.5', 'Performance.6', 'Performance.7',
       'Per 90 Minutes', 'Per 90 Minutes.1', 'Per 90 Minutes.2',
       'Per 90 Minutes.3', 'Per 90 Minutes.4'],
      dtype='object')
==================================================
shooting:  Index(['league', 'season', 'team', 'player', 'nation', 'pos', 'age', 'born',
       '90s', 'Standard', 'Standard.1', 'Standard.2', 'Standard.3',
       'Standard.4', 'Standard.5', 'Standard.6', 'Standard.7', 'Standard.8',
       'Standard.9'],
      dtype='object')
==================================================
playing time:  Index(['league', 'season', 'team', 'player', 'nation', 'pos', 'age', 'born',
       'Playing Time', 'Playing Time.1', 'Playing Time.2', 'Playing Time.3',
       'Playing Time.4', 'Starts', 'Starts.1', 'Starts.2', 'Subs', 'Subs.1',
       'Subs.2', 'Team Success', 'Team Success.1', 'Team Success.2',
       'Team Success.3', 'Team Success.4', 'Team Success.5'],
      dtype='object')
==================================================
misc:  Index(['league', 'season', 'team', 'player', 'nation', 'pos', 'age', 'born',
       '90s', 'Performance', 'Performance.1', 'Performance.2', 'Performance.3',
       'Performance.4', 'Performance.5', 'Performance.6', 'Performance.7',
       'Performance.8', 'Performance.9', 'Performance.10', 'Performance.11'],
      dtype='object')
==================================================
keeper:  Index(['league', 'season', 'team', 'player', 'nation', 'pos', 'age', 'born',
       'Playing Time', 'Playing Time.1', 'Playing Time.2', '90s',
       'Performance', 'Performance.1', 'Performance.2', 'Performance.3',
       'Performance.4', 'Performance.5', 'Performance.6', 'Performance.7',
       'Performance.8', 'Performance.9', 'Penalty Kicks', 'Penalty Kicks.1',
       'Penalty Kicks.2', 'Penalty Kicks.3', 'Penalty Kicks.4'],
      dtype='object')

In [35]:
standard.head()

,league,season,team,player,nation,pos,age,born,Playing Time,Playing Time.1,...,Performance.3,Performance.4,Performance.5,Performance.6,Performance.7,Per 90 Minutes,Per 90 Minutes.1,Per 90 Minutes.2,Per 90 Minutes.3,Per 90 Minutes.4
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MP,Starts,...,G-PK,PK,PKatt,CrdY,CrdR,Gls,Ast,G+A,G-PK,G+A-PK
1,ENG-Premier League,2122.0,Arsenal,Aaron Ramsdale,ENG,GK,23.0,1998.0,34,34,...,0,0,0,1,0,0.0,0.0,0.0,0.0,0.0
2,ENG-Premier League,2122.0,Arsenal,Ainsley Maitland-Niles,ENG,MF,23.0,1997.0,8,2,...,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0
3,ENG-Premier League,2122.0,Arsenal,Albert Sambi Lokonga,BEL,MF,21.0,1999.0,19,12,...,0,0,0,5,0,0.0,0.0,0.0,0.0,0.0
4,ENG-Premier League,2122.0,Arsenal,Alexandre Lacazette,FRA,"FW,MF",30.0,1991.0,30,20,...,2,2,3,0,0,0.2,0.35,0.56,0.1,0.45

In [36]:
shooting.head()

,league,season,team,player,nation,pos,age,born,90s,Standard,Standard.1,Standard.2,Standard.3,Standard.4,Standard.5,Standard.6,Standard.7,Standard.8,Standard.9
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Gls,Sh,SoT,SoT%,Sh/90,SoT/90,G/Sh,G/SoT,PK,PKatt
1,ENG-Premier League,2122.0,Arsenal,Aaron Ramsdale,ENG,GK,23.0,1998.0,34.0,0,0,0,NaN,0.0,0.0,NaN,NaN,0,0
2,ENG-Premier League,2122.0,Arsenal,Ainsley Maitland-Niles,ENG,MF,23.0,1997.0,3.0,0,2,0,0.0,0.67,0.0,0.0,NaN,0,0
3,ENG-Premier League,2122.0,Arsenal,Albert Sambi Lokonga,BEL,MF,21.0,1999.0,12.6,0,20,8,40.0,1.59,0.63,0.0,0.0,0,0
4,ENG-Premier League,2122.0,Arsenal,Alexandre Lacazette,FRA,"FW,MF",30.0,1991.0,19.8,4,46,15,32.6,2.32,0.76,0.04,0.13,2,3

In [37]:
playing_time.head()

,league,season,team,player,nation,pos,age,born,Playing Time,Playing Time.1,...,Starts.2,Subs,Subs.1,Subs.2,Team Success,Team Success.1,Team Success.2,Team Success.3,Team Success.4,Team Success.5
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MP,Min,...,Compl,Subs,Mn/Sub,unSub,PPM,onG,onGA,+/-,+/-90,On-Off
1,ENG-Premier League,2122.0,Arsenal,Aaron Ramsdale,ENG,GK,23.0,1998.0,34,3060,...,34,0,NaN,2,1.94,60,39,21,0.62,2.62
2,ENG-Premier League,2122.0,Arsenal,Ainsley Maitland-Niles,ENG,MF,23.0,1997.0,8,268,...,1,6,16,9,2.0,2,4,-2,-0.67,-1.1
3,ENG-Premier League,2122.0,Arsenal,Albert Sambi Lokonga,BEL,MF,21.0,1999.0,19,1134,...,9,7,20,18,1.74,11,11,0,0.0,-0.51
4,ENG-Premier League,2122.0,Arsenal,Alex Kirk,ENG,DF,18.0,2002.0,0,NaN,...,0,0,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN

In [38]:
misc.head()

,league,season,team,player,nation,pos,age,born,90s,Performance,...,Performance.2,Performance.3,Performance.4,Performance.5,Performance.6,Performance.7,Performance.8,Performance.9,Performance.10,Performance.11
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CrdY,...,2CrdY,Fls,Fld,Off,Crs,Int,TklW,PKwon,PKcon,OG
1,ENG-Premier League,2122.0,Arsenal,Aaron Ramsdale,ENG,GK,23.0,1998.0,34.0,1,...,0,0,5,0,0,0,1,NaN,NaN,0
2,ENG-Premier League,2122.0,Arsenal,Ainsley Maitland-Niles,ENG,MF,23.0,1997.0,3.0,0,...,0,4,3,0,2,4,4,NaN,NaN,0
3,ENG-Premier League,2122.0,Arsenal,Albert Sambi Lokonga,BEL,MF,21.0,1999.0,12.6,5,...,0,12,15,0,2,13,16,NaN,NaN,0
4,ENG-Premier League,2122.0,Arsenal,Alexandre Lacazette,FRA,"FW,MF",30.0,1991.0,19.8,0,...,0,32,29,6,7,4,10,NaN,NaN,0

In [39]:
keeper.head()

,league,season,team,player,nation,pos,age,born,Playing Time,Playing Time.1,...,Performance.5,Performance.6,Performance.7,Performance.8,Performance.9,Penalty Kicks,Penalty Kicks.1,Penalty Kicks.2,Penalty Kicks.3,Penalty Kicks.4
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MP,Starts,...,W,D,L,CS,CS%,PKatt,PKA,PKsv,PKm,Save%
1,ENG-Premier League,2122.0,Arsenal,Aaron Ramsdale,ENG,GK,23.0,1998.0,34,34,...,21,3,10,12,35.3,6,5,0,1,0.0
2,ENG-Premier League,2122.0,Arsenal,Bernd Leno,GER,GK,29.0,1992.0,4,4,...,1,0,3,1,25.0,0,0,0,0,NaN
3,ENG-Premier League,2122.0,Aston Villa,Emiliano Martínez,ARG,GK,28.0,1992.0,36,36,...,13,6,17,11,30.6,6,4,1,1,20.0
4,ENG-Premier League,2122.0,Aston Villa,Jed Steer,ENG,GK,28.0,1992.0,1,1,...,0,0,1,0,0.0,0,0,0,0,NaN

In [40]:
shooting.iloc[0]

league           NaN
season           NaN
team             NaN
player           NaN
nation           NaN
pos              NaN
age              NaN
born             NaN
90s              NaN
Standard         Gls
Standard.1        Sh
Standard.2       SoT
Standard.3      SoT%
Standard.4     Sh/90
Standard.5    SoT/90
Standard.6      G/Sh
Standard.7     G/SoT
Standard.8        PK
Standard.9     PKatt
Name: 0, dtype: object

In [41]:
playing_time.head()

,league,season,team,player,nation,pos,age,born,Playing Time,Playing Time.1,...,Starts.2,Subs,Subs.1,Subs.2,Team Success,Team Success.1,Team Success.2,Team Success.3,Team Success.4,Team Success.5
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MP,Min,...,Compl,Subs,Mn/Sub,unSub,PPM,onG,onGA,+/-,+/-90,On-Off
1,ENG-Premier League,2122.0,Arsenal,Aaron Ramsdale,ENG,GK,23.0,1998.0,34,3060,...,34,0,NaN,2,1.94,60,39,21,0.62,2.62
2,ENG-Premier League,2122.0,Arsenal,Ainsley Maitland-Niles,ENG,MF,23.0,1997.0,8,268,...,1,6,16,9,2.0,2,4,-2,-0.67,-1.1
3,ENG-Premier League,2122.0,Arsenal,Albert Sambi Lokonga,BEL,MF,21.0,1999.0,19,1134,...,9,7,20,18,1.74,11,11,0,0.0,-0.51
4,ENG-Premier League,2122.0,Arsenal,Alex Kirk,ENG,DF,18.0,2002.0,0,NaN,...,0,0,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN

In [42]:
list(enumerate(playing_time.columns))

[(0, 'league'),
 (1, 'season'),
 (2, 'team'),
 (3, 'player'),
 (4, 'nation'),
 (5, 'pos'),
 (6, 'age'),
 (7, 'born'),
 (8, 'Playing Time'),
 (9, 'Playing Time.1'),
 (10, 'Playing Time.2'),
 (11, 'Playing Time.3'),
 (12, 'Playing Time.4'),
 (13, 'Starts'),
 (14, 'Starts.1'),
 (15, 'Starts.2'),
 (16, 'Subs'),
 (17, 'Subs.1'),
 (18, 'Subs.2'),
 (19, 'Team Success'),
 (20, 'Team Success.1'),
 (21, 'Team Success.2'),
 (22, 'Team Success.3'),
 (23, 'Team Success.4'),
 (24, 'Team Success.5')]

In [43]:
standard = standard.iloc[1:].reset_index(drop=True)
shooting = shooting.iloc[1:].reset_index(drop=True)
playing_time = playing_time.iloc[1:].reset_index(drop=True)
misc = misc.iloc[1:].reset_index(drop=True)
keeper = keeper.iloc[1:].reset_index(drop=True)

In [44]:
standard.head()

,league,season,team,player,nation,pos,age,born,Playing Time,Playing Time.1,...,Performance.3,Performance.4,Performance.5,Performance.6,Performance.7,Per 90 Minutes,Per 90 Minutes.1,Per 90 Minutes.2,Per 90 Minutes.3,Per 90 Minutes.4
0,ENG-Premier League,2122.0,Arsenal,Aaron Ramsdale,ENG,GK,23.0,1998.0,34,34,...,0,0,0,1,0,0.0,0.0,0.0,0.0,0.0
1,ENG-Premier League,2122.0,Arsenal,Ainsley Maitland-Niles,ENG,MF,23.0,1997.0,8,2,...,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0
2,ENG-Premier League,2122.0,Arsenal,Albert Sambi Lokonga,BEL,MF,21.0,1999.0,19,12,...,0,0,0,5,0,0.0,0.0,0.0,0.0,0.0
3,ENG-Premier League,2122.0,Arsenal,Alexandre Lacazette,FRA,"FW,MF",30.0,1991.0,30,20,...,2,2,3,0,0,0.2,0.35,0.56,0.1,0.45
4,ENG-Premier League,2122.0,Arsenal,Ben White,ENG,DF,23.0,1997.0,32,32,...,0,0,0,3,0,0.0,0.0,0.0,0.0,0.0

In [45]:
standard.columns = [
    "league",
    "season",
    "team",
    "player",
    "nation",
    "position",
    "age",
    "born",
    "matches_played",
    "starts",
    "minutes",
    "nineties",
    "goals",
    "assists",
    "goal_contributions",
    "non_penalty_goals",
    "penalty_goals",
    "penalty_attempts",
    "yellow_cards",
    "red_cards",
    "goals_per90",
    "assists_per90",
    "ga_per90",
    "npg_per90",
    "npga_per90"
]

standard.columns

Index(['league', 'season', 'team', 'player', 'nation', 'position', 'age',
       'born', 'matches_played', 'starts', 'minutes', 'nineties', 'goals',
       'assists', 'goal_contributions', 'non_penalty_goals', 'penalty_goals',
       'penalty_attempts', 'yellow_cards', 'red_cards', 'goals_per90',
       'assists_per90', 'ga_per90', 'npg_per90', 'npga_per90'],
      dtype='object')

In [46]:
shooting.columns = [
    "league",
    "season",
    "team",
    "player",
    "nation",
    "position",
    "age",
    "born",
    "nineties",
    "goals",
    "shots",
    "shots_on_target",
    "shots_on_target_pct",
    "shots_per90",
    "shots_on_target_per90",
    "goals_per_shot",
    "goals_per_shot_on_target",
    "penalty_goals",
    "penalty_attempts"
]

shooting.columns

Index(['league', 'season', 'team', 'player', 'nation', 'position', 'age',
       'born', 'nineties', 'goals', 'shots', 'shots_on_target',
       'shots_on_target_pct', 'shots_per90', 'shots_on_target_per90',
       'goals_per_shot', 'goals_per_shot_on_target', 'penalty_goals',
       'penalty_attempts'],
      dtype='object')

In [47]:
playing_time.columns = [
    "league",
    "season",
    "team",
    "player",
    "nation",
    "position",
    "age",
    "born",
    "matches_played",
    "minutes",
    "minutes_per_match",
    "minutes_pct",
    "nineties",
    "starts",
    "starts_per_match",
    "complete_matches",
    "substitute_appearances",
    "minutes_per_sub",
    "unused_substitute",
    "points_per_match",
    "team_goals",
    "team_goals_against",
    "goal_difference",
    "goal_difference_per90",
    "on_off"
]

playing_time.columns

Index(['league', 'season', 'team', 'player', 'nation', 'position', 'age',
       'born', 'matches_played', 'minutes', 'minutes_per_match', 'minutes_pct',
       'nineties', 'starts', 'starts_per_match', 'complete_matches',
       'substitute_appearances', 'minutes_per_sub', 'unused_substitute',
       'points_per_match', 'team_goals', 'team_goals_against',
       'goal_difference', 'goal_difference_per90', 'on_off'],
      dtype='object')

In [48]:
misc.columns = [
    "league",
    "season",
    "team",
    "player",
    "nation",
    "position",
    "age",
    "born",
    "nineties",
    "yellow_cards",
    "red_cards",
    "second_yellow_red",
    "fouls_committed",
    "fouls_drawn",
    "offsides",
    "crosses",
    "interceptions",
    "tackles_won",
    "penalties_won",
    "penalties_conceded",
    "own_goals"
]

misc.columns

Index(['league', 'season', 'team', 'player', 'nation', 'position', 'age',
       'born', 'nineties', 'yellow_cards', 'red_cards', 'second_yellow_red',
       'fouls_committed', 'fouls_drawn', 'offsides', 'crosses',
       'interceptions', 'tackles_won', 'penalties_won', 'penalties_conceded',
       'own_goals'],
      dtype='object')

In [49]:
keeper.columns = [
    "league",
    "season",
    "team",
    "player",
    "nation",
    "position",
    "age",
    "born",
    "matches_played",
    "starts",
    "minutes",
    "nineties",
    "goals_against",
    "goals_against_per90",
    "shots_on_target_against",
    "saves",
    "save_percentage",
    "wins",
    "draws",
    "losses",
    "clean_sheets",
    "clean_sheet_percentage",
    "penalties_faced",
    "penalties_saved",
    "penalties_missed",
    "penalties_conceded",
    "penalty_save_percentage"
]

keeper.columns

Index(['league', 'season', 'team', 'player', 'nation', 'position', 'age',
       'born', 'matches_played', 'starts', 'minutes', 'nineties',
       'goals_against', 'goals_against_per90', 'shots_on_target_against',
       'saves', 'save_percentage', 'wins', 'draws', 'losses', 'clean_sheets',
       'clean_sheet_percentage', 'penalties_faced', 'penalties_saved',
       'penalties_missed', 'penalties_conceded', 'penalty_save_percentage'],
      dtype='object')

## Merging all FBref Datasets

In [50]:
shooting.columns.tolist()

['league',
 'season',
 'team',
 'player',
 'nation',
 'position',
 'age',
 'born',
 'nineties',
 'goals',
 'shots',
 'shots_on_target',
 'shots_on_target_pct',
 'shots_per90',
 'shots_on_target_per90',
 'goals_per_shot',
 'goals_per_shot_on_target',
 'penalty_goals',
 'penalty_attempts']

In [51]:
shooting = shooting.drop(
    columns=[
        "nineties",
        "goals",
        "penalty_goals",
        "penalty_attempts"
    ]
)

In [52]:
merge_cols = [
    "league",
    "season",
    "team",
    "player",
    "nation",
    "position",
    "age",
    "born"
]

fbref = standard.merge(
    shooting,
    on=merge_cols,
    how="left"
)

fbref.shape

(11517, 32)

In [53]:
fbref.columns

Index(['league', 'season', 'team', 'player', 'nation', 'position', 'age',
       'born', 'matches_played', 'starts', 'minutes', 'nineties', 'goals',
       'assists', 'goal_contributions', 'non_penalty_goals', 'penalty_goals',
       'penalty_attempts', 'yellow_cards', 'red_cards', 'goals_per90',
       'assists_per90', 'ga_per90', 'npg_per90', 'npga_per90', 'shots',
       'shots_on_target', 'shots_on_target_pct', 'shots_per90',
       'shots_on_target_per90', 'goals_per_shot', 'goals_per_shot_on_target'],
      dtype='object')

In [54]:
playing_time.columns.tolist()

['league',
 'season',
 'team',
 'player',
 'nation',
 'position',
 'age',
 'born',
 'matches_played',
 'minutes',
 'minutes_per_match',
 'minutes_pct',
 'nineties',
 'starts',
 'starts_per_match',
 'complete_matches',
 'substitute_appearances',
 'minutes_per_sub',
 'unused_substitute',
 'points_per_match',
 'team_goals',
 'team_goals_against',
 'goal_difference',
 'goal_difference_per90',
 'on_off']

In [55]:
playing_time = playing_time.drop(
    columns=[
        "matches_played",
        "starts",
        "minutes",
        "nineties"
    ]
)

In [56]:
fbref = fbref.merge(
    playing_time,
    on=merge_cols,
    how="left"
)

fbref.shape

(11517, 45)

In [57]:
fbref.columns.tolist()

['league',
 'season',
 'team',
 'player',
 'nation',
 'position',
 'age',
 'born',
 'matches_played',
 'starts',
 'minutes',
 'nineties',
 'goals',
 'assists',
 'goal_contributions',
 'non_penalty_goals',
 'penalty_goals',
 'penalty_attempts',
 'yellow_cards',
 'red_cards',
 'goals_per90',
 'assists_per90',
 'ga_per90',
 'npg_per90',
 'npga_per90',
 'shots',
 'shots_on_target',
 'shots_on_target_pct',
 'shots_per90',
 'shots_on_target_per90',
 'goals_per_shot',
 'goals_per_shot_on_target',
 'minutes_per_match',
 'minutes_pct',
 'starts_per_match',
 'complete_matches',
 'substitute_appearances',
 'minutes_per_sub',
 'unused_substitute',
 'points_per_match',
 'team_goals',
 'team_goals_against',
 'goal_difference',
 'goal_difference_per90',
 'on_off']

In [63]:
misc.columns = [
    "league",
    "season",
    "team",
    "player",
    "nation",
    "position",
    "age",
    "born",
    "nineties",
    "yellow_cards",
    "red_cards",
    "second_yellows",
    "fouls_committed",
    "fouls_drawn",
    "offsides",
    "crosses",
    "interceptions",
    "tackles_won",
    "penalty_wins",
    "penalty_conceded",
    "own_goals"
]

ValueError: Length mismatch: Expected axis has 18 elements, new values have 21 elements

In [64]:

misc = misc.drop(columns=[
    "nineties",
    "yellow_cards",
    "red_cards"
])

fbref = fbref.merge(
    misc,
    on=merge_cols,
    how="left"
)

fbref.shape

KeyError: "['nineties', 'yellow_cards', 'red_cards'] not found in axis"

In [65]:
fbref.shape

(11517, 55)

In [68]:
list(enumerate(keeper.columns))

[(0, 'league'),
 (1, 'season'),
 (2, 'team'),
 (3, 'player'),
 (4, 'nation'),
 (5, 'position'),
 (6, 'age'),
 (7, 'born'),
 (8, 'matches_played'),
 (9, 'starts'),
 (10, 'minutes'),
 (11, 'nineties'),
 (12, 'goals_against'),
 (13, 'goals_against_per90'),
 (14, 'shots_on_target_against'),
 (15, 'saves'),
 (16, 'save_percentage'),
 (17, 'wins'),
 (18, 'draws'),
 (19, 'losses'),
 (20, 'clean_sheets'),
 (21, 'clean_sheet_percentage'),
 (22, 'penalties_faced'),
 (23, 'penalties_saved'),
 (24, 'penalties_missed'),
 (25, 'penalties_conceded'),
 (26, 'penalty_save_percentage')]

In [69]:
keeper = keeper.drop(
    columns=[
        "matches_played",
        "starts",
        "minutes",
        "nineties"
    ]
)

fbref = fbref.merge(
    keeper,
    on=merge_cols,
    how="left"
)

In [70]:
fbref.shape

(11517, 70)

In [71]:
fbref.isna().sum().sort_values(ascending=False).head(30)

penalty_wins                11517
penalty_conceded            11517
penalty_save_percentage     10941
clean_sheet_percentage      10725
save_percentage             10695
losses                      10676
goals_against               10676
goals_against_per90         10676
shots_on_target_against     10676
wins                        10676
draws                       10676
saves                       10676
clean_sheets                10676
penalties_saved             10676
penalties_faced             10676
penalties_missed            10676
penalties_conceded          10676
goals_per_shot_on_target     3512
goals_per_shot               2134
shots_on_target_pct          2134
minutes_per_sub              1642
starts_per_match             1576
on_off                         75
points_per_match                7
nation                          4
age                             1
born                            1
team_goals_against              0
goal_difference                 0
goal_difference_per90           0
dtype: int64

In [72]:
fbref.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11517 entries, 0 to 11516
Data columns (total 70 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   league                    11517 non-null  object
 1   season                    11517 non-null  float64
 2   team                      11517 non-null  object
 3   player                    11517 non-null  object
 4   nation                    11513 non-null  object
 5   position                  11517 non-null  object
 6   age                       11516 non-null  float64
 7   born                      11516 non-null  float64
 8   matches_played            11517 non-null  object
 9   starts                    11517 non-null  object
 10  minutes                   11517 non-null  object
 11  nineties                  11517 non-null  object
 12  goals                     11517 non-null  object
 13  assists                   11517 non-null  object
 14  goal_contributions        11517 non-null  object
 15  non_penalty_goals         11517 non-null  object
 16  penalty_goals             11517 non-null  object
 17  penalty_attempts          11517 non-null  object
 18  yellow_cards              11517 non-null  object
 19  red_cards                 11517 non-null  object
 20  goals_per90               11517 non-null  object
 21  assists_per90             11517 non-null  object
 22  ga_per90                  11517 non-null  object
 23  npg_per90                 11517 non-null  object
 24  npga_per90                11517 non-null  object
 25  shots                     11517 non-null  object
 26  shots_on_target           11517 non-null  object
 27  shots_on_target_pct       9383 non-null   object
 28  shots_per90               11517 non-null  object
 29  shots_on_target_per90     11517 non-null  object
 30  goals_per_shot            9383 non-null   object
 31  goals_per_shot_on_target  8005 non-null   object
 32  minutes_per_match         11517 non-null  object
 33  minutes_pct               11517 non-null  object
 34  starts_per_match          9941 non-null   object
 35  complete_matches          11517 non-null  object
 36  substitute_appearances    11517 non-null  object
 37  minutes_per_sub           9875 non-null   object
 38  unused_substitute         11517 non-null  object
 39  points_per_match          11510 non-null  object
 40  team_goals                11517 non-null  object
 41  team_goals_against        11517 non-null  object
 42  goal_difference           11517 non-null  object
 43  goal_difference_per90     11517 non-null  object
 44  on_off                    11442 non-null  object
 45  second_yellows            11517 non-null  object
 46  fouls_committed           11517 non-null  object
 47  fouls_drawn               11517 non-null  object
 48  offsides                  11517 non-null  object
 49  crosses                   11517 non-null  object
 50  interceptions             11517 non-null  object
 51  tackles_won               11517 non-null  object
 52  penalty_wins              0 non-null      object
 53  penalty_conceded          0 non-null      object
 54  own_goals                 11517 non-null  object
 55  goals_against             841 non-null    object
 56  goals_against_per90       841 non-null    object
 57  shots_on_target_against   841 non-null    object
 58  saves                     841 non-null    object
 59  save_percentage           822 non-null    object
 60  wins                      841 non-null    object
 61  draws                     841 non-null    object
 62  losses                    841 non-null    object
 63  clean_sheets              841 non-null    object
 64  clean_sheet_percentage    792 non-null    object
 65  penalties_faced           841 non-null    object
 66  penalties_saved           841 non-null    object
 67  penalties_missed          841 non-null    object
 68  penalties_conceded        841 non-null    object
 69  penalty_save_percentage   576 non-null    object
dtypes: float64(3), object(67)
memory usage: 6.2+ MB

In [73]:
fbref = fbref.drop(
    columns=[
        "penalty_wins",
        "penalty_conceded"
    ]
)

In [74]:
fbref.to_csv(
    "/Users/kachi/Documents/Thesis/data/raw/fbref_epl_data.csv",
    index=False
)