In [1]:
from importlib import reload
import transfermarkt_utils

reload(transfermarkt_utils)
from transfermarkt_utils import *

In [18]:
prem_url = (
    "https://www.transfermarkt.com/"
    "premier-league/startseite/wettbewerb/GB1/plus/?saison_id=2025"
)

prem_clubs = get_league_clubs(prem_url)
prem_clubs.head()

,club_name,club_id,squad_url
0,Afc Bournemouth,989,https://www.transfermarkt.com/afc-bournemouth/...
1,Arsenal Fc,11,https://www.transfermarkt.com/arsenal-fc/kader...
2,Aston Villa,405,https://www.transfermarkt.com/aston-villa/kade...
3,Brentford Fc,1148,https://www.transfermarkt.com/brentford-fc/kad...
4,Brighton And Hove Albion,1237,https://www.transfermarkt.com/brighton-amp-hov...

In [19]:
len(prem_clubs)

20

In [20]:
prem_df = collect_league_squads(
    prem_clubs,
    "2526"
)

✓ Afc Bournemouth
✓ Arsenal Fc
✓ Aston Villa
✓ Brentford Fc
✓ Brighton And Hove Albion
✓ Burnley Fc
✓ Chelsea Fc
✓ Crystal Palace
✓ Everton Fc
✓ Fulham Fc
✓ Leeds United
✓ Liverpool Fc
✓ Manchester City
✓ Manchester United
✓ Newcastle United
✓ Nottingham Forest
✓ Sunderland Afc
✓ Tottenham Hotspur
✓ West Ham United
✓ Wolverhampton Wanderers

In [21]:
prem_df.shape

(555, 6)

In [22]:
prem_df.sample(20)

,player_name,position,Age,market_value_eur,club,season
458,Granit Xhaka,Defensive Midfield,33.0,8000000.0,Sunderland Afc,2526
362,Erling Haaland,Centre-Forward,25.0,200000000.0,Manchester City,2526
300,Brenden Aaronson,Attacking Midfield,25.0,22000000.0,Leeds United,2526
549,Tawanda Chirewa,Attacking Midfield,22.0,450000.0,Wolverhampton Wanderers,2526
500,Dominic Solanke,Centre-Forward,28.0,28000000.0,Tottenham Hotspur,2526
11,Adam Smith,Right-Back,35.0,300000.0,Afc Bournemouth,2526
426,Zach Abbott,Centre-Back,20.0,4000000.0,Nottingham Forest,2526
545,Tommy Doyle,Central Midfield,24.0,7000000.0,Wolverhampton Wanderers,2526
13,Alex Scott,Central Midfield,22.0,50000000.0,Afc Bournemouth,2526
15,Lewis Cook,Central Midfield,29.0,11000000.0,Afc Bournemouth,2526
149,Quilindschy Hartman,Left-Back,24.0,16000000.0,Burnley Fc,2526
533,Yerson Mosquera,Centre-Back,25.0,12000000.0,Wolverhampton Wanderers,2526
40,Martin Ødegaard,Attacking Midfield,27.0,65000000.0,Arsenal Fc,2526
467,Romaine Mundle,Left Winger,23.0,7000000.0,Sunderland Afc,2526
52,Ezri Konsa,Centre-Back,28.0,40000000.0,Aston Villa,2526
445,Taiwo Awoniyi,Centre-Forward,28.0,8000000.0,Nottingham Forest,2526
322,Ryan Gravenberch,Defensive Midfield,24.0,80000000.0,Liverpool Fc,2526
76,Caoimhín Kelleher,Goalkeeper,27.0,28000000.0,Brentford Fc,2526
292,Jayden Bogle,Right-Back,25.0,15000000.0,Leeds United,2526
238,Adam Aznou,Left-Back,20.0,6000000.0,Everton Fc,2526

In [23]:
prem_df["club"].nunique()

20

In [24]:
url = prem_clubs.loc[
    prem_clubs["club_name"] == "Brentford Fc",
    "squad_url"
].iloc[0]

tables = pd.read_html(url)

tables[1].head(20)

      #                         Player   Age  Nat.    Contract Market value
0     1   Caoimhín Kelleher Goalkeeper  27.0   NaN  30/06/2030      €28.00m
1   NaN              Caoimhín Kelleher   NaN   NaN         NaN          NaN
2   NaN                     Goalkeeper   NaN   NaN         NaN          NaN
3    12  Hákon Valdimarsson Goalkeeper  24.0   NaN  30/06/2030       €2.50m
4   NaN             Hákon Valdimarsson   NaN   NaN         NaN          NaN
5   NaN                     Goalkeeper   NaN   NaN         NaN          NaN
6     -         Matthew Cox Goalkeeper  23.0   NaN  30/06/2028        €700k
7   NaN                    Matthew Cox   NaN   NaN         NaN          NaN
8   NaN                     Goalkeeper   NaN   NaN         NaN          NaN
9    31     Ellery Balcombe Goalkeeper  26.0   NaN  30/06/2027        €400k
10  NaN                Ellery Balcombe   NaN   NaN         NaN          NaN
11  NaN                     Goalkeeper   NaN   NaN         NaN          NaN
12   41     Julian Eyestone Goalkeeper  20.0   NaN  30/06/2031            -
13  NaN                Julian Eyestone   NaN   NaN         NaN          NaN
14  NaN                     Goalkeeper   NaN   NaN         NaN          NaN
15    4  Sepp van den Berg Centre-Back  24.0   NaN  30/06/2029      €32.00m
16  NaN              Sepp van den Berg   NaN   NaN         NaN          NaN
17  NaN                    Centre-Back   NaN   NaN         NaN          NaN
18   22     Nathan Collins Centre-Back  25.0   NaN  30/06/2029      €30.00m
19  NaN                 Nathan Collins   NaN   NaN         NaN          NaN

In [25]:
brentford_df = tables[1]

brentford_df[
    brentford_df["Market value"].notna()
][["Player", "Market value"]].tail(10)

                                 Player Market value
63     Keane Lewis-Potter Left Midfield      €25.00m
66  Mikkel Damsgaard Attacking Midfield      €30.00m
69    Antoni Milambo Attacking Midfield      €15.00m
72    Fábio Carvalho Attacking Midfield       €8.00m
75             Kevin Schade Left Winger      €35.00m
78             Reiss Nelson Left Winger       €8.00m
81          Dango Ouattara Right Winger      €35.00m
84         Romelle Donovan Right Winger       €3.50m
87           Igor Thiago Centre-Forward      €65.00m
90             Kaye Furo Centre-Forward       €8.00m

In [26]:
brentford_df["position"] = (
    brentford_df["Player"]
    .apply(extract_position)
)

brentford_df[
    brentford_df["position"].isna()
][["Player"]]

                              Player
1                  Caoimhín Kelleher
4                 Hákon Valdimarsson
7                        Matthew Cox
10                   Ellery Balcombe
13                   Julian Eyestone
16                 Sepp van den Berg
19                    Nathan Collins
22                   Kristoffer Ajer
25                     Ethan Pinnock
28                        Rico Henry
31                    Jayden Meghoma
34                    Michael Kayode
37                      Aaron Hickey
40                     Vitaly Janelt
43                       Yunus Konak
46                  Jordan Henderson
49                   Yegor Yarmolyuk
52                    Mathias Jensen
55                      Frank Onyeka
58                      Josh Dasilva
61                      Ryan Trevitt
63  Keane Lewis-Potter Left Midfield
64                Keane Lewis-Potter
65                     Left Midfield
67                  Mikkel Damsgaard
70                    Antoni Milambo
73                    Fábio Carvalho
76                      Kevin Schade
79                      Reiss Nelson
82                    Dango Ouattara
85                   Romelle Donovan
88                       Igor Thiago
91                         Kaye Furo

In [27]:
prem_df.isna().sum()

player_name         0
position            2
Age                 0
market_value_eur    2
club                0
season              0
dtype: int64

In [28]:
prem_df["position"].value_counts()

position
Centre-Back           96
Goalkeeper            66
Centre-Forward        66
Central Midfield      64
Right-Back            49
Defensive Midfield    46
Right Winger          45
Left-Back             43
Attacking Midfield    41
Left Winger           36
Right Midfield         1
Name: count, dtype: int64

In [29]:
prem_df.to_csv(
    "/Users/kachi/Documents/Thesis/data/raw/premier_league_2526.csv",
    index=False
)

## Collecting Premier League 2024-2025

In [2]:
prem_url_24 = (
    "https://www.transfermarkt.com/"
    "premier-league/startseite/wettbewerb/GB1/plus/?saison_id=2024"
)

prem_clubs_24 = get_league_clubs(prem_url_24)
prem_clubs_24.head()

prem_24_df = collect_league_squads(
    prem_clubs_24,
    "2425"
)

✓ Afc Bournemouth
✓ Arsenal Fc
✓ Aston Villa
✓ Brentford Fc
✓ Brighton And Hove Albion
✓ Chelsea Fc
✓ Crystal Palace
✓ Everton Fc
✓ Fulham Fc
✓ Ipswich Town
✓ Leicester City
✓ Liverpool Fc
✓ Manchester City
✓ Manchester United
✓ Newcastle United
✓ Nottingham Forest
✓ Southampton Fc
✓ Tottenham Hotspur
✓ West Ham United
✓ Wolverhampton Wanderers

In [3]:
prem_24_df.shape

(802, 6)

In [4]:
prem_24_df.sample(5)

,player_name,position,Age,market_value_eur,club,season
439,Stephy Mavididi,Left Winger,27.0,10000000.0,Leicester City,2425
38,Daniel Adu-Adjei,Centre-Forward,20.0,150000.0,Afc Bournemouth,2425
454,Virgil van Dijk,Centre-Back,33.0,23000000.0,Liverpool Fc,2425
635,James Ward-Prowse,Central Midfield,30.0,8000000.0,Nottingham Forest,2425
361,Tom Cairney,Central Midfield,34.0,1500000.0,Fulham Fc,2425

In [5]:
prem_24_df["club"].nunique()

20

In [6]:
prem_24_df.isna().sum()

player_name          0
position             0
Age                  0
market_value_eur    84
club                 0
season               0
dtype: int64

In [7]:
prem_24_df["position"].value_counts()

position
Centre-Back           146
Goalkeeper             95
Central Midfield       92
Centre-Forward         91
Right-Back             68
Defensive Midfield     67
Left Winger            67
Attacking Midfield     58
Left-Back              57
Right Winger           50
Left Midfield           4
Right Midfield          4
Second Striker          3
Name: count, dtype: int64

In [8]:
prem_24_df.to_csv(
    "/Users/kachi/Documents/Thesis/data/raw/premier_league_2425.csv",
    index=False
)

## Collect La liga data

In [40]:
la_liga_url = (
    "https://www.transfermarkt.com/laliga/startseite/wettbewerb/ES1/plus/?saison_id=2025"
)

la_liga_clubs = get_league_clubs(la_liga_url)
la_liga_clubs.head()

,club_name,club_id,squad_url
0,Athletic Bilbao,621,https://www.transfermarkt.com/athletic-bilbao/...
1,Atletico De Madrid,13,https://www.transfermarkt.com/atletico-de-madr...
2,Ca Osasuna,331,https://www.transfermarkt.com/ca-osasuna/kader...
3,Celta De Vigo,940,https://www.transfermarkt.com/celta-de-vigo/ka...
4,Deportivo Alaves,1108,https://www.transfermarkt.com/deportivo-alaves...

In [41]:
len(la_liga_clubs)

20

In [65]:
la_liga_df = collect_league_squads(
    la_liga_clubs,
    "2526"
)

✓ Athletic Bilbao
✓ Atletico De Madrid
✓ Ca Osasuna
✓ Celta De Vigo
✓ Deportivo Alaves
✓ Elche Cf
✓ Fc Barcelona
✓ Getafe Cf
✓ Girona Fc
✓ Levante Ud
✓ Rayo Vallecano
✓ Rcd Espanyol Barcelona
✓ Rcd Mallorca
✓ Real Betis Balompie
✓ Real Madrid
✓ Real Oviedo
✓ Real Sociedad
✓ Sevilla Fc
✓ Valencia Cf
✓ Villarreal Cf

In [43]:
la_liga_df.shape

(521, 6)

In [44]:
la_liga_df.sample(20)

,player_name,position,Age,market_value_eur,club,season
269,Óscar Valentín,Central Midfield,31.0,2000000.0,Rayo Vallecano,2526
191,Luis Milla,Central Midfield,31.0,3500000.0,Getafe Cf,2526
233,Unai Elgezabal,Centre-Back,33.0,500000.0,Levante Ud,2526
72,Raúl García,Centre-Forward,25.0,3000000.0,Ca Osasuna,2526
287,Miguel Rubio,Centre-Back,28.0,1500000.0,Rcd Espanyol Barcelona,2526
97,Ferran Jutglà,Right Winger,27.0,10000000.0,Celta De Vigo,2526
132,Pedro Bigas,Centre-Back,36.0,300000.0,Elche Cf,2526
119,Abde Rebbach,Left Winger,27.0,2500000.0,Deportivo Alaves,2526
331,Abdón Prats,Centre-Forward,33.0,800000.0,Rcd Mallorca,2526
367,Álvaro Carreras,Left-Back,23.0,50000000.0,Real Madrid,2526
225,Vladyslav Vanat,Centre-Forward,24.0,15000000.0,Girona Fc,2526
442,Andrés Castrín,Centre-Back,23.0,6000000.0,Sevilla Fc,2526
340,Ricardo Rodríguez,Left-Back,33.0,1400000.0,Real Betis Balompie,2526
138,Federico Redondo,Defensive Midfield,23.0,2500000.0,Elche Cf,2526
250,Iker Losada Second Striker,None,24.0,1800000.0,Levante Ud,2526
2,Dani Vivian,Centre-Back,26.0,20000000.0,Athletic Bilbao,2526
195,Juanmi,Left Winger,33.0,1000000.0,Getafe Cf,2526
396,Nacho Vidal,Right-Back,31.0,1200000.0,Real Oviedo,2526
492,Lucas Beltrán,Centre-Forward,25.0,8000000.0,Valencia Cf,2526
353,Antony,Right Winger,26.0,40000000.0,Real Betis Balompie,2526

In [45]:
la_liga_df["club"].nunique()

20

In [50]:
la_liga_df.isna().sum()

player_name         0
position            0
Age                 0
market_value_eur    1
club                0
season              0
dtype: int64

In [51]:
la_liga_df["position"].value_counts()

position
Centre-Back           93
Central Midfield      75
Centre-Forward        58
Goalkeeper            52
Left Winger           49
Right-Back            47
Right Winger          43
Left-Back             38
Defensive Midfield    33
Attacking Midfield    26
Second Striker         7
Name: count, dtype: int64

In [52]:
la_liga_df[
    la_liga_df["position"].isna()
    | la_liga_df["market_value_eur"].isna()
]

,player_name,position,Age,market_value_eur,club,season
106,Facundo Garcés,Centre-Back,26.0,NaN,Deportivo Alaves,2526

In [53]:
la_liga_df.to_csv(
    "/Users/kachi/Documents/Thesis/data/raw/laliga_2526.csv",
    index=False
)

## Collect bundesliga data

In [54]:
bundesliga_url = (
    "https://www.transfermarkt.com/bundesliga/startseite/wettbewerb/L1/plus/?saison_id=2025"
)

bundesliga_clubs = get_league_clubs(bundesliga_url)
bundesliga_clubs.head()

,club_name,club_id,squad_url
0,1 Fc Heidenheim 1846,2036,https://www.transfermarkt.com/1-fc-heidenheim-...
1,1 Fc Koln,3,https://www.transfermarkt.com/1-fc-koln/kader/...
2,1 Fc Union Berlin,89,https://www.transfermarkt.com/1-fc-union-berli...
3,1 Fsv Mainz 05,39,https://www.transfermarkt.com/1-fsv-mainz-05/k...
4,Bayer 04 Leverkusen,15,https://www.transfermarkt.com/bayer-04-leverku...

In [56]:
len(bundesliga_clubs)

18

In [66]:
bundesliga_df = collect_league_squads(
    bundesliga_clubs,
    "2526"
)

✓ 1 Fc Heidenheim 1846
✓ 1 Fc Koln
✓ 1 Fc Union Berlin
✓ 1 Fsv Mainz 05
✓ Bayer 04 Leverkusen
✓ Bayern Munich
✓ Borussia Dortmund
✓ Borussia Monchengladbach
✓ Eintracht Frankfurt
✓ Fc Augsburg
✓ Fc St Pauli
✓ Hamburger Sv
✓ Rb Leipzig
✓ Sc Freiburg
✓ Sv Werder Bremen
✓ Tsg 1899 Hoffenheim
✓ Vfb Stuttgart
✓ Vfl Wolfsburg

In [67]:
bundesliga_df.shape

(516, 6)

In [68]:
bundesliga_df.sample(20)

,player_name,position,Age,market_value_eur,club,season
422,Keke Topp,Centre-Forward,22.0,3000000.0,Sv Werder Bremen,2526
28,Stefan Schimmer,Centre-Forward,32.0,300000.0,1 Fc Heidenheim 1846,2526
203,Lukas Ullrich,Left-Back,22.0,6000000.0,Borussia Monchengladbach,2526
123,Axel Tape,Centre-Back,18.0,8000000.0,Bayer 04 Leverkusen,2526
298,Joel Chima Fujita,Central Midfield,24.0,10000000.0,Fc St Pauli,2526
347,Lukas Klostermann,Centre-Back,30.0,3500000.0,Rb Leipzig,2526
105,Daniel Gleiber,Central Midfield,21.0,300000.0,1 Fsv Mainz 05,2526
5,Benedikt Gimber,Centre-Back,29.0,1500000.0,1 Fc Heidenheim 1846,2526
270,Elvis Rexhbecaj,Central Midfield,28.0,3500000.0,Fc Augsburg,2526
346,Willi Orbán,Centre-Back,33.0,5000000.0,Rb Leipzig,2526
370,Florian Müller,Goalkeeper,28.0,1200000.0,Sc Freiburg,2526
233,Elias Baum,Right-Back,20.0,4000000.0,Eintracht Frankfurt,2526
477,Badredine Bouanani,Right Winger,21.0,10000000.0,Vfb Stuttgart,2526
125,Issa Traoré,Centre-Back,18.0,800000.0,Bayer 04 Leverkusen,2526
130,Robert Andrich,Defensive Midfield,31.0,6000000.0,Bayer 04 Leverkusen,2526
187,Yan Couto,Right Midfield,24.0,17000000.0,Borussia Dortmund,2526
143,Jonas Urbig,Goalkeeper,22.0,18000000.0,Bayern Munich,2526
84,Dmytro Bogdanov,Centre-Forward,19.0,800000.0,1 Fc Union Berlin,2526
466,Pascal Stenzel,Right-Back,30.0,1200000.0,Vfb Stuttgart,2526
432,Kelven Frees,Centre-Back,21.0,500000.0,Tsg 1899 Hoffenheim,2526

In [69]:
bundesliga_df["club"].nunique()

18

In [70]:
bundesliga_df.isna().sum()

player_name         0
position            0
Age                 0
market_value_eur    2
club                0
season              0
dtype: int64

In [71]:
bundesliga_df["position"].value_counts()

position
Centre-Back           104
Centre-Forward         67
Goalkeeper             64
Central Midfield       49
Defensive Midfield     42
Attacking Midfield     39
Right-Back             38
Left-Back              37
Left Winger            34
Right Winger           31
Second Striker          5
Right Midfield          3
Left Midfield           3
Name: count, dtype: int64

In [72]:
bundesliga_df[
    bundesliga_df["position"].isna()
    | bundesliga_df["market_value_eur"].isna()
]

,player_name,position,Age,market_value_eur,club,season
225,Amil Siljevic,Goalkeeper,19.0,NaN,Eintracht Frankfurt,2526
354,Benno Kaltefleiter,Defensive Midfield,18.0,NaN,Rb Leipzig,2526

In [73]:
bundesliga_df.to_csv(
    "/Users/kachi/Documents/Thesis/data/raw/bundesliga_2526.csv",
    index=False
)

## Collect Serie A data

In [74]:
serie_a_url = (
    "https://www.transfermarkt.com/serie-a/startseite/wettbewerb/IT1/plus/?saison_id=2025"
)

serie_a_clubs = get_league_clubs(serie_a_url)
serie_a_clubs.head()

         club_name  club_id                                          squad_url
0         Ac Milan        5  https://www.transfermarkt.com/ac-milan/kader/v...
1   Acf Fiorentina      430  https://www.transfermarkt.com/acf-fiorentina/k...
2          As Roma       12  https://www.transfermarkt.com/as-roma/kader/ve...
3      Atalanta Bc      800  https://www.transfermarkt.com/atalanta-bc/kade...
4  Bologna Fc 1909     1025  https://www.transfermarkt.com/bologna-fc-1909/...

In [75]:
len(serie_a_clubs)

20

In [76]:
serie_a_df = collect_league_squads(
    serie_a_clubs,
    "2526"
)

✓ Ac Milan
✓ Acf Fiorentina
✓ As Roma
✓ Atalanta Bc
✓ Bologna Fc 1909
✓ Cagliari Calcio
✓ Como 1907
✓ Genoa Cfc
✓ Hellas Verona
✓ Inter Milan
✓ Juventus Fc
✓ Parma Calcio 1913
✓ Pisa Sporting Club
✓ Ss Lazio
✓ Ssc Napoli
✓ Torino Fc
✓ Udinese Calcio
✓ Us Cremonese
✓ Us Lecce
✓ Us Sassuolo

In [77]:
serie_a_df.shape

(536, 6)

In [78]:
serie_a_df.sample(20)

,player_name,position,Age,market_value_eur,club,season
207,Lorenzo Colombo,Centre-Forward,24.0,10000000.0,Genoa Cfc,2526
455,Lapo Nava,Goalkeeper,22.0,100000.0,Us Cremonese,2526
485,Gaspar,Centre-Back,28.0,3000000.0,Us Lecce,2526
450,Idrissa Gueye,Centre-Forward,19.0,8000000.0,Udinese Calcio,2526
128,Elia Caprile,Goalkeeper,24.0,15000000.0,Cagliari Calcio,2526
200,Mikael Egill Ellertsson,Central Midfield,24.0,6000000.0,Genoa Cfc,2526
122,Nicolò Cambiaghi,Left Winger,25.0,14000000.0,Bologna Fc 1909,2526
422,Zanos Savva,Right Winger,20.0,200000.0,Torino Fc,2526
123,Benja Domínguez,Left Winger,22.0,9000000.0,Bologna Fc 1909,2526
464,Tommaso Barbieri,Right-Back,23.0,3800000.0,Us Cremonese,2526
178,Jesús Rodríguez,Left Winger,20.0,30000000.0,Como 1907,2526
458,Sebastiano Luperto,Centre-Back,29.0,4000000.0,Us Cremonese,2526
474,Faris Moumbagna,Centre-Forward,25.0,3500000.0,Us Cremonese,2526
11,Ardon Jashari,Defensive Midfield,23.0,25000000.0,Ac Milan,2526
191,Johan Vásquez,Centre-Back,27.0,12000000.0,Genoa Cfc,2526
341,Filip Stojilkovic,Centre-Forward,26.0,2500000.0,Pisa Sporting Club,2526
362,Daniel Maldini,Attacking Midfield,24.0,9000000.0,Ss Lazio,2526
267,Bremer,Centre-Back,29.0,35000000.0,Juventus Fc,2526
254,Petar Sučić,Central Midfield,22.0,40000000.0,Inter Milan,2526
33,Fabiano Parisi,Left-Back,25.0,6000000.0,Acf Fiorentina,2526

In [79]:
serie_a_df["club"].nunique()

20

In [80]:
serie_a_df.isna().sum()

player_name         0
position            0
Age                 0
market_value_eur    1
club                0
season              0
dtype: int64

In [81]:
serie_a_df["position"].value_counts()

position
Centre-Back           104
Central Midfield       82
Centre-Forward         72
Goalkeeper             68
Left-Back              39
Right-Back             38
Defensive Midfield     38
Attacking Midfield     27
Left Winger            24
Right Winger           24
Right Midfield          8
Left Midfield           7
Second Striker          5
Name: count, dtype: int64

In [82]:
serie_a_df.to_csv(
    "/Users/kachi/Documents/Thesis/data/raw/serie_a_2526.csv",
    index=False
)

## Collect Ligue 1 data

In [83]:
ligue_one_url = (
    "https://www.transfermarkt.com/ligue-1/startseite/wettbewerb/FR1/plus/?saison_id=2025"
)

ligue_one_clubs = get_league_clubs(ligue_one_url)
ligue_one_clubs.head()

    club_name  club_id                                          squad_url
0  Aj Auxerre      290  https://www.transfermarkt.com/aj-auxerre/kader...
1  Angers Sco     1420  https://www.transfermarkt.com/angers-sco/kader...
2   As Monaco      162  https://www.transfermarkt.com/as-monaco/kader/...
3  Fc Lorient     1158  https://www.transfermarkt.com/fc-lorient/kader...
4     Fc Metz      347  https://www.transfermarkt.com/fc-metz/kader/ve...

In [84]:
len(ligue_one_clubs)

18

In [85]:
ligue_one_df = collect_league_squads(
    ligue_one_clubs,
    "2526"
)

✓ Aj Auxerre
✓ Angers Sco
✓ As Monaco
✓ Fc Lorient
✓ Fc Metz
✓ Fc Nantes
✓ Fc Toulouse
✓ Le Havre Ac
✓ Losc Lille
✓ Ogc Nice
✓ Olympique Lyon
✓ Olympique Marseille
✓ Paris Fc
✓ Paris Saint Germain
✓ Rc Lens
✓ Rc Strasbourg Alsace
✓ Stade Brestois 29
✓ Stade Rennais Fc

In [86]:
ligue_one_df.shape

(481, 6)

In [87]:
ligue_one_df.sample(20)

,player_name,position,Age,market_value_eur,club,season
326,Kevin Trapp,Goalkeeper,35.0,1800000.0,Paris Fc,2526
99,Bandiougou Fadiga,Attacking Midfield,25.0,150000.0,Fc Lorient,2526
83,Benjamin Leroy,Goalkeeper,37.0,100000.0,Fc Lorient,2526
43,Yassin Belkhdim,Central Midfield,24.0,7000000.0,Angers Sco,2526
449,Lucas Tousart,Central Midfield,29.0,2000000.0,Stade Brestois 29,2526
345,Alimami Gory,Left Winger,29.0,1500000.0,Paris Fc,2526
262,Tom Louchet,Right Midfield,23.0,7000000.0,Ogc Nice,2526
121,Benjamin Stambouli,Defensive Midfield,35.0,250000.0,Fc Metz,2526
71,Krépin Diatta,Right Midfield,27.0,6000000.0,As Monaco,2526
157,Matthis Abline,Centre-Forward,23.0,20000000.0,Fc Nantes,2526
22,Romain Faivre,Attacking Midfield,27.0,4000000.0,Aj Auxerre,2526
232,Félix Correia,Left Winger,25.0,10000000.0,Losc Lille,2526
64,Vanderson,Right-Back,25.0,18000000.0,As Monaco,2526
1,Théo De Percin,Goalkeeper,25.0,400000.0,Aj Auxerre,2526
170,Rafik Messali,Right-Back,23.0,1500000.0,Fc Toulouse,2526
192,Gautier Lloris,Centre-Back,30.0,3000000.0,Le Havre Ac,2526
467,Przemyslaw Frankowski,Right-Back,31.0,6000000.0,Stade Rennais Fc,2526
107,Pape Sy,Goalkeeper,29.0,600000.0,Fc Metz,2526
72,Aleksandr Golovin,Attacking Midfield,30.0,18000000.0,As Monaco,2526
461,Lilian Brassier,Centre-Back,26.0,12000000.0,Stade Rennais Fc,2526

In [88]:
ligue_one_df["club"].nunique()

18

In [89]:
ligue_one_df.isna().sum()

player_name          0
position             0
Age                  0
market_value_eur    11
club                 0
season               0
dtype: int64

In [91]:
ligue_one_df[
    ligue_one_df["market_value_eur"].isna()
]

,player_name,position,Age,market_value_eur,club,season
3,Louis Mezerette,Goalkeeper,19.0,NaN,Aj Auxerre,2526
9,Elikya Legros,Centre-Back,18.0,NaN,Aj Auxerre,2526
10,Alvin Petit Dol,Centre-Back,19.0,NaN,Aj Auxerre,2526
185,Enzo Faty,Centre-Forward,19.0,NaN,Fc Toulouse,2526
205,Guy-Noël Zohouri,Central Midfield,19.0,NaN,Le Havre Ac,2526
244,Bartosz Zelazowski,Goalkeeper,21.0,NaN,Ogc Nice,2526
273,Lassine Diarra,Goalkeeper,23.0,NaN,Olympique Lyon,2526
302,Jelle Van Neck,Goalkeeper,22.0,NaN,Olympique Marseille,2526
383,Ilan Jourdren,Goalkeeper,17.0,NaN,Rc Lens,2526
399,Alpha Diallo,Attacking Midfield,20.0,NaN,Rc Lens,2526
437,Noah Jauny,Goalkeeper,21.0,NaN,Stade Brestois 29,2526

In [92]:
ligue_one_df = ligue_one_df.dropna(
    subset=["market_value_eur"]
)

In [93]:
ligue_one_df["position"].value_counts()

position
Centre-Back           90
Centre-Forward        59
Central Midfield      53
Goalkeeper            50
Defensive Midfield    42
Right-Back            38
Left Winger           36
Left-Back             35
Right Winger          33
Attacking Midfield    24
Right Midfield         8
Second Striker         1
Left Midfield          1
Name: count, dtype: int64

In [94]:
ligue_one_df.to_csv(
    "/Users/kachi/Documents/Thesis/data/raw/ligue_one_2526.csv",
    index=False
)

## La Liga 24-25 season data collection

In [3]:
laliga_url_24 = (
    "https://www.transfermarkt.com/"
    "laliga/startseite/wettbewerb/ES1/plus/?saison_id=2024"
)

laliga_clubs_24 = get_league_clubs(laliga_url_24)

laliga_24_df = collect_league_squads(
    laliga_clubs_24,
    "2425"
)

✓ Athletic Bilbao
✓ Atletico De Madrid
✓ Ca Osasuna
✓ Cd Leganes
✓ Celta De Vigo
✓ Deportivo Alaves
✓ Fc Barcelona
✓ Getafe Cf
✓ Girona Fc
✓ Rayo Vallecano
✓ Rcd Espanyol Barcelona
✓ Rcd Mallorca
✓ Real Betis Balompie
✓ Real Madrid
✓ Real Sociedad
✓ Real Valladolid Cf
✓ Sevilla Fc
✓ Ud Las Palmas
✓ Valencia Cf
✓ Villarreal Cf

In [15]:
print(laliga_24_df.shape)
print("="*40)
print(laliga_24_df.isna().sum())
print("="*40)
print(laliga_24_df["club"].nunique())
print("="*40)
print(laliga_24_df.sample(5))

(785, 6)
========================================
player_name          0
position             0
Age                  0
market_value_eur    44
club                 0
season               0
dtype: int64
========================================
20
========================================
        player_name          position   Age  market_value_eur  \
653  Isra Domínguez       Left Winger  22.0          200000.0
171    Ilaix Moriba  Central Midfield  22.0         6000000.0
6     Yeray Álvarez       Centre-Back  30.0         7000000.0
116  Jackson Porozo       Centre-Back  24.0         2000000.0
740      Luis Rioja      Right Winger  31.0         2000000.0

                club season
653       Sevilla Fc   2425
171    Celta De Vigo   2425
6    Athletic Bilbao   2425
116       Cd Leganes   2425
740      Valencia Cf   2425

In [16]:
laliga_24_df[
    laliga_24_df["market_value_eur"].isna()
].head(20)

,player_name,position,Age,market_value_eur,club,season
115,Guillermo Ruiz,Goalkeeper,21.0,NaN,Cd Leganes,2425
136,Fer Rodríguez,Central Midfield,22.0,NaN,Cd Leganes,2425
137,Hugo Solozábal,Central Midfield,22.0,NaN,Cd Leganes,2425
145,Piri,Right Winger,21.0,NaN,Cd Leganes,2425
146,Adrián Rosell,Right Winger,20.0,NaN,Cd Leganes,2425
151,Suleiman El Haddadi,Centre-Forward,19.0,NaN,Cd Leganes,2425
267,Djordjije Medenica,Goalkeeper,18.0,NaN,Getafe Cf,2425
268,Diego Ferrer,Goalkeeper,18.0,NaN,Getafe Cf,2425
300,Martín Cuéllar,Centre-Forward,18.0,NaN,Getafe Cf,2425
305,Lucas García,Goalkeeper,21.0,NaN,Girona Fc,2425
306,Aleksandar Andreev,Goalkeeper,19.0,NaN,Girona Fc,2425
307,Jordi Danso,Goalkeeper,18.0,NaN,Girona Fc,2425
308,Pau Funallet,Goalkeeper,18.0,NaN,Girona Fc,2425
314,Oriol Comas,Centre-Back,21.0,NaN,Girona Fc,2425
315,Antal Yaakobishvili,Centre-Back,20.0,NaN,Girona Fc,2425
316,Marc Aznar,Centre-Back,19.0,NaN,Girona Fc,2425
319,Ferran Ruiz,Right-Back,22.0,NaN,Girona Fc,2425
327,Enric García,Central Midfield,18.0,NaN,Girona Fc,2425
328,Raúl Martínez,Central Midfield,23.0,NaN,Girona Fc,2425
330,Ricard Artero,Attacking Midfield,22.0,NaN,Girona Fc,2425

In [17]:
laliga_24_df[
    laliga_24_df["market_value_eur"].isna()
]["club"].value_counts()

club
Girona Fc              15
Ud Las Palmas          11
Cd Leganes              6
Rayo Vallecano          5
Getafe Cf               3
Sevilla Fc              2
Real Betis Balompie     1
Valencia Cf             1
Name: count, dtype: int64

In [18]:
laliga_24_df.to_csv(
    "/Users/kachi/Documents/Thesis/data/raw/la_liga_2425.csv",
    index=False
)

## Seria A 24-25 season data collection

In [19]:
seriea_url_24 = (
    "https://www.transfermarkt.com/"
    "serie-a/startseite/wettbewerb/IT1/plus/?saison_id=2024"
)

seriea_clubs_24 = get_league_clubs(seriea_url_24)

seriea_24_df = collect_league_squads(
    seriea_clubs_24,
    "2425"
)

✓ Ac Milan
✓ Ac Monza
✓ Acf Fiorentina
✓ As Roma
✓ Atalanta Bc
✓ Bologna Fc 1909
✓ Cagliari Calcio
✓ Como 1907
✓ Fc Empoli
✓ Genoa Cfc
✓ Hellas Verona
✓ Inter Milan
✓ Juventus Fc
✓ Parma Calcio 1913
✓ Ss Lazio
✓ Ssc Napoli
✓ Torino Fc
✓ Udinese Calcio
✓ Us Lecce
✓ Venezia Fc

In [20]:
print(seriea_24_df.shape)
print("="*40)
print(seriea_24_df.isna().sum())
print("="*40)
print(seriea_24_df["club"].nunique())
print("="*40)
print(seriea_24_df.sample(5))

(861, 6)
========================================
player_name          0
position             0
Age                  0
market_value_eur    21
club                 0
season               0
dtype: int64
========================================
20
========================================
               player_name          position   Age  market_value_eur  \
343        Niccolò Chiorra        Goalkeeper  24.0          300000.0
673              Luis Hasa  Central Midfield  21.0         1000000.0
260             Yerry Mina       Centre-Back  30.0         3000000.0
483  Alessandro Calligaris        Goalkeeper  20.0          350000.0
741          Edoardo Piana        Goalkeeper  21.0           50000.0

                club season
343        Fc Empoli   2425
673       Ssc Napoli   2425
260  Cagliari Calcio   2425
483      Inter Milan   2425
741   Udinese Calcio   2425

In [21]:
seriea_24_df.to_csv(
    "/Users/kachi/Documents/Thesis/data/raw/serie_a_2425.csv",
    index=False
)

## Bundesliga 24-25 season data collection

In [22]:
bundesliga_url_24 = (
    "https://www.transfermarkt.com/bundesliga/startseite/wettbewerb/L1/plus/?saison_id=2024"
)

bundesliga_clubs_24 = get_league_clubs(bundesliga_url_24)

bundesliga_24_df = collect_league_squads(
    bundesliga_clubs_24,
    "2425"
)

✓ 1 Fc Heidenheim 1846
✓ 1 Fc Union Berlin
✓ 1 Fsv Mainz 05
✓ Bayer 04 Leverkusen
✓ Bayern Munich
✓ Borussia Dortmund
✓ Borussia Monchengladbach
✓ Eintracht Frankfurt
✓ Fc Augsburg
✓ Fc St Pauli
✓ Holstein Kiel
✓ Rb Leipzig
✓ Sc Freiburg
✓ Sv Werder Bremen
✓ Tsg 1899 Hoffenheim
✓ Vfb Stuttgart
✓ Vfl Bochum
✓ Vfl Wolfsburg

In [23]:
print(bundesliga_24_df.shape)
print("="*40)
print(bundesliga_24_df.isna().sum())
print("="*40)
print(bundesliga_24_df["club"].nunique())
print("="*40)
print(bundesliga_24_df.sample(5))

(640, 6)
========================================
player_name          0
position             0
Age                  0
market_value_eur    33
club                 0
season               0
dtype: int64
========================================
18
========================================
           player_name        position   Age  market_value_eur  \
123      Patrik Schick  Centre-Forward  29.0        27000000.0
339     Noah Weißhaupt     Left Winger  23.0         5000000.0
388  Lukas Klostermann     Centre-Back  29.0         8000000.0
615      Joakim Maehle       Left-Back  28.0        14000000.0
175     Waldemar Anton     Centre-Back  28.0        18000000.0

                    club season
123  Bayer 04 Leverkusen   2425
339          Fc St Pauli   2425
388           Rb Leipzig   2425
615        Vfl Wolfsburg   2425
175    Borussia Dortmund   2425

In [24]:
bundesliga_24_df.to_csv(
    "/Users/kachi/Documents/Thesis/data/raw/bundesliga_2425.csv",
    index=False
)

## Ligue 1 24-25 season data collection

In [3]:
ligue1_url_24 = "https://www.transfermarkt.com/ligue-1/startseite/wettbewerb/FR1/plus/?saison_id=2024"

ligue1_clubs_24 = get_league_clubs(ligue1_url_24)

ligue1_24_df = collect_league_squads(
    ligue1_clubs_24,
    "2425"
)

✓ Aj Auxerre
✓ Angers Sco
✓ As Monaco
✓ As Saint Etienne
✓ Fc Nantes
✓ Fc Toulouse
✓ Le Havre Ac
✓ Losc Lille
✓ Montpellier Hsc
✓ Ogc Nice
✓ Olympique Lyon
✓ Olympique Marseille
✓ Paris Saint Germain
✓ Rc Lens
✓ Rc Strasbourg Alsace
✓ Stade Brestois 29
✓ Stade Reims
✓ Stade Rennais Fc

In [4]:
print(ligue1_24_df.shape)
print("="*40)
print(ligue1_24_df.isna().sum())
print("="*40)
print(ligue1_24_df["club"].nunique())
print("="*40)
print(ligue1_24_df.sample(5))

(700, 6)
========================================
player_name          0
position             0
Age                  0
market_value_eur    77
club                 0
season               0
dtype: int64
========================================
18
========================================
             player_name            position   Age  market_value_eur  \
681  Benjamin Bourigeaud    Central Midfield  31.0         7000000.0
424       Jelle Van Neck          Goalkeeper  21.0           50000.0
594           Luck Zogbé          Right-Back  20.0         2500000.0
403        Paul Akouokou  Defensive Midfield  27.0          800000.0
309        Modibo Sagnan         Centre-Back  26.0         3000000.0

                    club season
681     Stade Rennais Fc   2425
424  Olympique Marseille   2425
594    Stade Brestois 29   2425
403       Olympique Lyon   2425
309      Montpellier Hsc   2425

In [5]:
ligue1_24_df.to_csv(
    "/Users/kachi/Documents/Thesis/data/raw/serie_a_2425.csv",
    index=False
)