In [10]:
import pandas as pd
import numpy as np

from importlib import reload
import transfermarkt_utils

reload(transfermarkt_utils)
from transfermarkt_utils import *

In [2]:
pip install soccerdata

Requirement already satisfied: soccerdata in /opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages (1.9.0)
Requirement already satisfied: html5lib<2.0.0,>=1.1 in /opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages (from soccerdata) (1.1)
Requirement already satisfied: lxml>=5.0.0 in /opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages (from soccerdata) (6.1.1)
Requirement already satisfied: pandas!=2.1.0,<4.0.0,>=2.0.0 in /opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages (from soccerdata) (2.3.3)
Requirement already satisfied: rich<16.0.0,>=14.0.0 in /opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages (from soccerdata) (15.0.0)
Requirement already satisfied: seleniumbase<6.0.0,>=4.38.2 in /opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages (from soccerdata) (4.49.2)
Requirement already satisfied: tqdm<6.0.0,>=4.67.1 in /opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages (from soccerdata) (4.67.3)
Requirement already satisfied: unidecode<3.0.0,>=1.4.0 in /opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages (from soccerdata) (1.4.0)
Requirement already satisfied: urllib3<3 in /opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages (from soccerdata) (2.5.0)
Requirement already satisfied: wrapper-tls-requests<3.0.0,>=1.1.4 in /opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages (from soccerdata) (1.2.5)
Requirement already satisfied: six>=1.9 in /opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages (from html5lib<2.0.0,>=1.1->soccerdata) (1.17.0)
Requirement already satisfied: webencodings in /opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages (from html5lib<2.0.0,>=1.1->soccerdata) (0.5.1)
Requirement already satisfied: numpy>=1.26.0 in /opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages (from pandas!=2.1.0,<4.0.0,>=2.0.0->soccerdata) (2.3.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages (from pandas!=2.1.0,<4.0.0,>=2.0.0->soccerdata) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages (from pandas!=2.1.0,<4.0.0,>=2.0.0->soccerdata) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages (from pandas!=2.1.0,<4.0.0,>=2.0.0->soccerdata) (2025.2)
Requirement already satisfied: markdown-it-py>=2.2.0 in /opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages (from rich<16.0.0,>=14.0.0->soccerdata) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages (from rich<16.0.0,>=14.0.0->soccerdata) (2.20.0)
Requirement already satisfied: pip>=26.1.1 in /opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages (from seleniumbase<6.0.0,>=4.38.2->soccerdata) (26.1.1)
Requirement already satisfied: packaging>=26.2 in /opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages (from seleniumbase<6.0.0,>=4.38.2->soccerdata) (26.2)
Requirement already satisfied: setuptools>=82.0.1 in /opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages (from seleniumbase<6.0.0,>=4.38.2->soccerdata) (82.0.1)
Requirement already satisfied: wheel>=0.47.0 in /opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages (from seleniumbase<6.0.0,>=4.38.2->soccerdata) (0.47.0)
Collecting attrs>=26.1.0 (from seleniumbase<6.0.0,>=4.38.2->soccerdata)
  Using cached attrs-26.1.0-py3-none-any.whl.metadata (8.8 kB)
Requirement already satisfied: certifi>=2026.5.20 in /opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages (from seleniumbase<6.0.0,>=4.38.2->soccerdata) (2026.5.20)
Requirement already satisfied: exceptiongroup>=1.3.1 in /opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages (from seleniumbase<6.0.0,>=4.38.2->soccerdata) (1.3.1)
Requirement already satisfied: websockets>=16.0 in /opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages (from seleniumbase<6.0.0,>=4.38.2->soccerdata) (16.0)
Requirement already satisfied: filelock>=3.29.0 in /opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages (from seleniumbase<6.0.0,>=4.38.2->soccerdata) (3.29.0)
Requirement already satisfied: fasteners>=0.20 in /opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages (from seleniumbase<6.0.0,>=4.38.2->soccerdata) (0.20)
Requirement already satisfied: mycdp>=1.3.7 in /opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages (from seleniumbase<6.0.0,>=4.38.2->soccerdata) (1.3.7)
Requirement already satisfied: pynose>=1.5.5 in /opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages (from seleniumbase<6.0.0,>=4.38.2->soccerdata) (1.5.5)
Collecting platformdirs>=4.9.6 (from seleniumbase<6.0.0,>=4.38.2->soccerdata)
  Downloading platformdirs-4.10.0-py3-none-any.whl.metadata (5.5 kB)
Requirement already satisfied: typing-extensions>=4.15.0 in /opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages (from seleniumbase<6.0.0,>=4.38.2->soccerdata) (4.15.0)
Requirement already satisfied: sbvirtualdisplay>=1.4.0 in /opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages (from seleniumbase<6.0.0,>=4.38.2->soccerdata) (1.4.0)
Requirement already satisfied: MarkupSafe>=3.0.3 in /opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages (from seleniumbase<6.0.0,>=4.38.2->soccerdata) (3.0.3)
Requirement already satisfied: Jinja2>=3.1.6 in /opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages (from seleniumbase<6.0.0,>=4.38.2->soccerdata) (3.1.6)
Requirement already satisfied: parse>=1.22.0 in /opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages (from seleniumbase<6.0.0,>=4.38.2->soccerdata) (1.22.0)
Requirement already satisfied: parse-type>=0.6.6 in /opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages (from seleniumbase<6.0.0,>=4.38.2->soccerdata) (0.6.6)
Requirement already satisfied: colorama>=0.4.6 in /opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages (from seleniumbase<6.0.0,>=4.38.2->soccerdata) (0.4.6)
Collecting psutil>=7.2.2 (from seleniumbase<6.0.0,>=4.38.2->soccerdata)
  Using cached psutil-7.2.2-cp36-abi3-macosx_11_0_arm64.whl.metadata (22 kB)
Requirement already satisfied: pyyaml>=6.0.3 in /opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages (from seleniumbase<6.0.0,>=4.38.2->soccerdata) (6.0.3)
Requirement already satisfied: tabcompleter>=1.4.1 in /opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages (from seleniumbase<6.0.0,>=4.38.2->soccerdata) (1.4.1)
Requirement already satisfied: pdbp>=1.8.2 in /opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages (from seleniumbase<6.0.0,>=4.38.2->soccerdata) (1.8.2)
Collecting idna>=3.16 (from seleniumbase<6.0.0,>=4.38.2->soccerdata)
  Downloading idna-3.18-py3-none-any.whl.metadata (6.1 kB)
Collecting charset-normalizer<4,>=3.4.7 (from seleniumbase<6.0.0,>=4.38.2->soccerdata)
  Using cached charset_normalizer-3.4.7-cp313-cp313-macosx_10_13_universal2.whl.metadata (40 kB)
Collecting urllib3<3 (from soccerdata)
  Using cached urllib3-2.7.0-py3-none-any.whl.metadata (6.9 kB)
Collecting requests~=2.34.2 (from seleniumbase<6.0.0,>=4.38.2->soccerdata)
  Using cached requests-2.34.2-py3-none-any.whl.metadata (4.8 kB)
Requirement already satisfied: sniffio==1.3.1 in /opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages (from seleniumbase<6.0.0,>=4.38.2->soccerdata) (1.3.1)
Requirement already satisfied: h11==0.16.0 in /opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages (from seleniumbase<6.0.0,>=4.38.2->soccerdata) (0.16.0)
Requirement already satisfied: outcome==1.3.0.post0 in /opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages (from seleniumbase<6.0.0,>=4.38.2->soccerdata) (1.3.0.post0)
Requirement already satisfied: trio<1,>=0.33.0 in /opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages (from seleniumbase<6.0.0,>=4.38.2->soccerdata) (0.33.0)
Requirement already satisfied: trio-websocket~=0.12.2 in /opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages (from seleniumbase<6.0.0,>=4.38.2->soccerdata) (0.12.2)
Requirement already satisfied: wsproto~=1.3.2 in /opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages (from seleniumbase<6.0.0,>=4.38.2->soccerdata) (1.3.2)
Requirement already satisfied: websocket-client~=1.9.0 in /opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages (from seleniumbase<6.0.0,>=4.38.2->soccerdata) (1.9.0)
Requirement already satisfied: selenium==4.44.0 in /opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages (from seleniumbase<6.0.0,>=4.38.2->soccerdata) (4.44.0)
Requirement already satisfied: cssselect<2,>=1.4.0 in /opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages (from seleniumbase<6.0.0,>=4.38.2->soccerdata) (1.4.0)
Requirement already satisfied: sortedcontainers==2.4.0 in /opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages (from seleniumbase<6.0.0,>=4.38.2->soccerdata) (2.4.0)
Requirement already satisfied: execnet==2.1.2 in /opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages (from seleniumbase<6.0.0,>=4.38.2->soccerdata) (2.1.2)
Requirement already satisfied: iniconfig==2.3.0 in /opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages (from seleniumbase<6.0.0,>=4.38.2->soccerdata) (2.3.0)
Requirement already satisfied: pluggy==1.6.0 in /opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages (from seleniumbase<6.0.0,>=4.38.2->soccerdata) (1.6.0)
Requirement already satisfied: pytest==9.0.3 in /opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages (from seleniumbase<6.0.0,>=4.38.2->soccerdata) (9.0.3)
Requirement already satisfied: pytest-html==4.0.2 in /opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages (from seleniumbase<6.0.0,>=4.38.2->soccerdata) (4.0.2)
Requirement already satisfied: pytest-metadata==3.1.1 in /opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages (from seleniumbase<6.0.0,>=4.38.2->soccerdata) (3.1.1)
Requirement already satisfied: pytest-ordering==0.6 in /opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages (from seleniumbase<6.0.0,>=4.38.2->soccerdata) (0.6)
Requirement already satisfied: pytest-rerunfailures==16.2 in /opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages (from seleniumbase<6.0.0,>=4.38.2->soccerdata) (16.2)
Requirement already satisfied: pytest-xdist==3.8.0 in /opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages (from seleniumbase<6.0.0,>=4.38.2->soccerdata) (3.8.0)
Requirement already satisfied: parameterized==0.9.0 in /opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages (from seleniumbase<6.0.0,>=4.38.2->soccerdata) (0.9.0)
Requirement already satisfied: behave==1.2.6 in /opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages (from seleniumbase<6.0.0,>=4.38.2->soccerdata) (1.2.6)
Requirement already satisfied: soupsieve~=2.8.3 in /opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages (from seleniumbase<6.0.0,>=4.38.2->soccerdata) (2.8.4)
Collecting beautifulsoup4~=4.14.3 (from seleniumbase<6.0.0,>=4.38.2->soccerdata)
  Using cached beautifulsoup4-4.14.3-py3-none-any.whl.metadata (3.8 kB)
Requirement already satisfied: pyotp==2.9.0 in /opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages (from seleniumbase<6.0.0,>=4.38.2->soccerdata) (2.9.0)
Collecting markdown-it-py>=2.2.0 (from rich<16.0.0,>=14.0.0->soccerdata)
  Using cached markdown_it_py-4.2.0-py3-none-any.whl.metadata (7.4 kB)
Requirement already satisfied: mdurl==0.1.2 in /opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages (from seleniumbase<6.0.0,>=4.38.2->soccerdata) (0.1.2)
Requirement already satisfied: pysocks!=1.5.7,<2.0,>=1.5.6 in /opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages (from urllib3[socks]<3.0,>=2.6.3->selenium==4.44.0->seleniumbase<6.0.0,>=4.38.2->soccerdata) (1.7.1)
Requirement already satisfied: orjson in /opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages (from wrapper-tls-requests<3.0.0,>=1.1.4->soccerdata) (3.11.9)
Using cached markdown_it_py-4.2.0-py3-none-any.whl (91 kB)
Using cached beautifulsoup4-4.14.3-py3-none-any.whl (107 kB)
Using cached charset_normalizer-3.4.7-cp313-cp313-macosx_10_13_universal2.whl (309 kB)
Using cached requests-2.34.2-py3-none-any.whl (73 kB)
Downloading idna-3.18-py3-none-any.whl (65 kB)
Using cached urllib3-2.7.0-py3-none-any.whl (131 kB)
Using cached attrs-26.1.0-py3-none-any.whl (67 kB)
Downloading platformdirs-4.10.0-py3-none-any.whl (22 kB)
Using cached psutil-7.2.2-cp36-abi3-macosx_11_0_arm64.whl (129 kB)
Installing collected packages: urllib3, psutil, platformdirs, markdown-it-py, idna, charset-normalizer, beautifulsoup4, attrs, requests
  Attempting uninstall: urllib3
    Found existing installation: urllib3 2.5.0

[notice] A new release of pip is available: 26.1.1 -> 26.1.2
[notice] To update, run: /opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/bin/python -m pip install --upgrade pip
error: uninstall-no-record-file

× Cannot uninstall urllib3 2.5.0
╰─> The package's contents are unknown: no RECORD file was found for urllib3.

hint: The package was installed by brew. You should check if it can uninstall the package.
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0/9 [urllib3]
Note: you may need to restart the kernel to use updated packages.

In [3]:
import soccerdata as sd

[07/07/26 17:13:32] INFO     No custom team name replacements found. You can configure these in       ]8;id=4085150;file:///opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages/soccerdata/_config.py\_config.py]8;;\:]8;id=4085151;file:///opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages/soccerdata/_config.py#92\92]8;;\
                             /Users/kachi/soccerdata/config/teamname_replacements.json.

                    INFO     No custom league dict found. You can configure additional leagues in    ]8;id=4085157;file:///opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages/soccerdata/_config.py\_config.py]8;;\:]8;id=4085158;file:///opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages/soccerdata/_config.py#190\190]8;;\
                             /Users/kachi/soccerdata/config/league_dict.json.

In [7]:
print(sd.__version__)

1.9.0

In [4]:
import sys
!{sys.executable} -m pip install --ignore-installed --no-deps soccerdata

Collecting soccerdata
  Using cached soccerdata-1.9.0-py3-none-any.whl.metadata (5.3 kB)
Using cached soccerdata-1.9.0-py3-none-any.whl (51 kB)
Installing collected packages: soccerdata
Successfully installed soccerdata-1.9.0

In [5]:
import sys
!{sys.executable} -m pip install --ignore-installed Unidecode

Collecting Unidecode
  Using cached Unidecode-1.4.0-py3-none-any.whl.metadata (13 kB)
Using cached Unidecode-1.4.0-py3-none-any.whl (235 kB)
Installing collected packages: Unidecode
Successfully installed Unidecode-1.4.0

In [4]:
import sys

!{sys.executable} -m pip install --ignore-installed html5lib
!{sys.executable} -m pip install --ignore-installed lxml
!{sys.executable} -m pip install --ignore-installed wrapper-tls-requests
!{sys.executable} -m pip install --ignore-installed seleniumbase

Collecting html5lib
  Using cached html5lib-1.1-py2.py3-none-any.whl.metadata (16 kB)
Collecting six>=1.9 (from html5lib)
  Using cached six-1.17.0-py2.py3-none-any.whl.metadata (1.7 kB)
Collecting webencodings (from html5lib)
  Using cached webencodings-0.5.1-py2.py3-none-any.whl.metadata (2.1 kB)
Using cached html5lib-1.1-py2.py3-none-any.whl (112 kB)
Using cached six-1.17.0-py2.py3-none-any.whl (11 kB)
Using cached webencodings-0.5.1-py2.py3-none-any.whl (11 kB)
Installing collected packages: webencodings, six, html5lib
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3/3 [html5lib]
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
seleniumbase 4.49.2 requires attrs>=26.1.0, but you have attrs 25.3.0 which is incompatible.
seleniumbase 4.49.2 requires beautifulsoup4~=4.14.3, but you have beautifulsoup4 4.13.5 which is incompatible.
seleniumbase 4.49.2 requires charset-normalizer<4,>=3.4.7, but you have charset-normalizer 3.4.3 which is incompatible.
seleniumbase 4.49.2 requires idna>=3.16, but you have idna 3.10 which is incompatible.
seleniumbase 4.49.2 requires markdown-it-py==4.2.0; python_version >= "3.10", but you have markdown-it-py 4.0.0 which is incompatible.
seleniumbase 4.49.2 requires platformdirs>=4.9.6; python_version >= "3.10", but you have platformdirs 4.4.0 which is incompatible.
seleniumbase 4.49.2 requires psutil>=7.2.2, but you have psutil 7.0.0 which is incompatible.
seleniumbase 4.49.2 requires requests~=2.34.2; python_version >= "3.10", but you have requests 2.32.5 which is incompatible.
seleniumbase 4.49.2 requires urllib3<3,>=2.7.0; python_version >= "3.10", but you have urllib3 2.5.0 which is incompatible.
Successfully installed html5lib-1.1 six-1.17.0 webencodings-0.5.1
Collecting lxml
  Using cached lxml-6.1.1-cp313-cp313-macosx_10_13_universal2.whl.metadata (3.5 kB)
Using cached lxml-6.1.1-cp313-cp313-macosx_10_13_universal2.whl (8.6 MB)
Installing collected packages: lxml
Successfully installed lxml-6.1.1
Collecting wrapper-tls-requests
  Using cached wrapper_tls_requests-1.2.5-py3-none-any.whl.metadata (8.6 kB)
Collecting charset-normalizer (from wrapper-tls-requests)
  Using cached charset_normalizer-3.4.7-cp313-cp313-macosx_10_13_universal2.whl.metadata (40 kB)
Collecting idna~=3.10 (from wrapper-tls-requests)
  Using cached idna-3.16-py3-none-any.whl.metadata (6.4 kB)
Collecting orjson (from wrapper-tls-requests)
  Using cached orjson-3.11.9-cp313-cp313-macosx_15_0_arm64.whl.metadata (41 kB)
Using cached wrapper_tls_requests-1.2.5-py3-none-any.whl (57 kB)
Using cached idna-3.16-py3-none-any.whl (74 kB)
Using cached charset_normalizer-3.4.7-cp313-cp313-macosx_10_13_universal2.whl (309 kB)
Using cached orjson-3.11.9-cp313-cp313-macosx_15_0_arm64.whl (128 kB)
Installing collected packages: orjson, idna, charset-normalizer, wrapper-tls-requests
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4/4 [wrapper-tls-requests]
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
seleniumbase 4.49.2 requires attrs>=26.1.0, but you have attrs 25.3.0 which is incompatible.
seleniumbase 4.49.2 requires beautifulsoup4~=4.14.3, but you have beautifulsoup4 4.13.5 which is incompatible.
seleniumbase 4.49.2 requires markdown-it-py==4.2.0; python_version >= "3.10", but you have markdown-it-py 4.0.0 which is incompatible.
seleniumbase 4.49.2 requires platformdirs>=4.9.6; python_version >= "3.10", but you have platformdirs 4.4.0 which is incompatible.
seleniumbase 4.49.2 requires psutil>=7.2.2, but you have psutil 7.0.0 which is incompatible.
seleniumbase 4.49.2 requires requests~=2.34.2; python_version >= "3.10", but you have requests 2.32.5 which is incompatible.
seleniumbase 4.49.2 requires urllib3<3,>=2.7.0; python_version >= "3.10", but you have urllib3 2.5.0 which is incompatible.
Successfully installed charset-normalizer-3.4.3 idna-3.10 orjson-3.11.9 wrapper-tls-requests-1.2.5
Collecting seleniumbase
  Using cached seleniumbase-4.49.2-py3-none-any.whl.metadata (91 kB)
Collecting pip>=26.1.1 (from seleniumbase)
  Using cached pip-26.1.1-py3-none-any.whl.metadata (4.6 kB)
Collecting packaging>=26.2 (from seleniumbase)
  Using cached packaging-26.2-py3-none-any.whl.metadata (3.5 kB)
Collecting setuptools>=82.0.1 (from seleniumbase)
  Using cached setuptools-82.0.1-py3-none-any.whl.metadata (6.5 kB)
Collecting wheel>=0.47.0 (from seleniumbase)
  Using cached wheel-0.47.0-py3-none-any.whl.metadata (2.3 kB)
Collecting attrs>=26.1.0 (from seleniumbase)
  Using cached attrs-26.1.0-py3-none-any.whl.metadata (8.8 kB)
Collecting certifi>=2026.5.20 (from seleniumbase)
  Using cached certifi-2026.5.20-py3-none-any.whl.metadata (2.5 kB)
Collecting exceptiongroup>=1.3.1 (from seleniumbase)
  Using cached exceptiongroup-1.3.1-py3-none-any.whl.metadata (6.7 kB)
Collecting websockets>=16.0 (from seleniumbase)
  Using cached websockets-16.0-cp313-cp313-macosx_11_0_arm64.whl.metadata (6.8 kB)
Collecting filelock>=3.29.0 (from seleniumbase)
  Using cached filelock-3.29.0-py3-none-any.whl.metadata (2.0 kB)
Collecting fasteners>=0.20 (from seleniumbase)
  Using cached fasteners-0.20-py3-none-any.whl.metadata (4.8 kB)
Collecting mycdp>=1.3.7 (from seleniumbase)
  Using cached mycdp-1.3.7-py3-none-any.whl.metadata (3.7 kB)
Collecting pynose>=1.5.5 (from seleniumbase)
  Using cached pynose-1.5.5-py3-none-any.whl.metadata (19 kB)
Collecting platformdirs>=4.9.6 (from seleniumbase)
  Using cached platformdirs-4.9.6-py3-none-any.whl.metadata (4.7 kB)
Collecting typing-extensions>=4.15.0 (from seleniumbase)
  Using cached typing_extensions-4.15.0-py3-none-any.whl.metadata (3.3 kB)
Collecting sbvirtualdisplay>=1.4.0 (from seleniumbase)
  Using cached sbvirtualdisplay-1.4.0-py3-none-any.whl.metadata (4.3 kB)
Collecting MarkupSafe>=3.0.3 (from seleniumbase)
  Using cached markupsafe-3.0.3-cp313-cp313-macosx_11_0_arm64.whl.metadata (2.7 kB)
Collecting Jinja2>=3.1.6 (from seleniumbase)
  Using cached jinja2-3.1.6-py3-none-any.whl.metadata (2.9 kB)
Collecting six>=1.17.0 (from seleniumbase)
  Using cached six-1.17.0-py2.py3-none-any.whl.metadata (1.7 kB)
Collecting parse>=1.22.0 (from seleniumbase)
  Downloading parse-1.22.1-py2.py3-none-any.whl.metadata (21 kB)
Collecting parse-type>=0.6.6 (from seleniumbase)
  Using cached parse_type-0.6.6-py2.py3-none-any.whl.metadata (12 kB)
Collecting colorama>=0.4.6 (from seleniumbase)
  Using cached colorama-0.4.6-py2.py3-none-any.whl.metadata (17 kB)
Collecting psutil>=7.2.2 (from seleniumbase)
  Using cached psutil-7.2.2-cp36-abi3-macosx_11_0_arm64.whl.metadata (22 kB)
Collecting pyyaml>=6.0.3 (from seleniumbase)
  Using cached pyyaml-6.0.3-cp313-cp313-macosx_11_0_arm64.whl.metadata (2.4 kB)
Collecting pygments>=2.20.0 (from seleniumbase)
  Using cached pygments-2.20.0-py3-none-any.whl.metadata (2.5 kB)
Collecting tabcompleter>=1.4.1 (from seleniumbase)
  Using cached tabcompleter-1.4.1-py3-none-any.whl.metadata (3.9 kB)
Collecting pdbp>=1.8.2 (from seleniumbase)
  Using cached pdbp-1.8.2-py3-none-any.whl.metadata (7.2 kB)
Collecting idna>=3.16 (from seleniumbase)
  Using cached idna-3.16-py3-none-any.whl.metadata (6.4 kB)
Collecting charset-normalizer<4,>=3.4.7 (from seleniumbase)
  Using cached charset_normalizer-3.4.7-cp313-cp313-macosx_10_13_universal2.whl.metadata (40 kB)
Collecting urllib3<3,>=2.7.0 (from seleniumbase)
  Using cached urllib3-2.7.0-py3-none-any.whl.metadata (6.9 kB)
Collecting requests~=2.34.2 (from seleniumbase)
  Using cached requests-2.34.2-py3-none-any.whl.metadata (4.8 kB)
Collecting sniffio==1.3.1 (from seleniumbase)
  Using cached sniffio-1.3.1-py3-none-any.whl.metadata (3.9 kB)
Collecting h11==0.16.0 (from seleniumbase)
  Using cached h11-0.16.0-py3-none-any.whl.metadata (8.3 kB)
Collecting outcome==1.3.0.post0 (from seleniumbase)
  Using cached outcome-1.3.0.post0-py2.py3-none-any.whl.metadata (2.6 kB)
Collecting trio<1,>=0.33.0 (from seleniumbase)
  Using cached trio-0.33.0-py3-none-any.whl.metadata (8.5 kB)
Collecting trio-websocket~=0.12.2 (from seleniumbase)
  Using cached trio_websocket-0.12.2-py3-none-any.whl.metadata (5.1 kB)
Collecting wsproto~=1.3.2 (from seleniumbase)
  Using cached wsproto-1.3.2-py3-none-any.whl.metadata (5.2 kB)
Collecting websocket-client~=1.9.0 (from seleniumbase)
  Using cached websocket_client-1.9.0-py3-none-any.whl.metadata (8.3 kB)
Collecting selenium==4.44.0 (from seleniumbase)
  Using cached selenium-4.44.0-py3-none-any.whl.metadata (7.4 kB)
Collecting cssselect<2,>=1.4.0 (from seleniumbase)
  Using cached cssselect-1.4.0-py3-none-any.whl.metadata (2.4 kB)
Collecting sortedcontainers==2.4.0 (from seleniumbase)
  Using cached sortedcontainers-2.4.0-py2.py3-none-any.whl.metadata (10 kB)
Collecting execnet==2.1.2 (from seleniumbase)
  Using cached execnet-2.1.2-py3-none-any.whl.metadata (2.9 kB)
Collecting iniconfig==2.3.0 (from seleniumbase)
  Using cached iniconfig-2.3.0-py3-none-any.whl.metadata (2.5 kB)
Collecting pluggy==1.6.0 (from seleniumbase)
  Using cached pluggy-1.6.0-py3-none-any.whl.metadata (4.8 kB)
Collecting pytest==9.0.3 (from seleniumbase)
  Using cached pytest-9.0.3-py3-none-any.whl.metadata (7.6 kB)
Collecting pytest-html==4.0.2 (from seleniumbase)
  Using cached pytest_html-4.0.2-py3-none-any.whl.metadata (3.9 kB)
Collecting pytest-metadata==3.1.1 (from seleniumbase)
  Using cached pytest_metadata-3.1.1-py3-none-any.whl.metadata (8.6 kB)
Collecting pytest-ordering==0.6 (from seleniumbase)
  Using cached pytest_ordering-0.6-py3-none-any.whl.metadata (1.1 kB)
Collecting pytest-rerunfailures==16.2 (from seleniumbase)
  Using cached pytest_rerunfailures-16.2-py3-none-any.whl.metadata (22 kB)
Collecting pytest-xdist==3.8.0 (from seleniumbase)
  Using cached pytest_xdist-3.8.0-py3-none-any.whl.metadata (3.0 kB)
Collecting parameterized==0.9.0 (from seleniumbase)
  Using cached parameterized-0.9.0-py2.py3-none-any.whl.metadata (18 kB)
Collecting behave==1.2.6 (from seleniumbase)
  Using cached behave-1.2.6-py2.py3-none-any.whl.metadata (6.4 kB)
Collecting soupsieve~=2.8.3 (from seleniumbase)
  Downloading soupsieve-2.8.4-py3-none-any.whl.metadata (4.6 kB)
Collecting beautifulsoup4~=4.14.3 (from seleniumbase)
  Using cached beautifulsoup4-4.14.3-py3-none-any.whl.metadata (3.8 kB)
Collecting pyotp==2.9.0 (from seleniumbase)
  Using cached pyotp-2.9.0-py3-none-any.whl.metadata (9.8 kB)
Collecting markdown-it-py==4.2.0 (from seleniumbase)
  Using cached markdown_it_py-4.2.0-py3-none-any.whl.metadata (7.4 kB)
Collecting mdurl==0.1.2 (from seleniumbase)
  Using cached mdurl-0.1.2-py3-none-any.whl.metadata (1.6 kB)
Collecting rich<16,>=15.0.0 (from seleniumbase)
  Using cached rich-15.0.0-py3-none-any.whl.metadata (18 kB)
Collecting pysocks!=1.5.7,<2.0,>=1.5.6 (from urllib3[socks]<3.0,>=2.6.3->selenium==4.44.0->seleniumbase)
  Using cached PySocks-1.7.1-py3-none-any.whl.metadata (13 kB)
Using cached seleniumbase-4.49.2-py3-none-any.whl (666 kB)
Using cached behave-1.2.6-py2.py3-none-any.whl (136 kB)
Using cached execnet-2.1.2-py3-none-any.whl (40 kB)
Using cached h11-0.16.0-py3-none-any.whl (37 kB)
Using cached iniconfig-2.3.0-py3-none-any.whl (7.5 kB)
Using cached markdown_it_py-4.2.0-py3-none-any.whl (91 kB)
Using cached mdurl-0.1.2-py3-none-any.whl (10.0 kB)
Using cached outcome-1.3.0.post0-py2.py3-none-any.whl (10 kB)
Using cached parameterized-0.9.0-py2.py3-none-any.whl (20 kB)
Using cached pluggy-1.6.0-py3-none-any.whl (20 kB)
Using cached pyotp-2.9.0-py3-none-any.whl (13 kB)
Using cached pytest-9.0.3-py3-none-any.whl (375 kB)
Using cached pytest_html-4.0.2-py3-none-any.whl (23 kB)
Using cached pytest_metadata-3.1.1-py3-none-any.whl (11 kB)
Using cached pytest_ordering-0.6-py3-none-any.whl (4.6 kB)
Using cached pytest_rerunfailures-16.2-py3-none-any.whl (14 kB)
Using cached pytest_xdist-3.8.0-py3-none-any.whl (46 kB)
Using cached selenium-4.44.0-py3-none-any.whl (9.7 MB)
Using cached sniffio-1.3.1-py3-none-any.whl (10 kB)
Using cached sortedcontainers-2.4.0-py2.py3-none-any.whl (29 kB)
Using cached beautifulsoup4-4.14.3-py3-none-any.whl (107 kB)
Using cached charset_normalizer-3.4.7-cp313-cp313-macosx_10_13_universal2.whl (309 kB)
Using cached cssselect-1.4.0-py3-none-any.whl (18 kB)
Using cached requests-2.34.2-py3-none-any.whl (73 kB)
Using cached idna-3.16-py3-none-any.whl (74 kB)
Using cached rich-15.0.0-py3-none-any.whl (310 kB)
Using cached pygments-2.20.0-py3-none-any.whl (1.2 MB)
Downloading soupsieve-2.8.4-py3-none-any.whl (37 kB)
Using cached trio-0.33.0-py3-none-any.whl (510 kB)
Using cached trio_websocket-0.12.2-py3-none-any.whl (21 kB)
Using cached typing_extensions-4.15.0-py3-none-any.whl (44 kB)
Using cached urllib3-2.7.0-py3-none-any.whl (131 kB)
Using cached PySocks-1.7.1-py3-none-any.whl (16 kB)
Using cached websocket_client-1.9.0-py3-none-any.whl (82 kB)
Using cached wsproto-1.3.2-py3-none-any.whl (24 kB)
Using cached attrs-26.1.0-py3-none-any.whl (67 kB)
Using cached certifi-2026.5.20-py3-none-any.whl (134 kB)
Using cached colorama-0.4.6-py2.py3-none-any.whl (25 kB)
Using cached exceptiongroup-1.3.1-py3-none-any.whl (16 kB)
Using cached fasteners-0.20-py3-none-any.whl (18 kB)
Using cached filelock-3.29.0-py3-none-any.whl (39 kB)
Using cached jinja2-3.1.6-py3-none-any.whl (134 kB)
Using cached markupsafe-3.0.3-cp313-cp313-macosx_11_0_arm64.whl (12 kB)
Using cached mycdp-1.3.7-py3-none-any.whl (252 kB)
Using cached packaging-26.2-py3-none-any.whl (100 kB)
Downloading parse-1.22.1-py2.py3-none-any.whl (20 kB)
Using cached parse_type-0.6.6-py2.py3-none-any.whl (27 kB)
Using cached pdbp-1.8.2-py3-none-any.whl (21 kB)
Using cached pip-26.1.1-py3-none-any.whl (1.8 MB)
Using cached platformdirs-4.9.6-py3-none-any.whl (21 kB)
Using cached psutil-7.2.2-cp36-abi3-macosx_11_0_arm64.whl (129 kB)
Using cached pynose-1.5.5-py3-none-any.whl (130 kB)
Using cached pyyaml-6.0.3-cp313-cp313-macosx_11_0_arm64.whl (173 kB)
Using cached sbvirtualdisplay-1.4.0-py3-none-any.whl (12 kB)
Using cached setuptools-82.0.1-py3-none-any.whl (1.0 MB)
Using cached six-1.17.0-py2.py3-none-any.whl (11 kB)
Using cached tabcompleter-1.4.1-py3-none-any.whl (6.9 kB)
Using cached websockets-16.0-cp313-cp313-macosx_11_0_arm64.whl (175 kB)
Using cached wheel-0.47.0-py3-none-any.whl (32 kB)
Installing collected packages: sortedcontainers, parse, websockets, websocket-client, urllib3, typing-extensions, tabcompleter, soupsieve, sniffio, six, setuptools, sbvirtualdisplay, pyyaml, pysocks, pyotp, pynose, pygments, psutil, pluggy, platformdirs, pip, parameterized, packaging, mycdp, mdurl, MarkupSafe, iniconfig, idna, h11, filelock, fasteners, execnet, exceptiongroup, cssselect, colorama, charset-normalizer, certifi, attrs, wsproto, wheel, requests, pytest, pdbp, parse-type, outcome, markdown-it-py, Jinja2, beautifulsoup4, trio, rich, pytest-xdist, pytest-rerunfailures, pytest-ordering, pytest-metadata, behave, trio-websocket, pytest-html, selenium, seleniumbase
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 59/59 [seleniumbase]y]t]
Successfully installed Jinja2-3.1.6 MarkupSafe-3.0.3 attrs-25.3.0 beautifulsoup4-4.13.5 behave-1.2.6 certifi-2026.5.20 charset-normalizer-3.4.3 colorama-0.4.6 cssselect-1.4.0 exceptiongroup-1.3.1 execnet-2.1.2 fasteners-0.20 filelock-3.29.0 h11-0.16.0 idna-3.10 iniconfig-2.3.0 markdown-it-py-4.0.0 mdurl-0.1.2 mycdp-1.3.7 outcome-1.3.0.post0 packaging-26.2 parameterized-0.9.0 parse-1.22.0 parse-type-0.6.6 pdbp-1.8.2 pip-26.1.1 platformdirs-4.4.0 pluggy-1.6.0 psutil-7.0.0 pygments-2.20.0 pynose-1.5.5 pyotp-2.9.0 pysocks-1.7.1 pytest-9.0.3 pytest-html-4.0.2 pytest-metadata-3.1.1 pytest-ordering-0.6 pytest-rerunfailures-16.2 pytest-xdist-3.8.0 pyyaml-6.0.3 requests-2.32.5 rich-15.0.0 sbvirtualdisplay-1.4.0 selenium-4.44.0 seleniumbase-4.49.2 setuptools-82.0.1 six-1.17.0 sniffio-1.3.1 sortedcontainers-2.4.0 soupsieve-2.8.4 tabcompleter-1.4.1 trio-0.33.0 trio-websocket-0.12.2 typing-extensions-4.15.0 urllib3-2.5.0 websocket-client-1.9.0 websockets-16.0 wheel-0.47.0 wsproto-1.3.2

In [ ]:
import os
os._exit(0)

In [8]:
help(sd.FBref.read_player_season_stats)

Help on function read_player_season_stats in module soccerdata.fbref:

read_player_season_stats(self, stat_type: str = 'standard') -> pandas.core.frame.DataFrame
    Retrieve players from the datasource for the selected leagues and seasons.

    The following stat types are available:
        * 'standard'
        * 'shooting'
        * 'playing_time'
        * 'keeper'
        * 'misc'

    Parameters
    ----------
    stat_type :str
        Type of stats to retrieve.

    Raises
    ------
    TypeError
        If ``stat_type`` is not valid.

    Returns
    -------
    pd.DataFrame

In [4]:
sd.FBref.available_leagues()

['Big 5 European Leagues Combined',
 'ENG-Premier League',
 'ESP-La Liga',
 'FRA-Ligue 1',
 'GER-Bundesliga',
 'INT-European Championship',
 "INT-Women's World Cup",
 'INT-World Cup',
 'ITA-Serie A']

In [5]:
fbref = sd.FBref(
    leagues="Big 5 European Leagues Combined",
    seasons=["2021-2022","2022-2023","2023-2024","2024-2025"],
    no_cache=True
)

fbref.read_seasons()

[07/07/26 17:13:46] INFO     Saving cached data to /Users/kachi/soccerdata/data/FBref                ]8;id=4085165;file:///opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages/soccerdata/_common.py\_common.py]8;;\:]8;id=4085166;file:///opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages/soccerdata/_common.py#250\250]8;;\

[07/07/26 17:14:11] WARNING  /opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-pack ]8;id=4085173;file:///opt/homebrew/Cellar/python@3.13/3.13.7/Frameworks/Python.framework/Versions/3.13/lib/python3.13/warnings.py\warnings.py]8;;\:]8;id=4085174;file:///opt/homebrew/Cellar/python@3.13/3.13.7/Frameworks/Python.framework/Versions/3.13/lib/python3.13/warnings.py#110\110]8;;\
                             ages/soccerdata/fbref.py:171: FutureWarning: The behavior of DataFrame
                             concatenation with empty or all-NA entries is deprecated. In a future
                             version, this will no longer exclude empty or all-NA columns when
                             determining the result dtypes. To retain the old behavior, exclude the
                             relevant entries before the concat operation.
                               pd.concat(dfs)

                                             format  \
league                          season
Big 5 European Leagues Combined 2122    round-robin
                                2223    round-robin
                                2324    round-robin
                                2425    round-robin

                                                                                      url
league                          season
Big 5 European Leagues Combined 2122    /en/comps/Big5/2021-2022/2021-2022-Big-5-Europ...
                                2223    /en/comps/Big5/2022-2023/2022-2023-Big-5-Europ...
                                2324    /en/comps/Big5/2023-2024/2023-2024-Big-5-Europ...
                                2425    /en/comps/Big5/2024-2025/2024-2025-Big-5-Europ...

In [54]:
# Player season stats

player_season_stats = fbref.read_player_season_stats(stat_type="standard")
player_season_stats.head()

[07/06/26 17:38:51] WARNING  /opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-pack ]8;id=5412764;file:///opt/homebrew/Cellar/python@3.13/3.13.7/Frameworks/Python.framework/Versions/3.13/lib/python3.13/warnings.py\warnings.py]8;;\:]8;id=5412765;file:///opt/homebrew/Cellar/python@3.13/3.13.7/Frameworks/Python.framework/Versions/3.13/lib/python3.13/warnings.py#110\110]8;;\
                             ages/soccerdata/fbref.py:171: FutureWarning: The behavior of DataFrame
                             concatenation with empty or all-NA entries is deprecated. In a future
                             version, this will no longer exclude empty or all-NA columns when
                             determining the result dtypes. To retain the old behavior, exclude the
                             relevant entries before the concat operation.
                               pd.concat(dfs)

                                                         nation    pos age  \

league             season team    player
ENG-Premier League 2122   Arsenal Aaron Ramsdale            ENG     GK  23
                                  Ainsley Maitland-Niles    ENG     MF  23
                                  Albert Sambi Lokonga      BEL     MF  21
                                  Alexandre Lacazette       FRA  FW,MF  30
                                  Ben White                 ENG     DF  23

                                                          born Playing Time  \
                                                                         MP
league             season team    player
ENG-Premier League 2122   Arsenal Aaron Ramsdale          1998           34
                                  Ainsley Maitland-Niles  1997            8
                                  Albert Sambi Lokonga    1999           19
                                  Alexandre Lacazette     1991           30
                                  Ben White               1997           32

                                                                             \
                                                         Starts   Min   90s
league             season team    player
ENG-Premier League 2122   Arsenal Aaron Ramsdale             34  3060  34.0
                                  Ainsley Maitland-Niles      2   268   3.0
                                  Albert Sambi Lokonga       12  1134  12.6
                                  Alexandre Lacazette        20  1782  19.8
                                  Ben White                  32  2880  32.0

                                                         Performance      ...  \
                                                                 Gls Ast  ...
league             season team    player                                  ...
ENG-Premier League 2122   Arsenal Aaron Ramsdale                   0   0  ...
                                  Ainsley Maitland-Niles           0   0  ...
                                  Albert Sambi Lokonga             0   0  ...
                                  Alexandre Lacazette              4   7  ...
                                  Ben White                        0   0  ...

                                                                             \
                                                         G-PK PK PKatt CrdY
league             season team    player
ENG-Premier League 2122   Arsenal Aaron Ramsdale            0  0     0    1
                                  Ainsley Maitland-Niles    0  0     0    0
                                  Albert Sambi Lokonga      0  0     0    5
                                  Alexandre Lacazette       2  2     3    0
                                  Ben White                 0  0     0    3

                                                              Per 90 Minutes  \
                                                         CrdR            Gls
league             season team    player
ENG-Premier League 2122   Arsenal Aaron Ramsdale            0            0.0
                                  Ainsley Maitland-Niles    0            0.0
                                  Albert Sambi Lokonga      0            0.0
                                  Alexandre Lacazette       0            0.2
                                  Ben White                 0            0.0

                                                                           \
                                                           Ast   G+A G-PK
league             season team    player
ENG-Premier League 2122   Arsenal Aaron Ramsdale           0.0   0.0  0.0
                                  Ainsley Maitland-Niles   0.0   0.0  0.0
                                  Albert Sambi Lokonga     0.0   0.0  0.0
                                  Alexandre Lacazette     0.35  0.56  0.1
                                  Ben White                0.0   0.0  0.0


                                                         G+A-PK
league             season team    player
ENG-Premier League 2122   Arsenal Aaron Ramsdale            0.0
                                  Ainsley Maitland-Niles    0.0
                                  Albert Sambi Lokonga      0.0
                                  Alexandre Lacazette      0.45
                                  Ben White                 0.0

[5 rows x 21 columns]

In [55]:
player_season_stats.columns

MultiIndex([(        'nation',       ''),
            (           'pos',       ''),
            (           'age',       ''),
            (          'born',       ''),
            (  'Playing Time',     'MP'),
            (  'Playing Time', 'Starts'),
            (  'Playing Time',    'Min'),
            (  'Playing Time',    '90s'),
            (   'Performance',    'Gls'),
            (   'Performance',    'Ast'),
            (   'Performance',    'G+A'),
            (   'Performance',   'G-PK'),
            (   'Performance',     'PK'),
            (   'Performance',  'PKatt'),
            (   'Performance',   'CrdY'),
            (   'Performance',   'CrdR'),
            ('Per 90 Minutes',    'Gls'),
            ('Per 90 Minutes',    'Ast'),
            ('Per 90 Minutes',    'G+A'),
            ('Per 90 Minutes',   'G-PK'),
            ('Per 90 Minutes', 'G+A-PK')],
           )

In [58]:
# Investigations

print(player_season_stats.index.names)

['league', 'season', 'team', 'player']

In [11]:
#fbref = sd.FBref(
#    leagues="Big 5 European Leagues Combined",
#    seasons=["24-25"],
#    no_cache=True
#)

#player_season_stats = fbref.read_player_season_stats("standard")
#shooting = fbref.read_player_season_stats("shooting")
#passing = fbref.read_player_season_stats("passing")
#possession = fbref.read_player_season_stats("possession")
#defense = fbref.read_player_season_stats("defense")
#keeper = fbref.read_player_season_stats("keeper")

standard = fbref.read_player_season_stats("standard")
keeper = fbref.read_player_season_stats("keeper")
shooting = fbref.read_player_season_stats("shooting")
playing_time = fbref.read_player_season_stats("playing_time")
misc = fbref.read_player_season_stats("misc")

# Fix Bundesliga clubs

standard = fix_bundesliga_league(standard)
keeper = fix_bundesliga_league(keeper)
shooting = fix_bundesliga_league(shooting)
playing_time = fix_bundesliga_league(playing_time)
misc = fix_bundesliga_league(misc)


df = standard.reset_index()


print(df.shape)

[07/07/26 17:44:28] WARNING  /opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-pack ]8;id=4085221;file:///opt/homebrew/Cellar/python@3.13/3.13.7/Frameworks/Python.framework/Versions/3.13/lib/python3.13/warnings.py\warnings.py]8;;\:]8;id=4085222;file:///opt/homebrew/Cellar/python@3.13/3.13.7/Frameworks/Python.framework/Versions/3.13/lib/python3.13/warnings.py#110\110]8;;\
                             ages/soccerdata/fbref.py:171: FutureWarning: The behavior of DataFrame
                             concatenation with empty or all-NA entries is deprecated. In a future
                             version, this will no longer exclude empty or all-NA columns when
                             determining the result dtypes. To retain the old behavior, exclude the
                             relevant entries before the concat operation.
                               pd.concat(dfs)

[07/07/26 17:45:41] WARNING  /opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-pack ]8;id=4085227;file:///opt/homebrew/Cellar/python@3.13/3.13.7/Frameworks/Python.framework/Versions/3.13/lib/python3.13/warnings.py\warnings.py]8;;\:]8;id=4085228;file:///opt/homebrew/Cellar/python@3.13/3.13.7/Frameworks/Python.framework/Versions/3.13/lib/python3.13/warnings.py#110\110]8;;\
                             ages/soccerdata/fbref.py:171: FutureWarning: The behavior of DataFrame
                             concatenation with empty or all-NA entries is deprecated. In a future
                             version, this will no longer exclude empty or all-NA columns when
                             determining the result dtypes. To retain the old behavior, exclude the
                             relevant entries before the concat operation.
                               pd.concat(dfs)

[07/07/26 17:47:11] WARNING  /opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-pack ]8;id=4085233;file:///opt/homebrew/Cellar/python@3.13/3.13.7/Frameworks/Python.framework/Versions/3.13/lib/python3.13/warnings.py\warnings.py]8;;\:]8;id=4085234;file:///opt/homebrew/Cellar/python@3.13/3.13.7/Frameworks/Python.framework/Versions/3.13/lib/python3.13/warnings.py#110\110]8;;\
                             ages/soccerdata/fbref.py:171: FutureWarning: The behavior of DataFrame
                             concatenation with empty or all-NA entries is deprecated. In a future
                             version, this will no longer exclude empty or all-NA columns when
                             determining the result dtypes. To retain the old behavior, exclude the
                             relevant entries before the concat operation.
                               pd.concat(dfs)

[07/07/26 17:48:42] WARNING  /opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-pack ]8;id=4085239;file:///opt/homebrew/Cellar/python@3.13/3.13.7/Frameworks/Python.framework/Versions/3.13/lib/python3.13/warnings.py\warnings.py]8;;\:]8;id=4085240;file:///opt/homebrew/Cellar/python@3.13/3.13.7/Frameworks/Python.framework/Versions/3.13/lib/python3.13/warnings.py#110\110]8;;\
                             ages/soccerdata/fbref.py:171: FutureWarning: The behavior of DataFrame
                             concatenation with empty or all-NA entries is deprecated. In a future
                             version, this will no longer exclude empty or all-NA columns when
                             determining the result dtypes. To retain the old behavior, exclude the
                             relevant entries before the concat operation.
                               pd.concat(dfs)

[07/07/26 17:50:06] WARNING  /opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-pack ]8;id=4085245;file:///opt/homebrew/Cellar/python@3.13/3.13.7/Frameworks/Python.framework/Versions/3.13/lib/python3.13/warnings.py\warnings.py]8;;\:]8;id=4085246;file:///opt/homebrew/Cellar/python@3.13/3.13.7/Frameworks/Python.framework/Versions/3.13/lib/python3.13/warnings.py#110\110]8;;\
                             ages/soccerdata/fbref.py:171: FutureWarning: The behavior of DataFrame
                             concatenation with empty or all-NA entries is deprecated. In a future
                             version, this will no longer exclude empty or all-NA columns when
                             determining the result dtypes. To retain the old behavior, exclude the
                             relevant entries before the concat operation.
                               pd.concat(dfs)

(11517, 26)

In [12]:
# Saving Files For All Stats

# standard

standard.to_csv(
    "/Users/kachi/Documents/Thesis/data/raw/fbref_raw.csv",
    index=False
)

#shooting

shooting.to_csv(
    "/Users/kachi/Documents/Thesis/data/raw/fbref_shooting.csv",
    index=False
)

# passing

playing_time.to_csv(
    "/Users/kachi/Documents/Thesis/data/raw/fbref_playing_time.csv",
    index=False
)

# defense

misc.to_csv(
    "/Users/kachi/Documents/Thesis/data/raw/fbref_misc.csv",
    index=False
)

# Keeper

keeper.to_csv(
    "/Users/kachi/Documents/Thesis/data/raw/fbref_keeper.csv",
    index=False
)

In [61]:
df.loc[
    df["team"] == "Frankfurt",
    ["team", "league"]
]

            team          league

9623   Frankfurt  GER-Bundesliga
9624   Frankfurt  GER-Bundesliga
9625   Frankfurt  GER-Bundesliga
9626   Frankfurt  GER-Bundesliga
9627   Frankfurt  GER-Bundesliga
...          ...             ...
11159  Frankfurt  GER-Bundesliga
11160  Frankfurt  GER-Bundesliga
11161  Frankfurt  GER-Bundesliga
11162  Frankfurt  GER-Bundesliga
11163  Frankfurt  GER-Bundesliga

[115 rows x 2 columns]

In [48]:
print(df["season"].unique())

['2425']

In [45]:
df.head()

               league season     team         player nation    pos age  born  \

0  ENG-Premier League   2425  Arsenal      Ben White    ENG     DF  26  1997
1  ENG-Premier League   2425  Arsenal    Bukayo Saka    ENG  FW,MF  22  2001
2  ENG-Premier League   2425  Arsenal     David Raya    ESP     GK  28  1995
3  ENG-Premier League   2425  Arsenal    Declan Rice    ENG     MF  25  1999
4  ENG-Premier League   2425  Arsenal  Ethan Nwaneri    ENG  FW,MF  17  2007

  Playing Time         ... Performance                    Per 90 Minutes  \
            MP Starts  ...        G-PK PK PKatt CrdY CrdR            Gls
0           17     13  ...           0  0     0    2    0            0.0
1           25     20  ...           5  1     1    3    0           0.31
2           38     38  ...           0  0     0    3    0            0.0
3           35     33  ...           4  0     0    7    1           0.13
4           26     11  ...           4  0     0    1    0            0.4


    Ast   G+A  G-PK G+A-PK
0  0.15  0.15   0.0   0.15
1  0.52  0.83  0.26   0.78
2   0.0   0.0   0.0    0.0
3  0.22  0.35  0.13   0.35
4   0.2   0.6   0.4    0.6

[5 rows x 25 columns]

In [46]:
df['league'].unique()

array(['ENG-Premier League', 'ESP-La Liga', 'FRA-Ligue 1', 'ITA-Serie A',
       'GER-Bundesliga', nan], dtype=object)

In [39]:
standard.head()

                                                nation    pos age  born  \

league             season team    player
ENG-Premier League 2425   Arsenal Ben White        ENG     DF  26  1997
                                  Bukayo Saka      ENG  FW,MF  22  2001
                                  David Raya       ESP     GK  28  1995
                                  Declan Rice      ENG     MF  25  1999
                                  Ethan Nwaneri    ENG  FW,MF  17  2007

                                                Playing Time               \
                                                          MP Starts   Min
league             season team    player
ENG-Premier League 2425   Arsenal Ben White               17     13  1198
                                  Bukayo Saka             25     20  1729
                                  David Raya              38     38  3420
                                  Declan Rice             35     33  2825
                                  Ethan Nwaneri           26     11   895

                                                      Performance      ...  \
                                                  90s         Gls Ast  ...
league             season team    player                               ...
ENG-Premier League 2425   Arsenal Ben White      13.3           0   2  ...
                                  Bukayo Saka    19.2           6  10  ...
                                  David Raya     38.0           0   0  ...
                                  Declan Rice    31.4           4   7  ...
                                  Ethan Nwaneri   9.9           4   2  ...

                                                                         \
                                                G-PK PK PKatt CrdY CrdR
league             season team    player
ENG-Premier League 2425   Arsenal Ben White        0  0     0    2    0
                                  Bukayo Saka      5  1     1    3    0
                                  David Raya       0  0     0    3    0
                                  Declan Rice      4  0     0    7    1
                                  Ethan Nwaneri    4  0     0    1    0

                                                Per 90 Minutes              \
                                                           Gls   Ast   G+A
league             season team    player
ENG-Premier League 2425   Arsenal Ben White                0.0  0.15  0.15
                                  Bukayo Saka             0.31  0.52  0.83
                                  David Raya               0.0   0.0   0.0
                                  Declan Rice             0.13  0.22  0.35
                                  Ethan Nwaneri            0.4   0.2   0.6


                                                 G-PK G+A-PK
league             season team    player
ENG-Premier League 2425   Arsenal Ben White       0.0   0.15
                                  Bukayo Saka    0.26   0.78
                                  David Raya      0.0    0.0
                                  Declan Rice    0.13   0.35
                                  Ethan Nwaneri   0.4    0.6

[5 rows x 21 columns]

In [16]:
player_season_stats.columns

MultiIndex([(        'nation',       ''),
            (           'pos',       ''),
            (           'age',       ''),
            (          'born',       ''),
            (  'Playing Time',     'MP'),
            (  'Playing Time', 'Starts'),
            (  'Playing Time',    'Min'),
            (  'Playing Time',    '90s'),
            (   'Performance',    'Gls'),
            (   'Performance',    'Ast'),
            (   'Performance',    'G+A'),
            (   'Performance',   'G-PK'),
            (   'Performance',     'PK'),
            (   'Performance',  'PKatt'),
            (   'Performance',   'CrdY'),
            (   'Performance',   'CrdR'),
            ('Per 90 Minutes',    'Gls'),
            ('Per 90 Minutes',    'Ast'),
            ('Per 90 Minutes',    'G+A'),
            ('Per 90 Minutes',   'G-PK'),
            ('Per 90 Minutes', 'G+A-PK')],
           )

In [17]:
player_season_stats.columns = [
    '_'.join(col).strip('_')
    for col in player_season_stats.columns
]

In [19]:
shooting = fbref.read_player_season_stats("shooting")

[07/06/26 15:56:02] WARNING  /opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-pack ]8;id=5412674;file:///opt/homebrew/Cellar/python@3.13/3.13.7/Frameworks/Python.framework/Versions/3.13/lib/python3.13/warnings.py\warnings.py]8;;\:]8;id=5412675;file:///opt/homebrew/Cellar/python@3.13/3.13.7/Frameworks/Python.framework/Versions/3.13/lib/python3.13/warnings.py#110\110]8;;\
                             ages/soccerdata/fbref.py:171: FutureWarning: The behavior of DataFrame
                             concatenation with empty or all-NA entries is deprecated. In a future
                             version, this will no longer exclude empty or all-NA columns when
                             determining the result dtypes. To retain the old behavior, exclude the
                             relevant entries before the concat operation.
                               pd.concat(dfs)

In [20]:
playing_time = fbref.read_player_season_stats("playing_time")
misc = fbref.read_player_season_stats("misc")

[07/06/26 15:57:50] WARNING  /opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-pack ]8;id=5412680;file:///opt/homebrew/Cellar/python@3.13/3.13.7/Frameworks/Python.framework/Versions/3.13/lib/python3.13/warnings.py\warnings.py]8;;\:]8;id=5412681;file:///opt/homebrew/Cellar/python@3.13/3.13.7/Frameworks/Python.framework/Versions/3.13/lib/python3.13/warnings.py#110\110]8;;\
                             ages/soccerdata/fbref.py:171: FutureWarning: The behavior of DataFrame
                             concatenation with empty or all-NA entries is deprecated. In a future
                             version, this will no longer exclude empty or all-NA columns when
                             determining the result dtypes. To retain the old behavior, exclude the
                             relevant entries before the concat operation.
                               pd.concat(dfs)

[07/06/26 15:58:25] WARNING  /opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-pack ]8;id=5412686;file:///opt/homebrew/Cellar/python@3.13/3.13.7/Frameworks/Python.framework/Versions/3.13/lib/python3.13/warnings.py\warnings.py]8;;\:]8;id=5412687;file:///opt/homebrew/Cellar/python@3.13/3.13.7/Frameworks/Python.framework/Versions/3.13/lib/python3.13/warnings.py#110\110]8;;\
                             ages/soccerdata/fbref.py:171: FutureWarning: The behavior of DataFrame
                             concatenation with empty or all-NA entries is deprecated. In a future
                             version, this will no longer exclude empty or all-NA columns when
                             determining the result dtypes. To retain the old behavior, exclude the
                             relevant entries before the concat operation.
                               pd.concat(dfs)

In [36]:
########################################################
# Loading First Data From FBREF
########################################################

fbRef_one = pd.read_csv(
    "fbref_standard_2425.csv",
    header=[0,1]
)

fbRef_one.head()

FileNotFoundError: [Errno 2] No such file or directory: '01_fbref_standard_2425.csv'

In [24]:
fbRef_one.columns

MultiIndex([('Unnamed: 0_level_0', 'Unnamed: 0_level_1'),
            ('Unnamed: 1_level_0', 'Unnamed: 1_level_1'),
            ('Unnamed: 2_level_0', 'Unnamed: 2_level_1'),
            ('Unnamed: 3_level_0', 'Unnamed: 3_level_1'),
            (            'nation', 'Unnamed: 4_level_1'),
            (               'pos', 'Unnamed: 5_level_1'),
            (               'age', 'Unnamed: 6_level_1'),
            (              'born', 'Unnamed: 7_level_1'),
            (      'Playing Time',                 'MP'),
            (      'Playing Time',             'Starts'),
            (      'Playing Time',                'Min'),
            (      'Playing Time',                '90s'),
            (       'Performance',                'Gls'),
            (       'Performance',                'Ast'),
            (       'Performance',                'G+A'),
            (       'Performance',               'G-PK'),
            (       'Performance',                 'PK'),
            (       'Performance',              'PKatt'),
            (       'Performance',               'CrdY'),
            (       'Performance',               'CrdR'),
            (    'Per 90 Minutes',                'Gls'),
            (    'Per 90 Minutes',                'Ast'),
            (    'Per 90 Minutes',                'G+A'),
            (    'Per 90 Minutes',               'G-PK'),
            (    'Per 90 Minutes',             'G+A-PK')],
           )

In [25]:
fbRef_one.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11518 entries, 0 to 11517
Data columns (total 25 columns):
 #   Column                                    Non-Null Count  Dtype
---  ------                                    --------------  -----
 0   (Unnamed: 0_level_0, Unnamed: 0_level_1)  9481 non-null   object
 1   (Unnamed: 1_level_0, Unnamed: 1_level_1)  11518 non-null  object
 2   (Unnamed: 2_level_0, Unnamed: 2_level_1)  11518 non-null  object
 3   (Unnamed: 3_level_0, Unnamed: 3_level_1)  11518 non-null  object
 4   (nation, Unnamed: 4_level_1)              11513 non-null  object
 5   (pos, Unnamed: 5_level_1)                 11517 non-null  object
 6   (age, Unnamed: 6_level_1)                 11516 non-null  float64
 7   (born, Unnamed: 7_level_1)                11516 non-null  float64
 8   (Playing Time, MP)                        11517 non-null  float64
 9   (Playing Time, Starts)                    11517 non-null  float64
 10  (Playing Time, Min)                       11517 non-null  float64
 11  (Playing Time, 90s)                       11517 non-null  float64
 12  (Performance, Gls)                        11517 non-null  float64
 13  (Performance, Ast)                        11517 non-null  float64
 14  (Performance, G+A)                        11517 non-null  float64
 15  (Performance, G-PK)                       11517 non-null  float64
 16  (Performance, PK)                         11517 non-null  float64
 17  (Performance, PKatt)                      11517 non-null  float64
 18  (Performance, CrdY)                       11517 non-null  float64
 19  (Performance, CrdR)                       11517 non-null  float64
 20  (Per 90 Minutes, Gls)                     11517 non-null  float64
 21  (Per 90 Minutes, Ast)                     11517 non-null  float64
 22  (Per 90 Minutes, G+A)                     11517 non-null  float64
 23  (Per 90 Minutes, G-PK)                    11517 non-null  float64
 24  (Per 90 Minutes, G+A-PK)                  11517 non-null  float64
dtypes: float64(19), object(6)
memory usage: 2.2+ MB

In [26]:
fbRef_one.columns

MultiIndex([('Unnamed: 0_level_0', 'Unnamed: 0_level_1'),
            ('Unnamed: 1_level_0', 'Unnamed: 1_level_1'),
            ('Unnamed: 2_level_0', 'Unnamed: 2_level_1'),
            ('Unnamed: 3_level_0', 'Unnamed: 3_level_1'),
            (            'nation', 'Unnamed: 4_level_1'),
            (               'pos', 'Unnamed: 5_level_1'),
            (               'age', 'Unnamed: 6_level_1'),
            (              'born', 'Unnamed: 7_level_1'),
            (      'Playing Time',                 'MP'),
            (      'Playing Time',             'Starts'),
            (      'Playing Time',                'Min'),
            (      'Playing Time',                '90s'),
            (       'Performance',                'Gls'),
            (       'Performance',                'Ast'),
            (       'Performance',                'G+A'),
            (       'Performance',               'G-PK'),
            (       'Performance',                 'PK'),
            (       'Performance',              'PKatt'),
            (       'Performance',               'CrdY'),
            (       'Performance',               'CrdR'),
            (    'Per 90 Minutes',                'Gls'),
            (    'Per 90 Minutes',                'Ast'),
            (    'Per 90 Minutes',                'G+A'),
            (    'Per 90 Minutes',               'G-PK'),
            (    'Per 90 Minutes',             'G+A-PK')],
           )

In [33]:
# fbRef_one["Playing Time.1"].head(10)
fbRef_one["Unnamed: 0_level_0"].head(10)

   Unnamed: 0_level_1
0              league
1  ENG-Premier League
2  ENG-Premier League
3  ENG-Premier League
4  ENG-Premier League
5  ENG-Premier League
6  ENG-Premier League
7  ENG-Premier League
8  ENG-Premier League
9  ENG-Premier League

In [28]:
fbRef_one["Playing Time"].head(10)

     MP  Starts     Min   90s
0   NaN     NaN     NaN   NaN
1  34.0    34.0  3060.0  34.0
2   8.0     2.0   268.0   3.0
3  19.0    12.0  1134.0  12.6
4  30.0    20.0  1782.0  19.8
5  32.0    32.0  2880.0  32.0
6   4.0     4.0   360.0   4.0
7  38.0    36.0  2978.0  33.1
8   2.0     2.0   170.0   1.9
9  21.0    16.0  1486.0  16.5

In [35]:
# Renaming columns in the dataset. Reference: https://www.geeksforgeeks.org/pandas/how-to-rename-columns-in-pandas-dataframe/

#fbRef_one.rename(columns={
#    "Unnamed: 0": "league",
#    "Unnamed: 1": "season",
#    "Unnamed: 2": "team",
#    "Unnamed: 3": "player"
#}, inplace=True)

fbRef_one.rename(columns={
    "Unnamed: 0_level_0": "league",
    "Unnamed: 1_level_0": "season",
    "Unnamed: 2_level_0": "team",
    "Unnamed: 3_level_0": "player"
}, inplace=True)



fbRef_one.columns = [
    "nation",
    "pos",
    "age",
    "club",
    "born",
    "matches_played",
    "starts",
    "minutes",
    "nineties",
    "goals",
    "assists",
    "goal_contributions",
    "non_penalty_goals",
    "penalty_goals",
    "penalty_attempts",
    "yellow_cards",
    "red_cards",
    "goals_per90",
    "assists_per90",
    "ga_per90",
    "npg_per90",
    "npga_per90"
]

ValueError: Length mismatch: Expected axis has 25 elements, new values have 22 elements

In [30]:
fbRef_one.head()

   Unnamed: 0_level_0 Unnamed: 1_level_0 Unnamed: 2_level_0  \
   Unnamed: 0_level_1 Unnamed: 1_level_1 Unnamed: 2_level_1
0              league             season               team
1  ENG-Premier League               2122            Arsenal
2  ENG-Premier League               2122            Arsenal
3  ENG-Premier League               2122            Arsenal
4  ENG-Premier League               2122            Arsenal

       Unnamed: 3_level_0             nation                pos  \
       Unnamed: 3_level_1 Unnamed: 4_level_1 Unnamed: 5_level_1
0                  player                NaN                NaN
1          Aaron Ramsdale                ENG                 GK
2  Ainsley Maitland-Niles                ENG                 MF
3    Albert Sambi Lokonga                BEL                 MF
4     Alexandre Lacazette                FRA              FW,MF

                 age               born Playing Time         ... Performance  \
  Unnamed: 6_level_1 Unnamed: 7_level_1           MP Starts  ...        G-PK
0                NaN                NaN          NaN    NaN  ...         NaN
1               23.0             1998.0         34.0   34.0  ...         0.0
2               23.0             1997.0          8.0    2.0  ...         0.0
3               21.0             1999.0         19.0   12.0  ...         0.0
4               30.0             1991.0         30.0   20.0  ...         2.0

                       Per 90 Minutes
    PK PKatt CrdY CrdR            Gls   Ast   G+A G-PK G+A-PK
0  NaN   NaN  NaN  NaN            NaN   NaN   NaN  NaN    NaN
1  0.0   0.0  1.0  0.0            0.0  0.00  0.00  0.0   0.00
2  0.0   0.0  0.0  0.0            0.0  0.00  0.00  0.0   0.00
3  0.0   0.0  5.0  0.0            0.0  0.00  0.00  0.0   0.00
4  2.0   3.0  0.0  0.0            0.2  0.35  0.56  0.1   0.45

[5 rows x 25 columns]

In [46]:
fbRef_one.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19462 entries, 0 to 19461
Data columns (total 26 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   league            16412 non-null  object
 1   season            19461 non-null  object
 2   team              19461 non-null  object
 3   player            19461 non-null  object
 4   nation            19452 non-null  object
 5   pos               19460 non-null  object
 6   age               19457 non-null  object
 7   Club              679 non-null    object
 8   Playing Time      681 non-null    object
 9   Playing Time.1    19461 non-null  object
 10  Playing Time.2    19461 non-null  object
 11  Playing Time.3    19461 non-null  object
 12  Playing Time.4    19461 non-null  object
 13  Performance       19461 non-null  object
 14  Performance.1     19461 non-null  object
 15  Performance.2     19461 non-null  object
 16  Performance.3     19461 non-null  object
 17  Performance.4     19461 non-null  object
 18  Performance.5     19461 non-null  object
 19  Performance.6     19461 non-null  object
 20  Performance.7     19461 non-null  object
 21  Per 90 Minutes    19461 non-null  object
 22  Per 90 Minutes.1  19461 non-null  object
 23  Per 90 Minutes.2  19461 non-null  object
 24  Per 90 Minutes.3  19461 non-null  object
 25  Per 90 Minutes.4  19461 non-null  object
dtypes: object(26)
memory usage: 3.9+ MB

In [47]:
fbRef_one.size

506012

In [48]:
fbRef_one.columns.tolist()

['league',
 'season',
 'team',
 'player',
 'nation',
 'pos',
 'age',
 'Club',
 'Playing Time',
 'Playing Time.1',
 'Playing Time.2',
 'Playing Time.3',
 'Playing Time.4',
 'Performance',
 'Performance.1',
 'Performance.2',
 'Performance.3',
 'Performance.4',
 'Performance.5',
 'Performance.6',
 'Performance.7',
 'Per 90 Minutes',
 'Per 90 Minutes.1',
 'Per 90 Minutes.2',
 'Per 90 Minutes.3',
 'Per 90 Minutes.4']

### Missing Value Count

In [49]:
fbRef_one.isnull().sum().sort_values(ascending=False)

Club                18783
Playing Time        18781
league               3050
nation                 10
age                     5
pos                     2
Performance.3           1
Per 90 Minutes.3        1
Per 90 Minutes.2        1
Per 90 Minutes.1        1
Per 90 Minutes          1
Performance.7           1
Performance.6           1
Performance.5           1
Performance.4           1
Performance             1
Performance.2           1
Performance.1           1
season                  1
Playing Time.4          1
Playing Time.3          1
Playing Time.2          1
Playing Time.1          1
player                  1
team                    1
Per 90 Minutes.4        1
dtype: int64

### Position Distribution

In [50]:
fbRef_one['pos'].value_counts()

pos
MF       6079
DF       4935
FW       2658
GK       1379
MF,FW    1378
FW,MF    1251
DF,MF    1041
MF,DF     708
DF,FW      29
FW,DF       2
Name: count, dtype: int64

In [52]:
# Description of the Dataset

fbRef_one.describe()

,league,season,team,player,nation,pos,age,Club,Playing Time,Playing Time.1,...,Performance.3,Performance.4,Performance.5,Performance.6,Performance.7,Per 90 Minutes,Per 90 Minutes.1,Per 90 Minutes.2,Per 90 Minutes.3,Per 90 Minutes.4
count,16412,19461,19461,19461,19452,19460,19457,679,681,19461,...,19461,19461,19461,19461,19461,19461,19461,19461,19461,19461
unique,8,7,200,7294,195,10,2186,254,23,39,...,33,13,15,19,5,177,161,217,173,214
top,ITA-Serie A,2223,Hellas Verona,Rodri,ESP,MF,25,1. Bayern Munich,1997,1,...,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0
freq,3713,3569,201,14,2500,6079,1341,16,73,1695,...,10948,18162,17888,6556,17557,10812,11250,8469,10948,8530

## TransferMarket Data

In [2]:
%pip install requests beautifulsoup4 lxml pandas

Requirement already satisfied: requests in /opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages (2.32.5)
Requirement already satisfied: beautifulsoup4 in /opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages (4.13.5)
Requirement already satisfied: lxml in /opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages (6.1.1)
Requirement already satisfied: pandas in /opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages (2.3.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages (from requests) (3.4.3)
Requirement already satisfied: idna<4,>=2.5 in /opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages (from requests) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages (from requests) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages (from requests) (2026.5.20)
Requirement already satisfied: soupsieve>1.2 in /opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages (from beautifulsoup4) (2.8.4)
Requirement already satisfied: typing-extensions>=4.0.0 in /opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages (from beautifulsoup4) (4.15.0)
Requirement already satisfied: numpy>=1.26.0 in /opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages (from pandas) (2.3.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in /opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 26.1.1 -> 26.1.2
[notice] To update, run: /opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/bin/python -m pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.