In [4]:
import pandas as pd
import numpy as np

In [1]:
pip install soccerdata

Collecting soccerdata
  Using cached soccerdata-1.9.0-py3-none-any.whl.metadata (5.3 kB)
Collecting html5lib<2.0.0,>=1.1 (from soccerdata)
  Using cached html5lib-1.1-py2.py3-none-any.whl.metadata (16 kB)
Collecting lxml>=5.0.0 (from soccerdata)
  Using cached lxml-6.1.1-cp313-cp313-macosx_10_13_universal2.whl.metadata (3.5 kB)
Requirement already satisfied: pandas!=2.1.0,<4.0.0,>=2.0.0 in /opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages (from soccerdata) (2.3.3)
Requirement already satisfied: rich<16.0.0,>=14.0.0 in /opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages (from soccerdata) (14.3.3)
Collecting seleniumbase<6.0.0,>=4.38.2 (from soccerdata)
  Using cached seleniumbase-4.49.2-py3-none-any.whl.metadata (91 kB)
Requirement already satisfied: tqdm<6.0.0,>=4.67.1 in /opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages (from soccerdata) (4.67.3)
Collecting unidecode<3.0.0,>=1.4.0 (from soccerdata)
  Using cached Unidecode-1.4.0-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: urllib3<3 in /opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages (from soccerdata) (2.5.0)
Collecting wrapper-tls-requests<3.0.0,>=1.1.4 (from soccerdata)
  Using cached wrapper_tls_requests-1.2.5-py3-none-any.whl.metadata (8.6 kB)
Requirement already satisfied: six>=1.9 in /opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages (from html5lib<2.0.0,>=1.1->soccerdata) (1.17.0)
Requirement already satisfied: webencodings in /opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages (from html5lib<2.0.0,>=1.1->soccerdata) (0.5.1)
Requirement already satisfied: numpy>=1.26.0 in /opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages (from pandas!=2.1.0,<4.0.0,>=2.0.0->soccerdata) (2.3.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages (from pandas!=2.1.0,<4.0.0,>=2.0.0->soccerdata) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages (from pandas!=2.1.0,<4.0.0,>=2.0.0->soccerdata) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages (from pandas!=2.1.0,<4.0.0,>=2.0.0->soccerdata) (2025.2)
Requirement already satisfied: markdown-it-py>=2.2.0 in /opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages (from rich<16.0.0,>=14.0.0->soccerdata) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages (from rich<16.0.0,>=14.0.0->soccerdata) (2.19.2)
Collecting pip>=26.1.1 (from seleniumbase<6.0.0,>=4.38.2->soccerdata)
  Using cached pip-26.1.1-py3-none-any.whl.metadata (4.6 kB)
Collecting packaging>=26.2 (from seleniumbase<6.0.0,>=4.38.2->soccerdata)
  Using cached packaging-26.2-py3-none-any.whl.metadata (3.5 kB)
Collecting setuptools>=82.0.1 (from seleniumbase<6.0.0,>=4.38.2->soccerdata)
  Using cached setuptools-82.0.1-py3-none-any.whl.metadata (6.5 kB)
Collecting wheel>=0.47.0 (from seleniumbase<6.0.0,>=4.38.2->soccerdata)
  Using cached wheel-0.47.0-py3-none-any.whl.metadata (2.3 kB)
Collecting attrs>=26.1.0 (from seleniumbase<6.0.0,>=4.38.2->soccerdata)
  Using cached attrs-26.1.0-py3-none-any.whl.metadata (8.8 kB)
Collecting certifi>=2026.5.20 (from seleniumbase<6.0.0,>=4.38.2->soccerdata)
  Using cached certifi-2026.5.20-py3-none-any.whl.metadata (2.5 kB)
Collecting exceptiongroup>=1.3.1 (from seleniumbase<6.0.0,>=4.38.2->soccerdata)
  Using cached exceptiongroup-1.3.1-py3-none-any.whl.metadata (6.7 kB)
Requirement already satisfied: websockets>=16.0 in /opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages (from seleniumbase<6.0.0,>=4.38.2->soccerdata) (16.0)
Collecting filelock>=3.29.0 (from seleniumbase<6.0.0,>=4.38.2->soccerdata)
  Using cached filelock-3.29.0-py3-none-any.whl.metadata (2.0 kB)
Collecting fasteners>=0.20 (from seleniumbase<6.0.0,>=4.38.2->soccerdata)
  Using cached fasteners-0.20-py3-none-any.whl.metadata (4.8 kB)
Collecting mycdp>=1.3.7 (from seleniumbase<6.0.0,>=4.38.2->soccerdata)
  Using cached mycdp-1.3.7-py3-none-any.whl.metadata (3.7 kB)
Collecting pynose>=1.5.5 (from seleniumbase<6.0.0,>=4.38.2->soccerdata)
  Using cached pynose-1.5.5-py3-none-any.whl.metadata (19 kB)
Collecting platformdirs>=4.9.6 (from seleniumbase<6.0.0,>=4.38.2->soccerdata)
  Using cached platformdirs-4.9.6-py3-none-any.whl.metadata (4.7 kB)
Requirement already satisfied: typing-extensions>=4.15.0 in /opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages (from seleniumbase<6.0.0,>=4.38.2->soccerdata) (4.15.0)
Collecting sbvirtualdisplay>=1.4.0 (from seleniumbase<6.0.0,>=4.38.2->soccerdata)
  Using cached sbvirtualdisplay-1.4.0-py3-none-any.whl.metadata (4.3 kB)
Collecting MarkupSafe>=3.0.3 (from seleniumbase<6.0.0,>=4.38.2->soccerdata)
  Using cached markupsafe-3.0.3-cp313-cp313-macosx_11_0_arm64.whl.metadata (2.7 kB)
Requirement already satisfied: Jinja2>=3.1.6 in /opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages (from seleniumbase<6.0.0,>=4.38.2->soccerdata) (3.1.6)
Requirement already satisfied: parse>=1.22.0 in /opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages (from seleniumbase<6.0.0,>=4.38.2->soccerdata) (1.22.0)
Collecting parse-type>=0.6.6 (from seleniumbase<6.0.0,>=4.38.2->soccerdata)
  Using cached parse_type-0.6.6-py2.py3-none-any.whl.metadata (12 kB)
Collecting colorama>=0.4.6 (from seleniumbase<6.0.0,>=4.38.2->soccerdata)
  Using cached colorama-0.4.6-py2.py3-none-any.whl.metadata (17 kB)
Collecting psutil>=7.2.2 (from seleniumbase<6.0.0,>=4.38.2->soccerdata)
  Using cached psutil-7.2.2-cp36-abi3-macosx_11_0_arm64.whl.metadata (22 kB)
Collecting pyyaml>=6.0.3 (from seleniumbase<6.0.0,>=4.38.2->soccerdata)
  Using cached pyyaml-6.0.3-cp313-cp313-macosx_11_0_arm64.whl.metadata (2.4 kB)
Collecting pygments<3.0.0,>=2.13.0 (from rich<16.0.0,>=14.0.0->soccerdata)
  Using cached pygments-2.20.0-py3-none-any.whl.metadata (2.5 kB)
Collecting tabcompleter>=1.4.1 (from seleniumbase<6.0.0,>=4.38.2->soccerdata)
  Using cached tabcompleter-1.4.1-py3-none-any.whl.metadata (3.9 kB)
Collecting pdbp>=1.8.2 (from seleniumbase<6.0.0,>=4.38.2->soccerdata)
  Using cached pdbp-1.8.2-py3-none-any.whl.metadata (7.2 kB)
Collecting idna>=3.16 (from seleniumbase<6.0.0,>=4.38.2->soccerdata)
  Using cached idna-3.16-py3-none-any.whl.metadata (6.4 kB)
Collecting charset-normalizer<4,>=3.4.7 (from seleniumbase<6.0.0,>=4.38.2->soccerdata)
  Using cached charset_normalizer-3.4.7-cp313-cp313-macosx_10_13_universal2.whl.metadata (40 kB)
Collecting urllib3<3 (from soccerdata)
  Using cached urllib3-2.7.0-py3-none-any.whl.metadata (6.9 kB)
Collecting requests~=2.34.2 (from seleniumbase<6.0.0,>=4.38.2->soccerdata)
  Using cached requests-2.34.2-py3-none-any.whl.metadata (4.8 kB)
Requirement already satisfied: sniffio==1.3.1 in /opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages (from seleniumbase<6.0.0,>=4.38.2->soccerdata) (1.3.1)
Requirement already satisfied: h11==0.16.0 in /opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages (from seleniumbase<6.0.0,>=4.38.2->soccerdata) (0.16.0)
Collecting outcome==1.3.0.post0 (from seleniumbase<6.0.0,>=4.38.2->soccerdata)
  Using cached outcome-1.3.0.post0-py2.py3-none-any.whl.metadata (2.6 kB)
Collecting trio<1,>=0.33.0 (from seleniumbase<6.0.0,>=4.38.2->soccerdata)
  Using cached trio-0.33.0-py3-none-any.whl.metadata (8.5 kB)
Collecting trio-websocket~=0.12.2 (from seleniumbase<6.0.0,>=4.38.2->soccerdata)
  Using cached trio_websocket-0.12.2-py3-none-any.whl.metadata (5.1 kB)
Requirement already satisfied: wsproto~=1.3.2 in /opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages (from seleniumbase<6.0.0,>=4.38.2->soccerdata) (1.3.2)
Collecting websocket-client~=1.9.0 (from seleniumbase<6.0.0,>=4.38.2->soccerdata)
  Using cached websocket_client-1.9.0-py3-none-any.whl.metadata (8.3 kB)
Collecting selenium==4.44.0 (from seleniumbase<6.0.0,>=4.38.2->soccerdata)
  Using cached selenium-4.44.0-py3-none-any.whl.metadata (7.4 kB)
Collecting cssselect<2,>=1.4.0 (from seleniumbase<6.0.0,>=4.38.2->soccerdata)
  Using cached cssselect-1.4.0-py3-none-any.whl.metadata (2.4 kB)
Requirement already satisfied: sortedcontainers==2.4.0 in /opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages (from seleniumbase<6.0.0,>=4.38.2->soccerdata) (2.4.0)
Collecting execnet==2.1.2 (from seleniumbase<6.0.0,>=4.38.2->soccerdata)
  Using cached execnet-2.1.2-py3-none-any.whl.metadata (2.9 kB)
Collecting iniconfig==2.3.0 (from seleniumbase<6.0.0,>=4.38.2->soccerdata)
  Using cached iniconfig-2.3.0-py3-none-any.whl.metadata (2.5 kB)
Requirement already satisfied: pluggy==1.6.0 in /opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages (from seleniumbase<6.0.0,>=4.38.2->soccerdata) (1.6.0)
Collecting pytest==9.0.3 (from seleniumbase<6.0.0,>=4.38.2->soccerdata)
  Using cached pytest-9.0.3-py3-none-any.whl.metadata (7.6 kB)
Collecting pytest-html==4.0.2 (from seleniumbase<6.0.0,>=4.38.2->soccerdata)
  Using cached pytest_html-4.0.2-py3-none-any.whl.metadata (3.9 kB)
Collecting pytest-metadata==3.1.1 (from seleniumbase<6.0.0,>=4.38.2->soccerdata)
  Using cached pytest_metadata-3.1.1-py3-none-any.whl.metadata (8.6 kB)
Collecting pytest-ordering==0.6 (from seleniumbase<6.0.0,>=4.38.2->soccerdata)
  Using cached pytest_ordering-0.6-py3-none-any.whl.metadata (1.1 kB)
Collecting pytest-rerunfailures==16.2 (from seleniumbase<6.0.0,>=4.38.2->soccerdata)
  Using cached pytest_rerunfailures-16.2-py3-none-any.whl.metadata (22 kB)
Collecting pytest-xdist==3.8.0 (from seleniumbase<6.0.0,>=4.38.2->soccerdata)
  Using cached pytest_xdist-3.8.0-py3-none-any.whl.metadata (3.0 kB)
Collecting parameterized==0.9.0 (from seleniumbase<6.0.0,>=4.38.2->soccerdata)
  Using cached parameterized-0.9.0-py2.py3-none-any.whl.metadata (18 kB)
Collecting behave==1.2.6 (from seleniumbase<6.0.0,>=4.38.2->soccerdata)
  Using cached behave-1.2.6-py2.py3-none-any.whl.metadata (6.4 kB)
Collecting soupsieve~=2.8.3 (from seleniumbase<6.0.0,>=4.38.2->soccerdata)
  Using cached soupsieve-2.8.3-py3-none-any.whl.metadata (4.6 kB)
Collecting beautifulsoup4~=4.14.3 (from seleniumbase<6.0.0,>=4.38.2->soccerdata)
  Using cached beautifulsoup4-4.14.3-py3-none-any.whl.metadata (3.8 kB)
Collecting pyotp==2.9.0 (from seleniumbase<6.0.0,>=4.38.2->soccerdata)
  Using cached pyotp-2.9.0-py3-none-any.whl.metadata (9.8 kB)
Collecting markdown-it-py>=2.2.0 (from rich<16.0.0,>=14.0.0->soccerdata)
  Using cached markdown_it_py-4.2.0-py3-none-any.whl.metadata (7.4 kB)
Requirement already satisfied: mdurl==0.1.2 in /opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages (from seleniumbase<6.0.0,>=4.38.2->soccerdata) (0.1.2)
Collecting rich<16.0.0,>=14.0.0 (from soccerdata)
  Using cached rich-15.0.0-py3-none-any.whl.metadata (18 kB)
Collecting pysocks!=1.5.7,<2.0,>=1.5.6 (from urllib3[socks]<3.0,>=2.6.3->selenium==4.44.0->seleniumbase<6.0.0,>=4.38.2->soccerdata)
  Using cached PySocks-1.7.1-py3-none-any.whl.metadata (13 kB)
Collecting orjson (from wrapper-tls-requests<3.0.0,>=1.1.4->soccerdata)
  Using cached orjson-3.11.9-cp313-cp313-macosx_15_0_arm64.whl.metadata (41 kB)
Using cached soccerdata-1.9.0-py3-none-any.whl (51 kB)
Using cached html5lib-1.1-py2.py3-none-any.whl (112 kB)
Using cached seleniumbase-4.49.2-py3-none-any.whl (666 kB)
Using cached behave-1.2.6-py2.py3-none-any.whl (136 kB)
Using cached execnet-2.1.2-py3-none-any.whl (40 kB)
Using cached iniconfig-2.3.0-py3-none-any.whl (7.5 kB)
Using cached markdown_it_py-4.2.0-py3-none-any.whl (91 kB)
Using cached outcome-1.3.0.post0-py2.py3-none-any.whl (10 kB)
Using cached parameterized-0.9.0-py2.py3-none-any.whl (20 kB)
Using cached pyotp-2.9.0-py3-none-any.whl (13 kB)
Using cached pytest-9.0.3-py3-none-any.whl (375 kB)
Using cached pytest_html-4.0.2-py3-none-any.whl (23 kB)
Using cached pytest_metadata-3.1.1-py3-none-any.whl (11 kB)
Using cached pytest_ordering-0.6-py3-none-any.whl (4.6 kB)
Using cached pytest_rerunfailures-16.2-py3-none-any.whl (14 kB)
Using cached pytest_xdist-3.8.0-py3-none-any.whl (46 kB)
Using cached selenium-4.44.0-py3-none-any.whl (9.7 MB)
Using cached beautifulsoup4-4.14.3-py3-none-any.whl (107 kB)
Using cached charset_normalizer-3.4.7-cp313-cp313-macosx_10_13_universal2.whl (309 kB)
Using cached cssselect-1.4.0-py3-none-any.whl (18 kB)
Using cached requests-2.34.2-py3-none-any.whl (73 kB)
Using cached idna-3.16-py3-none-any.whl (74 kB)
Using cached rich-15.0.0-py3-none-any.whl (310 kB)
Using cached pygments-2.20.0-py3-none-any.whl (1.2 MB)
Using cached soupsieve-2.8.3-py3-none-any.whl (37 kB)
Using cached trio-0.33.0-py3-none-any.whl (510 kB)
Using cached trio_websocket-0.12.2-py3-none-any.whl (21 kB)
Using cached Unidecode-1.4.0-py3-none-any.whl (235 kB)
Using cached urllib3-2.7.0-py3-none-any.whl (131 kB)
Using cached PySocks-1.7.1-py3-none-any.whl (16 kB)
Using cached websocket_client-1.9.0-py3-none-any.whl (82 kB)
Using cached wrapper_tls_requests-1.2.5-py3-none-any.whl (57 kB)
Using cached attrs-26.1.0-py3-none-any.whl (67 kB)
Using cached certifi-2026.5.20-py3-none-any.whl (134 kB)
Using cached colorama-0.4.6-py2.py3-none-any.whl (25 kB)
Using cached exceptiongroup-1.3.1-py3-none-any.whl (16 kB)
Using cached fasteners-0.20-py3-none-any.whl (18 kB)
Using cached filelock-3.29.0-py3-none-any.whl (39 kB)
Using cached lxml-6.1.1-cp313-cp313-macosx_10_13_universal2.whl (8.6 MB)
Using cached markupsafe-3.0.3-cp313-cp313-macosx_11_0_arm64.whl (12 kB)
Using cached mycdp-1.3.7-py3-none-any.whl (252 kB)
Using cached packaging-26.2-py3-none-any.whl (100 kB)
Using cached parse_type-0.6.6-py2.py3-none-any.whl (27 kB)
Using cached pdbp-1.8.2-py3-none-any.whl (21 kB)
Using cached pip-26.1.1-py3-none-any.whl (1.8 MB)
Using cached platformdirs-4.9.6-py3-none-any.whl (21 kB)
Using cached psutil-7.2.2-cp36-abi3-macosx_11_0_arm64.whl (129 kB)
Using cached pynose-1.5.5-py3-none-any.whl (130 kB)
Using cached pyyaml-6.0.3-cp313-cp313-macosx_11_0_arm64.whl (173 kB)
Using cached sbvirtualdisplay-1.4.0-py3-none-any.whl (12 kB)
Using cached setuptools-82.0.1-py3-none-any.whl (1.0 MB)
Using cached tabcompleter-1.4.1-py3-none-any.whl (6.9 kB)
Using cached wheel-0.47.0-py3-none-any.whl (32 kB)
Using cached orjson-3.11.9-cp313-cp313-macosx_15_0_arm64.whl (128 kB)
Installing collected packages: websocket-client, urllib3, unidecode, tabcompleter, soupsieve, setuptools, sbvirtualdisplay, pyyaml, pysocks, pyotp, pynose, pygments, psutil, platformdirs, pip, parse-type, parameterized, packaging, orjson, mycdp, MarkupSafe, markdown-it-py, lxml, iniconfig, idna, html5lib, filelock, fasteners, execnet, exceptiongroup, cssselect, colorama, charset-normalizer, certifi, attrs, wrapper-tls-requests, wheel, rich, requests, pytest, pdbp, outcome, behave, beautifulsoup4, trio, pytest-xdist, pytest-rerunfailures, pytest-ordering, pytest-metadata, trio-websocket, pytest-html, selenium, seleniumbase, soccerdata
  Attempting uninstall: websocket-client
    Found existing installation: websocket-client 1.8.0
error: uninstall-no-record-file

× Cannot uninstall websocket-client 1.8.0
╰─> The package's contents are unknown: no RECORD file was found for websocket-client.

hint: The package was installed by brew. You should check if it can uninstall the package.
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  0/54 [websocket-client]
Note: you may need to restart the kernel to use updated packages.

In [11]:
import soccerdata as sd

In [4]:
import sys
!{sys.executable} -m pip install --ignore-installed --no-deps soccerdata

Collecting soccerdata
  Using cached soccerdata-1.9.0-py3-none-any.whl.metadata (5.3 kB)
Using cached soccerdata-1.9.0-py3-none-any.whl (51 kB)
Installing collected packages: soccerdata
Successfully installed soccerdata-1.9.0

In [5]:
import sys
!{sys.executable} -m pip install --ignore-installed Unidecode

Collecting Unidecode
  Using cached Unidecode-1.4.0-py3-none-any.whl.metadata (13 kB)
Using cached Unidecode-1.4.0-py3-none-any.whl (235 kB)
Installing collected packages: Unidecode
Successfully installed Unidecode-1.4.0

In [4]:
import sys

!{sys.executable} -m pip install --ignore-installed html5lib
!{sys.executable} -m pip install --ignore-installed lxml
!{sys.executable} -m pip install --ignore-installed wrapper-tls-requests
!{sys.executable} -m pip install --ignore-installed seleniumbase

Collecting html5lib
  Using cached html5lib-1.1-py2.py3-none-any.whl.metadata (16 kB)
Collecting six>=1.9 (from html5lib)
  Using cached six-1.17.0-py2.py3-none-any.whl.metadata (1.7 kB)
Collecting webencodings (from html5lib)
  Using cached webencodings-0.5.1-py2.py3-none-any.whl.metadata (2.1 kB)
Using cached html5lib-1.1-py2.py3-none-any.whl (112 kB)
Using cached six-1.17.0-py2.py3-none-any.whl (11 kB)
Using cached webencodings-0.5.1-py2.py3-none-any.whl (11 kB)
Installing collected packages: webencodings, six, html5lib
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3/3 [html5lib]
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
seleniumbase 4.49.2 requires attrs>=26.1.0, but you have attrs 25.3.0 which is incompatible.
seleniumbase 4.49.2 requires beautifulsoup4~=4.14.3, but you have beautifulsoup4 4.13.5 which is incompatible.
seleniumbase 4.49.2 requires charset-normalizer<4,>=3.4.7, but you have charset-normalizer 3.4.3 which is incompatible.
seleniumbase 4.49.2 requires idna>=3.16, but you have idna 3.10 which is incompatible.
seleniumbase 4.49.2 requires markdown-it-py==4.2.0; python_version >= "3.10", but you have markdown-it-py 4.0.0 which is incompatible.
seleniumbase 4.49.2 requires platformdirs>=4.9.6; python_version >= "3.10", but you have platformdirs 4.4.0 which is incompatible.
seleniumbase 4.49.2 requires psutil>=7.2.2, but you have psutil 7.0.0 which is incompatible.
seleniumbase 4.49.2 requires requests~=2.34.2; python_version >= "3.10", but you have requests 2.32.5 which is incompatible.
seleniumbase 4.49.2 requires urllib3<3,>=2.7.0; python_version >= "3.10", but you have urllib3 2.5.0 which is incompatible.
Successfully installed html5lib-1.1 six-1.17.0 webencodings-0.5.1
Collecting lxml
  Using cached lxml-6.1.1-cp313-cp313-macosx_10_13_universal2.whl.metadata (3.5 kB)
Using cached lxml-6.1.1-cp313-cp313-macosx_10_13_universal2.whl (8.6 MB)
Installing collected packages: lxml
Successfully installed lxml-6.1.1
Collecting wrapper-tls-requests
  Using cached wrapper_tls_requests-1.2.5-py3-none-any.whl.metadata (8.6 kB)
Collecting charset-normalizer (from wrapper-tls-requests)
  Using cached charset_normalizer-3.4.7-cp313-cp313-macosx_10_13_universal2.whl.metadata (40 kB)
Collecting idna~=3.10 (from wrapper-tls-requests)
  Using cached idna-3.16-py3-none-any.whl.metadata (6.4 kB)
Collecting orjson (from wrapper-tls-requests)
  Using cached orjson-3.11.9-cp313-cp313-macosx_15_0_arm64.whl.metadata (41 kB)
Using cached wrapper_tls_requests-1.2.5-py3-none-any.whl (57 kB)
Using cached idna-3.16-py3-none-any.whl (74 kB)
Using cached charset_normalizer-3.4.7-cp313-cp313-macosx_10_13_universal2.whl (309 kB)
Using cached orjson-3.11.9-cp313-cp313-macosx_15_0_arm64.whl (128 kB)
Installing collected packages: orjson, idna, charset-normalizer, wrapper-tls-requests
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4/4 [wrapper-tls-requests]
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
seleniumbase 4.49.2 requires attrs>=26.1.0, but you have attrs 25.3.0 which is incompatible.
seleniumbase 4.49.2 requires beautifulsoup4~=4.14.3, but you have beautifulsoup4 4.13.5 which is incompatible.
seleniumbase 4.49.2 requires markdown-it-py==4.2.0; python_version >= "3.10", but you have markdown-it-py 4.0.0 which is incompatible.
seleniumbase 4.49.2 requires platformdirs>=4.9.6; python_version >= "3.10", but you have platformdirs 4.4.0 which is incompatible.
seleniumbase 4.49.2 requires psutil>=7.2.2, but you have psutil 7.0.0 which is incompatible.
seleniumbase 4.49.2 requires requests~=2.34.2; python_version >= "3.10", but you have requests 2.32.5 which is incompatible.
seleniumbase 4.49.2 requires urllib3<3,>=2.7.0; python_version >= "3.10", but you have urllib3 2.5.0 which is incompatible.
Successfully installed charset-normalizer-3.4.3 idna-3.10 orjson-3.11.9 wrapper-tls-requests-1.2.5
Collecting seleniumbase
  Using cached seleniumbase-4.49.2-py3-none-any.whl.metadata (91 kB)
Collecting pip>=26.1.1 (from seleniumbase)
  Using cached pip-26.1.1-py3-none-any.whl.metadata (4.6 kB)
Collecting packaging>=26.2 (from seleniumbase)
  Using cached packaging-26.2-py3-none-any.whl.metadata (3.5 kB)
Collecting setuptools>=82.0.1 (from seleniumbase)
  Using cached setuptools-82.0.1-py3-none-any.whl.metadata (6.5 kB)
Collecting wheel>=0.47.0 (from seleniumbase)
  Using cached wheel-0.47.0-py3-none-any.whl.metadata (2.3 kB)
Collecting attrs>=26.1.0 (from seleniumbase)
  Using cached attrs-26.1.0-py3-none-any.whl.metadata (8.8 kB)
Collecting certifi>=2026.5.20 (from seleniumbase)
  Using cached certifi-2026.5.20-py3-none-any.whl.metadata (2.5 kB)
Collecting exceptiongroup>=1.3.1 (from seleniumbase)
  Using cached exceptiongroup-1.3.1-py3-none-any.whl.metadata (6.7 kB)
Collecting websockets>=16.0 (from seleniumbase)
  Using cached websockets-16.0-cp313-cp313-macosx_11_0_arm64.whl.metadata (6.8 kB)
Collecting filelock>=3.29.0 (from seleniumbase)
  Using cached filelock-3.29.0-py3-none-any.whl.metadata (2.0 kB)
Collecting fasteners>=0.20 (from seleniumbase)
  Using cached fasteners-0.20-py3-none-any.whl.metadata (4.8 kB)
Collecting mycdp>=1.3.7 (from seleniumbase)
  Using cached mycdp-1.3.7-py3-none-any.whl.metadata (3.7 kB)
Collecting pynose>=1.5.5 (from seleniumbase)
  Using cached pynose-1.5.5-py3-none-any.whl.metadata (19 kB)
Collecting platformdirs>=4.9.6 (from seleniumbase)
  Using cached platformdirs-4.9.6-py3-none-any.whl.metadata (4.7 kB)
Collecting typing-extensions>=4.15.0 (from seleniumbase)
  Using cached typing_extensions-4.15.0-py3-none-any.whl.metadata (3.3 kB)
Collecting sbvirtualdisplay>=1.4.0 (from seleniumbase)
  Using cached sbvirtualdisplay-1.4.0-py3-none-any.whl.metadata (4.3 kB)
Collecting MarkupSafe>=3.0.3 (from seleniumbase)
  Using cached markupsafe-3.0.3-cp313-cp313-macosx_11_0_arm64.whl.metadata (2.7 kB)
Collecting Jinja2>=3.1.6 (from seleniumbase)
  Using cached jinja2-3.1.6-py3-none-any.whl.metadata (2.9 kB)
Collecting six>=1.17.0 (from seleniumbase)
  Using cached six-1.17.0-py2.py3-none-any.whl.metadata (1.7 kB)
Collecting parse>=1.22.0 (from seleniumbase)
  Downloading parse-1.22.1-py2.py3-none-any.whl.metadata (21 kB)
Collecting parse-type>=0.6.6 (from seleniumbase)
  Using cached parse_type-0.6.6-py2.py3-none-any.whl.metadata (12 kB)
Collecting colorama>=0.4.6 (from seleniumbase)
  Using cached colorama-0.4.6-py2.py3-none-any.whl.metadata (17 kB)
Collecting psutil>=7.2.2 (from seleniumbase)
  Using cached psutil-7.2.2-cp36-abi3-macosx_11_0_arm64.whl.metadata (22 kB)
Collecting pyyaml>=6.0.3 (from seleniumbase)
  Using cached pyyaml-6.0.3-cp313-cp313-macosx_11_0_arm64.whl.metadata (2.4 kB)
Collecting pygments>=2.20.0 (from seleniumbase)
  Using cached pygments-2.20.0-py3-none-any.whl.metadata (2.5 kB)
Collecting tabcompleter>=1.4.1 (from seleniumbase)
  Using cached tabcompleter-1.4.1-py3-none-any.whl.metadata (3.9 kB)
Collecting pdbp>=1.8.2 (from seleniumbase)
  Using cached pdbp-1.8.2-py3-none-any.whl.metadata (7.2 kB)
Collecting idna>=3.16 (from seleniumbase)
  Using cached idna-3.16-py3-none-any.whl.metadata (6.4 kB)
Collecting charset-normalizer<4,>=3.4.7 (from seleniumbase)
  Using cached charset_normalizer-3.4.7-cp313-cp313-macosx_10_13_universal2.whl.metadata (40 kB)
Collecting urllib3<3,>=2.7.0 (from seleniumbase)
  Using cached urllib3-2.7.0-py3-none-any.whl.metadata (6.9 kB)
Collecting requests~=2.34.2 (from seleniumbase)
  Using cached requests-2.34.2-py3-none-any.whl.metadata (4.8 kB)
Collecting sniffio==1.3.1 (from seleniumbase)
  Using cached sniffio-1.3.1-py3-none-any.whl.metadata (3.9 kB)
Collecting h11==0.16.0 (from seleniumbase)
  Using cached h11-0.16.0-py3-none-any.whl.metadata (8.3 kB)
Collecting outcome==1.3.0.post0 (from seleniumbase)
  Using cached outcome-1.3.0.post0-py2.py3-none-any.whl.metadata (2.6 kB)
Collecting trio<1,>=0.33.0 (from seleniumbase)
  Using cached trio-0.33.0-py3-none-any.whl.metadata (8.5 kB)
Collecting trio-websocket~=0.12.2 (from seleniumbase)
  Using cached trio_websocket-0.12.2-py3-none-any.whl.metadata (5.1 kB)
Collecting wsproto~=1.3.2 (from seleniumbase)
  Using cached wsproto-1.3.2-py3-none-any.whl.metadata (5.2 kB)
Collecting websocket-client~=1.9.0 (from seleniumbase)
  Using cached websocket_client-1.9.0-py3-none-any.whl.metadata (8.3 kB)
Collecting selenium==4.44.0 (from seleniumbase)
  Using cached selenium-4.44.0-py3-none-any.whl.metadata (7.4 kB)
Collecting cssselect<2,>=1.4.0 (from seleniumbase)
  Using cached cssselect-1.4.0-py3-none-any.whl.metadata (2.4 kB)
Collecting sortedcontainers==2.4.0 (from seleniumbase)
  Using cached sortedcontainers-2.4.0-py2.py3-none-any.whl.metadata (10 kB)
Collecting execnet==2.1.2 (from seleniumbase)
  Using cached execnet-2.1.2-py3-none-any.whl.metadata (2.9 kB)
Collecting iniconfig==2.3.0 (from seleniumbase)
  Using cached iniconfig-2.3.0-py3-none-any.whl.metadata (2.5 kB)
Collecting pluggy==1.6.0 (from seleniumbase)
  Using cached pluggy-1.6.0-py3-none-any.whl.metadata (4.8 kB)
Collecting pytest==9.0.3 (from seleniumbase)
  Using cached pytest-9.0.3-py3-none-any.whl.metadata (7.6 kB)
Collecting pytest-html==4.0.2 (from seleniumbase)
  Using cached pytest_html-4.0.2-py3-none-any.whl.metadata (3.9 kB)
Collecting pytest-metadata==3.1.1 (from seleniumbase)
  Using cached pytest_metadata-3.1.1-py3-none-any.whl.metadata (8.6 kB)
Collecting pytest-ordering==0.6 (from seleniumbase)
  Using cached pytest_ordering-0.6-py3-none-any.whl.metadata (1.1 kB)
Collecting pytest-rerunfailures==16.2 (from seleniumbase)
  Using cached pytest_rerunfailures-16.2-py3-none-any.whl.metadata (22 kB)
Collecting pytest-xdist==3.8.0 (from seleniumbase)
  Using cached pytest_xdist-3.8.0-py3-none-any.whl.metadata (3.0 kB)
Collecting parameterized==0.9.0 (from seleniumbase)
  Using cached parameterized-0.9.0-py2.py3-none-any.whl.metadata (18 kB)
Collecting behave==1.2.6 (from seleniumbase)
  Using cached behave-1.2.6-py2.py3-none-any.whl.metadata (6.4 kB)
Collecting soupsieve~=2.8.3 (from seleniumbase)
  Downloading soupsieve-2.8.4-py3-none-any.whl.metadata (4.6 kB)
Collecting beautifulsoup4~=4.14.3 (from seleniumbase)
  Using cached beautifulsoup4-4.14.3-py3-none-any.whl.metadata (3.8 kB)
Collecting pyotp==2.9.0 (from seleniumbase)
  Using cached pyotp-2.9.0-py3-none-any.whl.metadata (9.8 kB)
Collecting markdown-it-py==4.2.0 (from seleniumbase)
  Using cached markdown_it_py-4.2.0-py3-none-any.whl.metadata (7.4 kB)
Collecting mdurl==0.1.2 (from seleniumbase)
  Using cached mdurl-0.1.2-py3-none-any.whl.metadata (1.6 kB)
Collecting rich<16,>=15.0.0 (from seleniumbase)
  Using cached rich-15.0.0-py3-none-any.whl.metadata (18 kB)
Collecting pysocks!=1.5.7,<2.0,>=1.5.6 (from urllib3[socks]<3.0,>=2.6.3->selenium==4.44.0->seleniumbase)
  Using cached PySocks-1.7.1-py3-none-any.whl.metadata (13 kB)
Using cached seleniumbase-4.49.2-py3-none-any.whl (666 kB)
Using cached behave-1.2.6-py2.py3-none-any.whl (136 kB)
Using cached execnet-2.1.2-py3-none-any.whl (40 kB)
Using cached h11-0.16.0-py3-none-any.whl (37 kB)
Using cached iniconfig-2.3.0-py3-none-any.whl (7.5 kB)
Using cached markdown_it_py-4.2.0-py3-none-any.whl (91 kB)
Using cached mdurl-0.1.2-py3-none-any.whl (10.0 kB)
Using cached outcome-1.3.0.post0-py2.py3-none-any.whl (10 kB)
Using cached parameterized-0.9.0-py2.py3-none-any.whl (20 kB)
Using cached pluggy-1.6.0-py3-none-any.whl (20 kB)
Using cached pyotp-2.9.0-py3-none-any.whl (13 kB)
Using cached pytest-9.0.3-py3-none-any.whl (375 kB)
Using cached pytest_html-4.0.2-py3-none-any.whl (23 kB)
Using cached pytest_metadata-3.1.1-py3-none-any.whl (11 kB)
Using cached pytest_ordering-0.6-py3-none-any.whl (4.6 kB)
Using cached pytest_rerunfailures-16.2-py3-none-any.whl (14 kB)
Using cached pytest_xdist-3.8.0-py3-none-any.whl (46 kB)
Using cached selenium-4.44.0-py3-none-any.whl (9.7 MB)
Using cached sniffio-1.3.1-py3-none-any.whl (10 kB)
Using cached sortedcontainers-2.4.0-py2.py3-none-any.whl (29 kB)
Using cached beautifulsoup4-4.14.3-py3-none-any.whl (107 kB)
Using cached charset_normalizer-3.4.7-cp313-cp313-macosx_10_13_universal2.whl (309 kB)
Using cached cssselect-1.4.0-py3-none-any.whl (18 kB)
Using cached requests-2.34.2-py3-none-any.whl (73 kB)
Using cached idna-3.16-py3-none-any.whl (74 kB)
Using cached rich-15.0.0-py3-none-any.whl (310 kB)
Using cached pygments-2.20.0-py3-none-any.whl (1.2 MB)
Downloading soupsieve-2.8.4-py3-none-any.whl (37 kB)
Using cached trio-0.33.0-py3-none-any.whl (510 kB)
Using cached trio_websocket-0.12.2-py3-none-any.whl (21 kB)
Using cached typing_extensions-4.15.0-py3-none-any.whl (44 kB)
Using cached urllib3-2.7.0-py3-none-any.whl (131 kB)
Using cached PySocks-1.7.1-py3-none-any.whl (16 kB)
Using cached websocket_client-1.9.0-py3-none-any.whl (82 kB)
Using cached wsproto-1.3.2-py3-none-any.whl (24 kB)
Using cached attrs-26.1.0-py3-none-any.whl (67 kB)
Using cached certifi-2026.5.20-py3-none-any.whl (134 kB)
Using cached colorama-0.4.6-py2.py3-none-any.whl (25 kB)
Using cached exceptiongroup-1.3.1-py3-none-any.whl (16 kB)
Using cached fasteners-0.20-py3-none-any.whl (18 kB)
Using cached filelock-3.29.0-py3-none-any.whl (39 kB)
Using cached jinja2-3.1.6-py3-none-any.whl (134 kB)
Using cached markupsafe-3.0.3-cp313-cp313-macosx_11_0_arm64.whl (12 kB)
Using cached mycdp-1.3.7-py3-none-any.whl (252 kB)
Using cached packaging-26.2-py3-none-any.whl (100 kB)
Downloading parse-1.22.1-py2.py3-none-any.whl (20 kB)
Using cached parse_type-0.6.6-py2.py3-none-any.whl (27 kB)
Using cached pdbp-1.8.2-py3-none-any.whl (21 kB)
Using cached pip-26.1.1-py3-none-any.whl (1.8 MB)
Using cached platformdirs-4.9.6-py3-none-any.whl (21 kB)
Using cached psutil-7.2.2-cp36-abi3-macosx_11_0_arm64.whl (129 kB)
Using cached pynose-1.5.5-py3-none-any.whl (130 kB)
Using cached pyyaml-6.0.3-cp313-cp313-macosx_11_0_arm64.whl (173 kB)
Using cached sbvirtualdisplay-1.4.0-py3-none-any.whl (12 kB)
Using cached setuptools-82.0.1-py3-none-any.whl (1.0 MB)
Using cached six-1.17.0-py2.py3-none-any.whl (11 kB)
Using cached tabcompleter-1.4.1-py3-none-any.whl (6.9 kB)
Using cached websockets-16.0-cp313-cp313-macosx_11_0_arm64.whl (175 kB)
Using cached wheel-0.47.0-py3-none-any.whl (32 kB)
Installing collected packages: sortedcontainers, parse, websockets, websocket-client, urllib3, typing-extensions, tabcompleter, soupsieve, sniffio, six, setuptools, sbvirtualdisplay, pyyaml, pysocks, pyotp, pynose, pygments, psutil, pluggy, platformdirs, pip, parameterized, packaging, mycdp, mdurl, MarkupSafe, iniconfig, idna, h11, filelock, fasteners, execnet, exceptiongroup, cssselect, colorama, charset-normalizer, certifi, attrs, wsproto, wheel, requests, pytest, pdbp, parse-type, outcome, markdown-it-py, Jinja2, beautifulsoup4, trio, rich, pytest-xdist, pytest-rerunfailures, pytest-ordering, pytest-metadata, behave, trio-websocket, pytest-html, selenium, seleniumbase
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 59/59 [seleniumbase]y]t]
Successfully installed Jinja2-3.1.6 MarkupSafe-3.0.3 attrs-25.3.0 beautifulsoup4-4.13.5 behave-1.2.6 certifi-2026.5.20 charset-normalizer-3.4.3 colorama-0.4.6 cssselect-1.4.0 exceptiongroup-1.3.1 execnet-2.1.2 fasteners-0.20 filelock-3.29.0 h11-0.16.0 idna-3.10 iniconfig-2.3.0 markdown-it-py-4.0.0 mdurl-0.1.2 mycdp-1.3.7 outcome-1.3.0.post0 packaging-26.2 parameterized-0.9.0 parse-1.22.0 parse-type-0.6.6 pdbp-1.8.2 pip-26.1.1 platformdirs-4.4.0 pluggy-1.6.0 psutil-7.0.0 pygments-2.20.0 pynose-1.5.5 pyotp-2.9.0 pysocks-1.7.1 pytest-9.0.3 pytest-html-4.0.2 pytest-metadata-3.1.1 pytest-ordering-0.6 pytest-rerunfailures-16.2 pytest-xdist-3.8.0 pyyaml-6.0.3 requests-2.32.5 rich-15.0.0 sbvirtualdisplay-1.4.0 selenium-4.44.0 seleniumbase-4.49.2 setuptools-82.0.1 six-1.17.0 sniffio-1.3.1 sortedcontainers-2.4.0 soupsieve-2.8.4 tabcompleter-1.4.1 trio-0.33.0 trio-websocket-0.12.2 typing-extensions-4.15.0 urllib3-2.5.0 websocket-client-1.9.0 websockets-16.0 wheel-0.47.0 wsproto-1.3.2

In [ ]:
import os
os._exit(0)

In [12]:
sd.FBref.available_leagues()

['Big 5 European Leagues Combined',
 'ENG-Premier League',
 'ESP-La Liga',
 'FRA-Ligue 1',
 'GER-Bundesliga',
 'INT-European Championship',
 "INT-Women's World Cup",
 'INT-World Cup',
 'ITA-Serie A']

In [13]:
fbref = sd.FBref(
    leagues="Big 5 European Leagues Combined",
    seasons=["2021-2022","2022-2023","2023-2024","2024-2025"],
    no_cache=True
)

fbref.read_seasons()

[05/30/26 05:44:20] INFO     Saving cached data to /Users/kachi/soccerdata/data/FBref                ]8;id=6119777;file:///opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages/soccerdata/_common.py\_common.py]8;;\:]8;id=6119778;file:///opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages/soccerdata/_common.py#250\250]8;;\

[05/30/26 05:44:33] WARNING  /opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-pack ]8;id=6119783;file:///opt/homebrew/Cellar/python@3.13/3.13.7/Frameworks/Python.framework/Versions/3.13/lib/python3.13/warnings.py\warnings.py]8;;\:]8;id=6119784;file:///opt/homebrew/Cellar/python@3.13/3.13.7/Frameworks/Python.framework/Versions/3.13/lib/python3.13/warnings.py#110\110]8;;\
                             ages/soccerdata/fbref.py:171: FutureWarning: The behavior of DataFrame
                             concatenation with empty or all-NA entries is deprecated. In a future
                             version, this will no longer exclude empty or all-NA columns when
                             determining the result dtypes. To retain the old behavior, exclude the
                             relevant entries before the concat operation.
                               pd.concat(dfs)

                                             format  \
league                          season
Big 5 European Leagues Combined 2122    round-robin
                                2223    round-robin
                                2324    round-robin
                                2425    round-robin

                                                                                      url
league                          season
Big 5 European Leagues Combined 2122    /en/comps/Big5/2021-2022/2021-2022-Big-5-Europ...
                                2223    /en/comps/Big5/2022-2023/2022-2023-Big-5-Europ...
                                2324    /en/comps/Big5/2023-2024/2023-2024-Big-5-Europ...
                                2425    /en/comps/Big5/2024-2025/2024-2025-Big-5-Europ...

In [6]:
# Player season stats

player_season_stats = fbref.read_player_season_stats(stat_type="standard")
player_season_stats.head()

[05/29/26 17:15:46] ERROR    Error while scraping https://fbref.com/en/comps/. Retrying in 0         ]8;id=6119741;file:///opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages/soccerdata/_common.py\_common.py]8;;\:]8;id=6119742;file:///opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages/soccerdata/_common.py#623\623]8;;\
                             seconds... (attempt 1 of 5).
                             Traceback (most recent call last):
                               File
                             "/opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-pack
                             ages/urllib3/connection.py", line 204, in _new_conn
                                 sock = connection.create_connection(
                                     (self._dns_host, self.port),
                                 ...<2 lines>...
                                     socket_options=self.socket_options,
                                 )
                               File
                             "/opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-pack
                             ages/urllib3/util/connection.py", line 85, in create_connection
                                 raise err
                               File
                             "/opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-pack
                             ages/urllib3/util/connection.py", line 73, in create_connection
                                 sock.connect(sa)
                                 ~~~~~~~~~~~~^^^^
                             ConnectionRefusedError: [Errno 61] Connection refused

                             The above exception was the direct cause of the following exception:

                             Traceback (most recent call last):
                               File
                             "/opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-pack
                             ages/urllib3/connectionpool.py", line 788, in urlopen
                                 response = self._make_request(
                                     conn,
                                 ...<10 lines>...
                                     **response_kw,
                                 )
                               File
                             "/opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-pack
                             ages/urllib3/connectionpool.py", line 493, in _make_request
                                 conn.request(
                                 ~~~~~~~~~~~~^
                                     method,
                                     ^^^^^^^
                                 ...<6 lines>...
                                     enforce_content_length=enforce_content_length,
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                 )
                                 ^
                               File
                             "/opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-pack
                             ages/urllib3/connection.py", line 500, in request
                                 self.endheaders()
                                 ~~~~~~~~~~~~~~~^^
                               File
                             "/opt/homebrew/Cellar/python@3.13/3.13.7/Frameworks/Python.framework/Ve
                             rsions/3.13/lib/python3.13/http/client.py", line 1333, in endheaders
                                 self._send_output(message_body, encode_chunked=encode_chunked)
                                 ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                               File
                             "/opt/homebrew/Cellar/python@3.13/3.13.7/Frameworks/Python.framework/Ve
                             rsions/3.13/lib/python3.13/http/client.py", line 1093, in _send_output
                                 self.send(msg)
                                 ~~~~~~~~~^^^^^
                               File
                             "/opt/homebrew/Cellar/python@3.13/3.13.7/Frameworks/Python.framework/Ve
                             rsions/3.13/lib/python3.13/http/client.py", line 1037, in send
                                 self.connect()
                                 ~~~~~~~~~~~~^^
                               File
                             "/opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-pack
                             ages/urllib3/connection.py", line 331, in connect
                                 self.sock = self._new_conn()
                                             ~~~~~~~~~~~~~~^^
                               File
                             "/opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-pack
                             ages/urllib3/connection.py", line 219, in _new_conn
                                 raise NewConnectionError(
                                     self, f"Failed to establish a new connection: {e}"
                                 ) from e
                             urllib3.exceptions.NewConnectionError: HTTPConnection(host='localhost',
                             port=53655): Failed to establish a new connection: [Errno 61]
                             Connection refused

                             The above exception was the direct cause of the following exception:

                             Traceback (most recent call last):
                               File
                             "/opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-pack
                             ages/soccerdata/_common.py", line 603, in _download_and_save
                                 self._driver.get(url)
                                 ~~~~~~~~~~~~~~~~^^^^^
                               File
                             "/opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-pack
                             ages/seleniumbase/core/browser_launcher.py", line 5945, in <lambda>
                                 driver.get = lambda url: uc_special_open_if_cf(
                                                          ~~~~~~~~~~~~~~~~~~~~~^
                                     driver,
                                     ^^^^^^^
                                 ...<5 lines>...
                                     device_pixel_ratio,
                                     ^^^^^^^^^^^^^^^^^^^
                                 )
                                 ^
                               File
                             "/opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-pack
                             ages/seleniumbase/core/browser_launcher.py", line 516, in
                             uc_special_open_if_cf
                                 driver.execute_script('window.open("%s","_blank");' % url)
                                 ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                               File
                             "/opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-pack
                             ages/selenium/webdriver/remote/webdriver.py", line 578, in
                             execute_script
                                 return self.execute(command, {"script": script, "args":
                             converted_args})["value"]
                                        ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                             ^^^^^
                               File
                             "/opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-pack
                             ages/selenium/webdriver/remote/webdriver.py", line 465, in execute
                                 response = cast(RemoteConnection,
                             self.command_executor).execute(driver_command, params)
                               File
                             "/opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-pack
                             ages/selenium/webdriver/remote/remote_connection.py", line 407, in
                             execute
                                 return self._request(command_info[0], url, body=data)
                                        ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                               File
                             "/opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-pack
                             ages/selenium/webdriver/remote/remote_connection.py", line 431, in
                             _request
                                 response = self._conn.request(method, url, body=body,
                             headers=headers, timeout=self._client_config.timeout)
                               File
                             "/opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-pack
                             ages/urllib3/_request_methods.py", line 143, in request
                                 return self.request_encode_body(
                                        ~~~~~~~~~~~~~~~~~~~~~~~~^
                                     method, url, fields=fields, headers=headers, **urlopen_kw
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                 )
                                 ^
                               File
                             "/opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-pack
                             ages/urllib3/_request_methods.py", line 278, in request_encode_body
                                 return self.urlopen(method, url, **extra_kw)
                                        ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
                               File
                             "/opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-pack
                             ages/urllib3/poolmanager.py", line 457, in urlopen
                                 response = conn.urlopen(method, u.request_uri, **kw)
                               File
                             "/opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-pack
                             ages/urllib3/connectionpool.py", line 872, in urlopen
                                 return self.urlopen(
                                        ~~~~~~~~~~~~^
                                     method,
                                     ^^^^^^^
                                 ...<13 lines>...
                                     **response_kw,
                                     ^^^^^^^^^^^^^^
                                 )
                                 ^
                               File
                             "/opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-pack
                             ages/urllib3/connectionpool.py", line 872, in urlopen
                                 return self.urlopen(
                                        ~~~~~~~~~~~~^
                                     method,
                                     ^^^^^^^
                                 ...<13 lines>...
                                     **response_kw,
                                     ^^^^^^^^^^^^^^
                                 )
                                 ^
                               File
                             "/opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-pack
                             ages/urllib3/connectionpool.py", line 872, in urlopen
                                 return self.urlopen(
                                        ~~~~~~~~~~~~^
                                     method,
                                     ^^^^^^^
                                 ...<13 lines>...
                                     **response_kw,
                                     ^^^^^^^^^^^^^^
                                 )
                                 ^
                               File
                             "/opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-pack
                             ages/urllib3/connectionpool.py", line 842, in urlopen
                                 retries = retries.increment(
                                     method, url, error=new_e, _pool=self,
                             _stacktrace=sys.exc_info()[2]
                                 )
                               File
                             "/opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-pack
                             ages/urllib3/util/retry.py", line 543, in increment
                                 raise MaxRetryError(_pool, url, reason) from reason  # type: ignore
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                             urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost',
                             port=53655): Max retries exceeded with url:
                             /session/a56be213633a6e0a0f5cfa31ab3b3a05/execute/sync (Caused by
                             NewConnectionError("HTTPConnection(host='localhost', port=53655):
                             Failed to establish a new connection: [Errno 61] Connection refused"))

[05/29/26 17:16:00] WARNING  /opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-pack ]8;id=6119747;file:///opt/homebrew/Cellar/python@3.13/3.13.7/Frameworks/Python.framework/Versions/3.13/lib/python3.13/warnings.py\warnings.py]8;;\:]8;id=6119748;file:///opt/homebrew/Cellar/python@3.13/3.13.7/Frameworks/Python.framework/Versions/3.13/lib/python3.13/warnings.py#110\110]8;;\
                             ages/soccerdata/fbref.py:171: FutureWarning: The behavior of DataFrame
                             concatenation with empty or all-NA entries is deprecated. In a future
                             version, this will no longer exclude empty or all-NA columns when
                             determining the result dtypes. To retain the old behavior, exclude the
                             relevant entries before the concat operation.
                               pd.concat(dfs)

[05/29/26 17:16:03] ERROR    Error while scraping                                                    ]8;id=6119753;file:///opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages/soccerdata/_common.py\_common.py]8;;\:]8;id=6119754;file:///opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages/soccerdata/_common.py#623\623]8;;\
                             https://fbref.com/en/comps/Big5/history/Big-5-European-Leagues-Seasons.
                             Retrying in 0 seconds... (attempt 1 of 5).
                             Traceback (most recent call last):
                               File
                             "/opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-pack
                             ages/soccerdata/_common.py", line 603, in _download_and_save
                                 self._driver.get(url)
                                 ~~~~~~~~~~~~~~~~^^^^^
                               File
                             "/opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-pack
                             ages/seleniumbase/core/browser_launcher.py", line 5945, in <lambda>
                                 driver.get = lambda url: uc_special_open_if_cf(
                                                          ~~~~~~~~~~~~~~~~~~~~~^
                                     driver,
                                     ^^^^^^^
                                 ...<5 lines>...
                                     device_pixel_ratio,
                                     ^^^^^^^^^^^^^^^^^^^
                                 )
                                 ^
                               File
                             "/opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-pack
                             ages/seleniumbase/core/browser_launcher.py", line 549, in
                             uc_special_open_if_cf
                                 page_actions.switch_to_window(
                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
                                     driver, driver.window_handles[-1], 2
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                 )
                                 ^
                               File
                             "/opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-pack
                             ages/seleniumbase/fixtures/page_actions.py", line 1709, in
                             switch_to_window
                                 __switch_to_window(driver, window_handle, uc_lock=uc_lock)
                                 ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                               File
                             "/opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-pack
                             ages/seleniumbase/fixtures/page_actions.py", line 1651, in
                             __switch_to_window
                                 with gui_lock:
                                      ^^^^^^^^
                               File
                             "/opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-pack
                             ages/filelock/_api.py", line 554, in __enter__
                                 self.acquire()
                                 ~~~~~~~~~~~~^^
                               File
                             "/opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-pack
                             ages/filelock/_api.py", line 502, in acquire
                                 self._acquire()
                                 ~~~~~~~~~~~~~^^
                               File
                             "/opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-pack
                             ages/filelock/_unix.py", line 55, in _acquire
                                 fd = os.open(self.lock_file, open_flags, open_mode)
                             OSError: [Errno 28] No space left on device:
                             'downloaded_files/pyautogui.lock'

[05/29/26 17:16:29] ERROR    Error while scraping                                                    ]8;id=6119759;file:///opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages/soccerdata/_common.py\_common.py]8;;\:]8;id=6119760;file:///opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages/soccerdata/_common.py#623\623]8;;\
                             https://fbref.com/en/comps/Big5/2022-2023/stats/players/2022-2023-Big-5
                             -European-Leagues-Stats. Retrying in 0 seconds... (attempt 1 of 5).
                             Traceback (most recent call last):
                               File
                             "/opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-pack
                             ages/soccerdata/_common.py", line 603, in _download_and_save
                                 self._driver.get(url)
                                 ~~~~~~~~~~~~~~~~^^^^^
                               File
                             "/opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-pack
                             ages/seleniumbase/core/browser_launcher.py", line 5945, in <lambda>
                                 driver.get = lambda url: uc_special_open_if_cf(
                                                          ~~~~~~~~~~~~~~~~~~~~~^
                                     driver,
                                     ^^^^^^^
                                 ...<5 lines>...
                                     device_pixel_ratio,
                                     ^^^^^^^^^^^^^^^^^^^
                                 )
                                 ^
                               File
                             "/opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-pack
                             ages/seleniumbase/core/browser_launcher.py", line 549, in
                             uc_special_open_if_cf
                                 page_actions.switch_to_window(
                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
                                     driver, driver.window_handles[-1], 2
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                 )
                                 ^
                               File
                             "/opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-pack
                             ages/seleniumbase/fixtures/page_actions.py", line 1709, in
                             switch_to_window
                                 __switch_to_window(driver, window_handle, uc_lock=uc_lock)
                                 ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                               File
                             "/opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-pack
                             ages/seleniumbase/fixtures/page_actions.py", line 1651, in
                             __switch_to_window
                                 with gui_lock:
                                      ^^^^^^^^
                               File
                             "/opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-pack
                             ages/filelock/_api.py", line 554, in __enter__
                                 self.acquire()
                                 ~~~~~~~~~~~~^^
                               File
                             "/opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-pack
                             ages/filelock/_api.py", line 502, in acquire
                                 self._acquire()
                                 ~~~~~~~~~~~~~^^
                               File
                             "/opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-pack
                             ages/filelock/_unix.py", line 55, in _acquire
                                 fd = os.open(self.lock_file, open_flags, open_mode)
                             OSError: [Errno 28] No space left on device:
                             'downloaded_files/pyautogui.lock'

--- Logging error ---
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages/soccerdata/_common.py", line 603, in _download_and_save
    self._driver.get(url)
    ~~~~~~~~~~~~~~~~^^^^^
  File "/opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages/seleniumbase/core/browser_launcher.py", line 5945, in <lambda>
    driver.get = lambda url: uc_special_open_if_cf(
                             ~~~~~~~~~~~~~~~~~~~~~^
        driver,
        ^^^^^^^
    ...<5 lines>...
        device_pixel_ratio,
        ^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages/seleniumbase/core/browser_launcher.py", line 549, in uc_special_open_if_cf
    page_actions.switch_to_window(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        driver, driver.window_handles[-1], 2
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages/seleniumbase/fixtures/page_actions.py", line 1709, in switch_to_window
    __switch_to_window(driver, window_handle, uc_lock=uc_lock)
    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages/seleniumbase/fixtures/page_actions.py", line 1651, in __switch_to_window
    with gui_lock:
         ^^^^^^^^
  File "/opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages/filelock/_api.py", line 554, in __enter__
    self.acquire()
    ~~~~~~~~~~~~^^
  File "/opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages/filelock/_api.py", line 502, in acquire
    self._acquire()
    ~~~~~~~~~~~~~^^
  File "/opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages/filelock/_unix.py", line 55, in _acquire
    fd = os.open(self.lock_file, open_flags, open_mode)
OSError: [Errno 28] No space left on device: 'downloaded_files/pyautogui.lock'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.13/3.13.7/Frameworks/Python.framework/Versions/3.13/lib/python3.13/logging/__init__.py", line 1155, in emit
    self.flush()
    ~~~~~~~~~~^^
  File "/opt/homebrew/Cellar/python@3.13/3.13.7/Frameworks/Python.framework/Versions/3.13/lib/python3.13/logging/__init__.py", line 1137, in flush
    self.stream.flush()
    ~~~~~~~~~~~~~~~~~^^
OSError: [Errno 28] No space left on device
Call stack:
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages/ipykernel_launcher.py", line 18, in <module>
    app.launch_new_instance()
  File "/opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages/traitlets/config/application.py", line 1075, in launch_instance
    app.start()
  File "/opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages/ipykernel/kernelapp.py", line 739, in start
    self.io_loop.start()
  File "/opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages/tornado/platform/asyncio.py", line 211, in start
    self.asyncio_loop.run_forever()
  File "/opt/homebrew/Cellar/python@3.13/3.13.7/Frameworks/Python.framework/Versions/3.13/lib/python3.13/asyncio/base_events.py", line 683, in run_forever
    self._run_once()
  File "/opt/homebrew/Cellar/python@3.13/3.13.7/Frameworks/Python.framework/Versions/3.13/lib/python3.13/asyncio/base_events.py", line 2050, in _run_once
    handle._run()
  File "/opt/homebrew/Cellar/python@3.13/3.13.7/Frameworks/Python.framework/Versions/3.13/lib/python3.13/asyncio/events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
  File "/opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages/ipykernel/kernelbase.py", line 519, in dispatch_queue
    await self.process_one()
  File "/opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages/ipykernel/kernelbase.py", line 508, in process_one
    await dispatch(*args)
  File "/opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages/ipykernel/kernelbase.py", line 400, in dispatch_shell
    await result
  File "/opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages/ipykernel/ipkernel.py", line 368, in execute_request
    await super().execute_request(stream, ident, parent)
  File "/opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages/ipykernel/kernelbase.py", line 767, in execute_request
    reply_content = await reply_content
  File "/opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages/ipykernel/ipkernel.py", line 455, in do_execute
    res = shell.run_cell(
  File "/opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages/ipykernel/zmqshell.py", line 577, in run_cell
    return super().run_cell(*args, **kwargs)
  File "/opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages/IPython/core/interactiveshell.py", line 3116, in run_cell
    result = self._run_cell(
  File "/opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages/IPython/core/interactiveshell.py", line 3171, in _run_cell
    result = runner(coro)
  File "/opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages/IPython/core/async_helpers.py", line 128, in _pseudo_sync_runner
    coro.send(None)
  File "/opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages/IPython/core/interactiveshell.py", line 3394, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "/opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages/IPython/core/interactiveshell.py", line 3639, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "/opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages/IPython/core/interactiveshell.py", line 3699, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/var/folders/cj/2nrsc7ds2lx8n63yblxbbhfw0000gn/T/ipykernel_11006/502862824.py", line 3, in <module>
    player_season_stats = fbref.read_player_season_stats(stat_type="standard")
  File "/opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages/soccerdata/fbref.py", line 573, in read_player_season_stats
    reader = self.get(url, filepath)
  File "/opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages/soccerdata/_common.py", line 293, in get
    return self._download_and_save(url, filepath, var)
  File "/opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages/soccerdata/_common.py", line 623, in _download_and_save
    logger.exception(
Message: 'Error while scraping %s. Retrying in %d seconds... (attempt %d of 5).'
Arguments: ('https://fbref.com/en/comps/Big5/2022-2023/stats/players/2022-2023-Big-5-European-Leagues-Stats', 0, 1)

[05/29/26 17:16:54] ERROR    Error while scraping                                                    ]8;id=6119765;file:///opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages/soccerdata/_common.py\_common.py]8;;\:]8;id=6119766;file:///opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages/soccerdata/_common.py#623\623]8;;\
                             https://fbref.com/en/comps/Big5/2023-2024/stats/players/2023-2024-Big-5
                             -European-Leagues-Stats. Retrying in 0 seconds... (attempt 1 of 5).
                             Traceback (most recent call last):
                               File
                             "/opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-pack
                             ages/soccerdata/_common.py", line 619, in _download_and_save
                                 with filepath.open(mode="wb") as fh:
                                      ~~~~~~~~~~~~~^^^^^^^^^^^
                               File
                             "/opt/homebrew/Cellar/python@3.13/3.13.7/Frameworks/Python.framework/Ve
                             rsions/3.13/lib/python3.13/pathlib/_local.py", line 537, in open
                                 return io.open(self, mode, buffering, encoding, errors, newline)
                                        ~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                             OSError: [Errno 28] No space left on device:
                             '/Users/kachi/soccerdata/data/FBref/players_Big 5 European Leagues
                             Combined_2324_standard.html'

--- Logging error ---
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages/soccerdata/_common.py", line 619, in _download_and_save
    with filepath.open(mode="wb") as fh:
         ~~~~~~~~~~~~~^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.13/3.13.7/Frameworks/Python.framework/Versions/3.13/lib/python3.13/pathlib/_local.py", line 537, in open
    return io.open(self, mode, buffering, encoding, errors, newline)
           ~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 28] No space left on device: '/Users/kachi/soccerdata/data/FBref/players_Big 5 European Leagues Combined_2324_standard.html'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.13/3.13.7/Frameworks/Python.framework/Versions/3.13/lib/python3.13/logging/handlers.py", line 79, in emit
    if self.shouldRollover(record):
       ~~~~~~~~~~~~~~~~~~~^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.13/3.13.7/Frameworks/Python.framework/Versions/3.13/lib/python3.13/logging/handlers.py", line 199, in shouldRollover
    pos = self.stream.tell()
OSError: [Errno 28] No space left on device
Call stack:
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages/ipykernel_launcher.py", line 18, in <module>
    app.launch_new_instance()
  File "/opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages/traitlets/config/application.py", line 1075, in launch_instance
    app.start()
  File "/opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages/ipykernel/kernelapp.py", line 739, in start
    self.io_loop.start()
  File "/opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages/tornado/platform/asyncio.py", line 211, in start
    self.asyncio_loop.run_forever()
  File "/opt/homebrew/Cellar/python@3.13/3.13.7/Frameworks/Python.framework/Versions/3.13/lib/python3.13/asyncio/base_events.py", line 683, in run_forever
    self._run_once()
  File "/opt/homebrew/Cellar/python@3.13/3.13.7/Frameworks/Python.framework/Versions/3.13/lib/python3.13/asyncio/base_events.py", line 2050, in _run_once
    handle._run()
  File "/opt/homebrew/Cellar/python@3.13/3.13.7/Frameworks/Python.framework/Versions/3.13/lib/python3.13/asyncio/events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
  File "/opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages/ipykernel/kernelbase.py", line 519, in dispatch_queue
    await self.process_one()
  File "/opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages/ipykernel/kernelbase.py", line 508, in process_one
    await dispatch(*args)
  File "/opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages/ipykernel/kernelbase.py", line 400, in dispatch_shell
    await result
  File "/opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages/ipykernel/ipkernel.py", line 368, in execute_request
    await super().execute_request(stream, ident, parent)
  File "/opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages/ipykernel/kernelbase.py", line 767, in execute_request
    reply_content = await reply_content
  File "/opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages/ipykernel/ipkernel.py", line 455, in do_execute
    res = shell.run_cell(
  File "/opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages/ipykernel/zmqshell.py", line 577, in run_cell
    return super().run_cell(*args, **kwargs)
  File "/opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages/IPython/core/interactiveshell.py", line 3116, in run_cell
    result = self._run_cell(
  File "/opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages/IPython/core/interactiveshell.py", line 3171, in _run_cell
    result = runner(coro)
  File "/opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages/IPython/core/async_helpers.py", line 128, in _pseudo_sync_runner
    coro.send(None)
  File "/opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages/IPython/core/interactiveshell.py", line 3394, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "/opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages/IPython/core/interactiveshell.py", line 3639, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "/opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages/IPython/core/interactiveshell.py", line 3699, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/var/folders/cj/2nrsc7ds2lx8n63yblxbbhfw0000gn/T/ipykernel_11006/502862824.py", line 3, in <module>
    player_season_stats = fbref.read_player_season_stats(stat_type="standard")
  File "/opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages/soccerdata/fbref.py", line 573, in read_player_season_stats
    reader = self.get(url, filepath)
  File "/opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages/soccerdata/_common.py", line 293, in get
    return self._download_and_save(url, filepath, var)
  File "/opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages/soccerdata/_common.py", line 623, in _download_and_save
    logger.exception(
Message: 'Error while scraping %s. Retrying in %d seconds... (attempt %d of 5).'
Arguments: ('https://fbref.com/en/comps/Big5/2023-2024/stats/players/2023-2024-Big-5-European-Leagues-Stats', 0, 1)
--- Logging error ---
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages/soccerdata/_common.py", line 619, in _download_and_save
    with filepath.open(mode="wb") as fh:
         ~~~~~~~~~~~~~^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.13/3.13.7/Frameworks/Python.framework/Versions/3.13/lib/python3.13/pathlib/_local.py", line 537, in open
    return io.open(self, mode, buffering, encoding, errors, newline)
           ~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 28] No space left on device: '/Users/kachi/soccerdata/data/FBref/players_Big 5 European Leagues Combined_2324_standard.html'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.13/3.13.7/Frameworks/Python.framework/Versions/3.13/lib/python3.13/logging/__init__.py", line 1155, in emit
    self.flush()
    ~~~~~~~~~~^^
  File "/opt/homebrew/Cellar/python@3.13/3.13.7/Frameworks/Python.framework/Versions/3.13/lib/python3.13/logging/__init__.py", line 1137, in flush
    self.stream.flush()
    ~~~~~~~~~~~~~~~~~^^
OSError: [Errno 28] No space left on device
Call stack:
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages/ipykernel_launcher.py", line 18, in <module>
    app.launch_new_instance()
  File "/opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages/traitlets/config/application.py", line 1075, in launch_instance
    app.start()
  File "/opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages/ipykernel/kernelapp.py", line 739, in start
    self.io_loop.start()
  File "/opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages/tornado/platform/asyncio.py", line 211, in start
    self.asyncio_loop.run_forever()
  File "/opt/homebrew/Cellar/python@3.13/3.13.7/Frameworks/Python.framework/Versions/3.13/lib/python3.13/asyncio/base_events.py", line 683, in run_forever
    self._run_once()
  File "/opt/homebrew/Cellar/python@3.13/3.13.7/Frameworks/Python.framework/Versions/3.13/lib/python3.13/asyncio/base_events.py", line 2050, in _run_once
    handle._run()
  File "/opt/homebrew/Cellar/python@3.13/3.13.7/Frameworks/Python.framework/Versions/3.13/lib/python3.13/asyncio/events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
  File "/opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages/ipykernel/kernelbase.py", line 519, in dispatch_queue
    await self.process_one()
  File "/opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages/ipykernel/kernelbase.py", line 508, in process_one
    await dispatch(*args)
  File "/opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages/ipykernel/kernelbase.py", line 400, in dispatch_shell
    await result
  File "/opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages/ipykernel/ipkernel.py", line 368, in execute_request
    await super().execute_request(stream, ident, parent)
  File "/opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages/ipykernel/kernelbase.py", line 767, in execute_request
    reply_content = await reply_content
  File "/opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages/ipykernel/ipkernel.py", line 455, in do_execute
    res = shell.run_cell(
  File "/opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages/ipykernel/zmqshell.py", line 577, in run_cell
    return super().run_cell(*args, **kwargs)
  File "/opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages/IPython/core/interactiveshell.py", line 3116, in run_cell
    result = self._run_cell(
  File "/opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages/IPython/core/interactiveshell.py", line 3171, in _run_cell
    result = runner(coro)
  File "/opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages/IPython/core/async_helpers.py", line 128, in _pseudo_sync_runner
    coro.send(None)
  File "/opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages/IPython/core/interactiveshell.py", line 3394, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "/opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages/IPython/core/interactiveshell.py", line 3639, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "/opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages/IPython/core/interactiveshell.py", line 3699, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/var/folders/cj/2nrsc7ds2lx8n63yblxbbhfw0000gn/T/ipykernel_11006/502862824.py", line 3, in <module>
    player_season_stats = fbref.read_player_season_stats(stat_type="standard")
  File "/opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages/soccerdata/fbref.py", line 573, in read_player_season_stats
    reader = self.get(url, filepath)
  File "/opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages/soccerdata/_common.py", line 293, in get
    return self._download_and_save(url, filepath, var)
  File "/opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages/soccerdata/_common.py", line 623, in _download_and_save
    logger.exception(
Message: 'Error while scraping %s. Retrying in %d seconds... (attempt %d of 5).'
Arguments: ('https://fbref.com/en/comps/Big5/2023-2024/stats/players/2023-2024-Big-5-European-Leagues-Stats', 0, 1)

[05/29/26 17:17:06] ERROR    Error while scraping                                                    ]8;id=6119771;file:///opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages/soccerdata/_common.py\_common.py]8;;\:]8;id=6119772;file:///opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages/soccerdata/_common.py#623\623]8;;\
                             https://fbref.com/en/comps/Big5/2023-2024/stats/players/2023-2024-Big-5
                             -European-Leagues-Stats. Retrying in 10 seconds... (attempt 2 of 5).
                             Traceback (most recent call last):
                               File
                             "/opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-pack
                             ages/soccerdata/_common.py", line 619, in _download_and_save
                                 with filepath.open(mode="wb") as fh:
                                      ~~~~~~~~~~~~~^^^^^^^^^^^
                               File
                             "/opt/homebrew/Cellar/python@3.13/3.13.7/Frameworks/Python.framework/Ve
                             rsions/3.13/lib/python3.13/pathlib/_local.py", line 537, in open
                                 return io.open(self, mode, buffering, encoding, errors, newline)
                                        ~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                             OSError: [Errno 28] No space left on device:
                             '/Users/kachi/soccerdata/data/FBref/players_Big 5 European Leagues
                             Combined_2324_standard.html'

--- Logging error ---
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages/soccerdata/_common.py", line 619, in _download_and_save
    with filepath.open(mode="wb") as fh:
         ~~~~~~~~~~~~~^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.13/3.13.7/Frameworks/Python.framework/Versions/3.13/lib/python3.13/pathlib/_local.py", line 537, in open
    return io.open(self, mode, buffering, encoding, errors, newline)
           ~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 28] No space left on device: '/Users/kachi/soccerdata/data/FBref/players_Big 5 European Leagues Combined_2324_standard.html'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.13/3.13.7/Frameworks/Python.framework/Versions/3.13/lib/python3.13/logging/handlers.py", line 79, in emit
    if self.shouldRollover(record):
       ~~~~~~~~~~~~~~~~~~~^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.13/3.13.7/Frameworks/Python.framework/Versions/3.13/lib/python3.13/logging/handlers.py", line 199, in shouldRollover
    pos = self.stream.tell()
OSError: [Errno 28] No space left on device
Call stack:
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages/ipykernel_launcher.py", line 18, in <module>
    app.launch_new_instance()
  File "/opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages/traitlets/config/application.py", line 1075, in launch_instance
    app.start()
  File "/opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages/ipykernel/kernelapp.py", line 739, in start
    self.io_loop.start()
  File "/opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages/tornado/platform/asyncio.py", line 211, in start
    self.asyncio_loop.run_forever()
  File "/opt/homebrew/Cellar/python@3.13/3.13.7/Frameworks/Python.framework/Versions/3.13/lib/python3.13/asyncio/base_events.py", line 683, in run_forever
    self._run_once()
  File "/opt/homebrew/Cellar/python@3.13/3.13.7/Frameworks/Python.framework/Versions/3.13/lib/python3.13/asyncio/base_events.py", line 2050, in _run_once
    handle._run()
  File "/opt/homebrew/Cellar/python@3.13/3.13.7/Frameworks/Python.framework/Versions/3.13/lib/python3.13/asyncio/events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
  File "/opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages/ipykernel/kernelbase.py", line 519, in dispatch_queue
    await self.process_one()
  File "/opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages/ipykernel/kernelbase.py", line 508, in process_one
    await dispatch(*args)
  File "/opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages/ipykernel/kernelbase.py", line 400, in dispatch_shell
    await result
  File "/opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages/ipykernel/ipkernel.py", line 368, in execute_request
    await super().execute_request(stream, ident, parent)
  File "/opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages/ipykernel/kernelbase.py", line 767, in execute_request
    reply_content = await reply_content
  File "/opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages/ipykernel/ipkernel.py", line 455, in do_execute
    res = shell.run_cell(
  File "/opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages/ipykernel/zmqshell.py", line 577, in run_cell
    return super().run_cell(*args, **kwargs)
  File "/opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages/IPython/core/interactiveshell.py", line 3116, in run_cell
    result = self._run_cell(
  File "/opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages/IPython/core/interactiveshell.py", line 3171, in _run_cell
    result = runner(coro)
  File "/opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages/IPython/core/async_helpers.py", line 128, in _pseudo_sync_runner
    coro.send(None)
  File "/opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages/IPython/core/interactiveshell.py", line 3394, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "/opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages/IPython/core/interactiveshell.py", line 3639, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "/opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages/IPython/core/interactiveshell.py", line 3699, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/var/folders/cj/2nrsc7ds2lx8n63yblxbbhfw0000gn/T/ipykernel_11006/502862824.py", line 3, in <module>
    player_season_stats = fbref.read_player_season_stats(stat_type="standard")
  File "/opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages/soccerdata/fbref.py", line 573, in read_player_season_stats
    reader = self.get(url, filepath)
  File "/opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages/soccerdata/_common.py", line 293, in get
    return self._download_and_save(url, filepath, var)
  File "/opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages/soccerdata/_common.py", line 623, in _download_and_save
    logger.exception(
Message: 'Error while scraping %s. Retrying in %d seconds... (attempt %d of 5).'
Arguments: ('https://fbref.com/en/comps/Big5/2023-2024/stats/players/2023-2024-Big-5-European-Leagues-Stats', 10, 2)
--- Logging error ---
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages/soccerdata/_common.py", line 619, in _download_and_save
    with filepath.open(mode="wb") as fh:
         ~~~~~~~~~~~~~^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.13/3.13.7/Frameworks/Python.framework/Versions/3.13/lib/python3.13/pathlib/_local.py", line 537, in open
    return io.open(self, mode, buffering, encoding, errors, newline)
           ~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 28] No space left on device: '/Users/kachi/soccerdata/data/FBref/players_Big 5 European Leagues Combined_2324_standard.html'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.13/3.13.7/Frameworks/Python.framework/Versions/3.13/lib/python3.13/logging/handlers.py", line 79, in emit
    if self.shouldRollover(record):
       ~~~~~~~~~~~~~~~~~~~^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.13/3.13.7/Frameworks/Python.framework/Versions/3.13/lib/python3.13/logging/handlers.py", line 199, in shouldRollover
    pos = self.stream.tell()
OSError: [Errno 28] No space left on device
Call stack:
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages/ipykernel_launcher.py", line 18, in <module>
    app.launch_new_instance()
  File "/opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages/traitlets/config/application.py", line 1075, in launch_instance
    app.start()
  File "/opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages/ipykernel/kernelapp.py", line 739, in start
    self.io_loop.start()
  File "/opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages/tornado/platform/asyncio.py", line 211, in start
    self.asyncio_loop.run_forever()
  File "/opt/homebrew/Cellar/python@3.13/3.13.7/Frameworks/Python.framework/Versions/3.13/lib/python3.13/asyncio/base_events.py", line 683, in run_forever
    self._run_once()
  File "/opt/homebrew/Cellar/python@3.13/3.13.7/Frameworks/Python.framework/Versions/3.13/lib/python3.13/asyncio/base_events.py", line 2050, in _run_once
    handle._run()
  File "/opt/homebrew/Cellar/python@3.13/3.13.7/Frameworks/Python.framework/Versions/3.13/lib/python3.13/asyncio/events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
  File "/opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages/ipykernel/kernelbase.py", line 519, in dispatch_queue
    await self.process_one()
  File "/opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages/ipykernel/kernelbase.py", line 508, in process_one
    await dispatch(*args)
  File "/opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages/ipykernel/kernelbase.py", line 400, in dispatch_shell
    await result
  File "/opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages/ipykernel/ipkernel.py", line 368, in execute_request
    await super().execute_request(stream, ident, parent)
  File "/opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages/ipykernel/kernelbase.py", line 767, in execute_request
    reply_content = await reply_content
  File "/opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages/ipykernel/ipkernel.py", line 455, in do_execute
    res = shell.run_cell(
  File "/opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages/ipykernel/zmqshell.py", line 577, in run_cell
    return super().run_cell(*args, **kwargs)
  File "/opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages/IPython/core/interactiveshell.py", line 3116, in run_cell
    result = self._run_cell(
  File "/opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages/IPython/core/interactiveshell.py", line 3171, in _run_cell
    result = runner(coro)
  File "/opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages/IPython/core/async_helpers.py", line 128, in _pseudo_sync_runner
    coro.send(None)
  File "/opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages/IPython/core/interactiveshell.py", line 3394, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "/opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages/IPython/core/interactiveshell.py", line 3639, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "/opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages/IPython/core/interactiveshell.py", line 3699, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/var/folders/cj/2nrsc7ds2lx8n63yblxbbhfw0000gn/T/ipykernel_11006/502862824.py", line 3, in <module>
    player_season_stats = fbref.read_player_season_stats(stat_type="standard")
  File "/opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages/soccerdata/fbref.py", line 573, in read_player_season_stats
    reader = self.get(url, filepath)
  File "/opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages/soccerdata/_common.py", line 293, in get
    return self._download_and_save(url, filepath, var)
  File "/opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages/soccerdata/_common.py", line 623, in _download_and_save
    logger.exception(
Message: 'Error while scraping %s. Retrying in %d seconds... (attempt %d of 5).'
Arguments: ('https://fbref.com/en/comps/Big5/2023-2024/stats/players/2023-2024-Big-5-European-Leagues-Stats', 10, 2)

OSError: [Errno 28] No space left on device: '/var/folders/cj/2nrsc7ds2lx8n63yblxbbhfw0000gn/T/tmpda0xscgj'

In [7]:
# Investigations

print(player_season_stats.index.names)

NameError: name 'player_season_stats' is not defined

In [14]:
df = player_season_stats.reset_index()
df.head()

NameError: name 'player_season_stats' is not defined

In [15]:
# print(player_season_stats.shape)

# player_season_stats.info()

# for col in player_season_stats.columns:
    # print(col)

fbref = sd.FBref(
    leagues="Big 5 European Leagues Combined",
    seasons=["24-25"],
    no_cache=True
)

standard = fbref.read_player_season_stats("standard")

print(standard.shape)
standard.head()

player_season_stats.to_csv(
   "fbref_standard_2425.csv",
   index=True
)

[05/30/26 05:46:18] INFO     Saving cached data to /Users/kachi/soccerdata/data/FBref                ]8;id=6119789;file:///opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages/soccerdata/_common.py\_common.py]8;;\:]8;id=6119790;file:///opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages/soccerdata/_common.py#250\250]8;;\

[05/30/26 05:46:30] WARNING  /opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-pack ]8;id=6119795;file:///opt/homebrew/Cellar/python@3.13/3.13.7/Frameworks/Python.framework/Versions/3.13/lib/python3.13/warnings.py\warnings.py]8;;\:]8;id=6119796;file:///opt/homebrew/Cellar/python@3.13/3.13.7/Frameworks/Python.framework/Versions/3.13/lib/python3.13/warnings.py#110\110]8;;\
                             ages/soccerdata/fbref.py:171: FutureWarning: The behavior of DataFrame
                             concatenation with empty or all-NA entries is deprecated. In a future
                             version, this will no longer exclude empty or all-NA columns when
                             determining the result dtypes. To retain the old behavior, exclude the
                             relevant entries before the concat operation.
                               pd.concat(dfs)

(2854, 21)

NameError: name 'player_season_stats' is not defined

In [10]:
player_season_stats.columns

NameError: name 'player_season_stats' is not defined

In [16]:
player_season_stats.columns = [
    '_'.join(col).strip('_')
    for col in player_season_stats.columns
]

In [17]:
shooting = fbref.read_player_season_stats("shooting")

[05/29/26 02:17:58] WARNING  /opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-pack ]8;id=327541;file:///opt/homebrew/Cellar/python@3.13/3.13.7/Frameworks/Python.framework/Versions/3.13/lib/python3.13/warnings.py\warnings.py]8;;\:]8;id=327542;file:///opt/homebrew/Cellar/python@3.13/3.13.7/Frameworks/Python.framework/Versions/3.13/lib/python3.13/warnings.py#110\110]8;;\
                             ages/soccerdata/fbref.py:171: FutureWarning: The behavior of DataFrame
                             concatenation with empty or all-NA entries is deprecated. In a future
                             version, this will no longer exclude empty or all-NA columns when
                             determining the result dtypes. To retain the old behavior, exclude the
                             relevant entries before the concat operation.
                               pd.concat(dfs)

In [16]:
playing_time = fbref.read_player_season_stats("playing_time")
misc = fbref.read_player_season_stats("misc")

[05/30/26 05:47:23] WARNING  /opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-pack ]8;id=6119801;file:///opt/homebrew/Cellar/python@3.13/3.13.7/Frameworks/Python.framework/Versions/3.13/lib/python3.13/warnings.py\warnings.py]8;;\:]8;id=6119802;file:///opt/homebrew/Cellar/python@3.13/3.13.7/Frameworks/Python.framework/Versions/3.13/lib/python3.13/warnings.py#110\110]8;;\
                             ages/soccerdata/fbref.py:171: FutureWarning: The behavior of DataFrame
                             concatenation with empty or all-NA entries is deprecated. In a future
                             version, this will no longer exclude empty or all-NA columns when
                             determining the result dtypes. To retain the old behavior, exclude the
                             relevant entries before the concat operation.
                               pd.concat(dfs)

[05/30/26 05:47:55] WARNING  /opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-pack ]8;id=6119807;file:///opt/homebrew/Cellar/python@3.13/3.13.7/Frameworks/Python.framework/Versions/3.13/lib/python3.13/warnings.py\warnings.py]8;;\:]8;id=6119808;file:///opt/homebrew/Cellar/python@3.13/3.13.7/Frameworks/Python.framework/Versions/3.13/lib/python3.13/warnings.py#110\110]8;;\
                             ages/soccerdata/fbref.py:171: FutureWarning: The behavior of DataFrame
                             concatenation with empty or all-NA entries is deprecated. In a future
                             version, this will no longer exclude empty or all-NA columns when
                             determining the result dtypes. To retain the old behavior, exclude the
                             relevant entries before the concat operation.
                               pd.concat(dfs)

In [27]:
########################################################
# Loading First Data From FBREF
########################################################

fbRef_one = pd.read_csv(
    "fbref_standard_2425.csv",
    header=[0,1]
)

fbRef_one.head()

   Unnamed: 0_level_0 Unnamed: 1_level_0 Unnamed: 2_level_0  \
   Unnamed: 0_level_1 Unnamed: 1_level_1 Unnamed: 2_level_1
0              league             season               team
1  ENG-Premier League               2122            Arsenal
2  ENG-Premier League               2122            Arsenal
3  ENG-Premier League               2122            Arsenal
4  ENG-Premier League               2122            Arsenal

       Unnamed: 3_level_0             nation                pos  \
       Unnamed: 3_level_1 Unnamed: 4_level_1 Unnamed: 5_level_1
0                  player                NaN                NaN
1          Aaron Ramsdale                ENG                 GK
2  Ainsley Maitland-Niles                ENG                 MF
3    Albert Sambi Lokonga                BEL                 MF
4     Alexandre Lacazette                FRA              FW,MF

                 age               born Playing Time         ... Performance  \
  Unnamed: 6_level_1 Unnamed: 7_level_1           MP Starts  ...        G-PK
0                NaN                NaN          NaN    NaN  ...         NaN
1               23.0             1998.0         34.0   34.0  ...         0.0
2               23.0             1997.0          8.0    2.0  ...         0.0
3               21.0             1999.0         19.0   12.0  ...         0.0
4               30.0             1991.0         30.0   20.0  ...         2.0

                       Per 90 Minutes
    PK PKatt CrdY CrdR            Gls   Ast   G+A G-PK G+A-PK
0  NaN   NaN  NaN  NaN            NaN   NaN   NaN  NaN    NaN
1  0.0   0.0  1.0  0.0            0.0  0.00  0.00  0.0   0.00
2  0.0   0.0  0.0  0.0            0.0  0.00  0.00  0.0   0.00
3  0.0   0.0  5.0  0.0            0.0  0.00  0.00  0.0   0.00
4  2.0   3.0  0.0  0.0            0.2  0.35  0.56  0.1   0.45

[5 rows x 25 columns]

In [28]:
fbRef_one.columns

MultiIndex([('Unnamed: 0_level_0', 'Unnamed: 0_level_1'),
            ('Unnamed: 1_level_0', 'Unnamed: 1_level_1'),
            ('Unnamed: 2_level_0', 'Unnamed: 2_level_1'),
            ('Unnamed: 3_level_0', 'Unnamed: 3_level_1'),
            (            'nation', 'Unnamed: 4_level_1'),
            (               'pos', 'Unnamed: 5_level_1'),
            (               'age', 'Unnamed: 6_level_1'),
            (              'born', 'Unnamed: 7_level_1'),
            (      'Playing Time',                 'MP'),
            (      'Playing Time',             'Starts'),
            (      'Playing Time',                'Min'),
            (      'Playing Time',                '90s'),
            (       'Performance',                'Gls'),
            (       'Performance',                'Ast'),
            (       'Performance',                'G+A'),
            (       'Performance',               'G-PK'),
            (       'Performance',                 'PK'),
            (       'Performance',              'PKatt'),
            (       'Performance',               'CrdY'),
            (       'Performance',               'CrdR'),
            (    'Per 90 Minutes',                'Gls'),
            (    'Per 90 Minutes',                'Ast'),
            (    'Per 90 Minutes',                'G+A'),
            (    'Per 90 Minutes',               'G-PK'),
            (    'Per 90 Minutes',             'G+A-PK')],
           )

In [18]:
fbRef_one.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11519 entries, 0 to 11518
Data columns (total 25 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Unnamed: 0        9481 non-null   object
 1   Unnamed: 1        11518 non-null  object
 2   Unnamed: 2        11518 non-null  object
 3   Unnamed: 3        11518 non-null  object
 4   nation            11513 non-null  object
 5   pos               11517 non-null  object
 6   age               11516 non-null  float64
 7   born              11516 non-null  float64
 8   Playing Time      11518 non-null  object
 9   Playing Time.1    11518 non-null  object
 10  Playing Time.2    11518 non-null  object
 11  Playing Time.3    11518 non-null  object
 12  Performance       11518 non-null  object
 13  Performance.1     11518 non-null  object
 14  Performance.2     11518 non-null  object
 15  Performance.3     11518 non-null  object
 16  Performance.4     11518 non-null  object
 17  Performance.5     11518 non-null  object
 18  Performance.6     11518 non-null  object
 19  Performance.7     11518 non-null  object
 20  Per 90 Minutes    11518 non-null  object
 21  Per 90 Minutes.1  11518 non-null  object
 22  Per 90 Minutes.2  11518 non-null  object
 23  Per 90 Minutes.3  11518 non-null  object
 24  Per 90 Minutes.4  11518 non-null  object
dtypes: float64(2), object(23)
memory usage: 2.2+ MB

In [19]:
fbRef_one.columns

Index(['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'nation', 'pos',
       'age', 'born', 'Playing Time', 'Playing Time.1', 'Playing Time.2',
       'Playing Time.3', 'Performance', 'Performance.1', 'Performance.2',
       'Performance.3', 'Performance.4', 'Performance.5', 'Performance.6',
       'Performance.7', 'Per 90 Minutes', 'Per 90 Minutes.1',
       'Per 90 Minutes.2', 'Per 90 Minutes.3', 'Per 90 Minutes.4'],
      dtype='object')

In [23]:
fbRef_one["Playing Time.1"].head(10)

0    Starts
1       NaN
2        34
3         2
4        12
5        20
6        32
7         4
8        36
9         2
Name: Playing Time.1, dtype: object

In [25]:
fbRef_one["Playing Time"].head(10)

0     MP
1    NaN
2     34
3      8
4     19
5     30
6     32
7      4
8     38
9      2
Name: Playing Time, dtype: object

In [ ]:
# Renaming columns in the dataset. Reference: https://www.geeksforgeeks.org/pandas/how-to-rename-columns-in-pandas-dataframe/

fbRef_one.rename(columns={
    "Unnamed: 0": "league",
    "Unnamed: 1": "season",
    "Unnamed: 2": "team",
    "Unnamed: 3": "player"
}, inplace=True)

fbRef_one.columns = [
    "nation",
    "pos",
    "age",
    "club",
    "born",
    "matches_played",
    "starts",
    "minutes",
    "nineties",
    "goals",
    "assists",
    "goal_contributions",
    "non_penalty_goals",
    "penalty_goals",
    "penalty_attempts",
    "yellow_cards",
    "red_cards",
    "goals_per90",
    "assists_per90",
    "ga_per90",
    "npg_per90",
    "npga_per90"
]

In [45]:
fbRef_one.head()

,league,season,team,player,nation,pos,age,Club,Playing Time,Playing Time.1,...,Performance.3,Performance.4,Performance.5,Performance.6,Performance.7,Per 90 Minutes,Per 90 Minutes.1,Per 90 Minutes.2,Per 90 Minutes.3,Per 90 Minutes.4
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,born,MP,...,G-PK,PK,PKatt,CrdY,CrdR,Gls,Ast,G+A,G-PK,G+A-PK
1,league,season,team,player,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,ENG-Premier League,2021,Arsenal,Ainsley Maitland-Niles,ENG,"MF,DF",22,NaN,NaN,11,...,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0
3,ENG-Premier League,2021,Arsenal,Alexandre Lacazette,FRA,FW,29,NaN,NaN,31,...,10,3,3,3,0,0.61,0.09,0.7,0.47,0.56
4,ENG-Premier League,2021,Arsenal,Bernd Leno,GER,GK,28,NaN,NaN,35,...,0,0,0,0,1,0.0,0.0,0.0,0.0,0.0

In [46]:
fbRef_one.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19462 entries, 0 to 19461
Data columns (total 26 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   league            16412 non-null  object
 1   season            19461 non-null  object
 2   team              19461 non-null  object
 3   player            19461 non-null  object
 4   nation            19452 non-null  object
 5   pos               19460 non-null  object
 6   age               19457 non-null  object
 7   Club              679 non-null    object
 8   Playing Time      681 non-null    object
 9   Playing Time.1    19461 non-null  object
 10  Playing Time.2    19461 non-null  object
 11  Playing Time.3    19461 non-null  object
 12  Playing Time.4    19461 non-null  object
 13  Performance       19461 non-null  object
 14  Performance.1     19461 non-null  object
 15  Performance.2     19461 non-null  object
 16  Performance.3     19461 non-null  object
 17  Performance.4     19461 non-null  object
 18  Performance.5     19461 non-null  object
 19  Performance.6     19461 non-null  object
 20  Performance.7     19461 non-null  object
 21  Per 90 Minutes    19461 non-null  object
 22  Per 90 Minutes.1  19461 non-null  object
 23  Per 90 Minutes.2  19461 non-null  object
 24  Per 90 Minutes.3  19461 non-null  object
 25  Per 90 Minutes.4  19461 non-null  object
dtypes: object(26)
memory usage: 3.9+ MB

In [47]:
fbRef_one.size

506012

In [48]:
fbRef_one.columns.tolist()

['league',
 'season',
 'team',
 'player',
 'nation',
 'pos',
 'age',
 'Club',
 'Playing Time',
 'Playing Time.1',
 'Playing Time.2',
 'Playing Time.3',
 'Playing Time.4',
 'Performance',
 'Performance.1',
 'Performance.2',
 'Performance.3',
 'Performance.4',
 'Performance.5',
 'Performance.6',
 'Performance.7',
 'Per 90 Minutes',
 'Per 90 Minutes.1',
 'Per 90 Minutes.2',
 'Per 90 Minutes.3',
 'Per 90 Minutes.4']

### Missing Value Count

In [49]:
fbRef_one.isnull().sum().sort_values(ascending=False)

Club                18783
Playing Time        18781
league               3050
nation                 10
age                     5
pos                     2
Performance.3           1
Per 90 Minutes.3        1
Per 90 Minutes.2        1
Per 90 Minutes.1        1
Per 90 Minutes          1
Performance.7           1
Performance.6           1
Performance.5           1
Performance.4           1
Performance             1
Performance.2           1
Performance.1           1
season                  1
Playing Time.4          1
Playing Time.3          1
Playing Time.2          1
Playing Time.1          1
player                  1
team                    1
Per 90 Minutes.4        1
dtype: int64

### Position Distribution

In [50]:
fbRef_one['pos'].value_counts()

pos
MF       6079
DF       4935
FW       2658
GK       1379
MF,FW    1378
FW,MF    1251
DF,MF    1041
MF,DF     708
DF,FW      29
FW,DF       2
Name: count, dtype: int64

In [52]:
# Description of the Dataset

fbRef_one.describe()

,league,season,team,player,nation,pos,age,Club,Playing Time,Playing Time.1,...,Performance.3,Performance.4,Performance.5,Performance.6,Performance.7,Per 90 Minutes,Per 90 Minutes.1,Per 90 Minutes.2,Per 90 Minutes.3,Per 90 Minutes.4
count,16412,19461,19461,19461,19452,19460,19457,679,681,19461,...,19461,19461,19461,19461,19461,19461,19461,19461,19461,19461
unique,8,7,200,7294,195,10,2186,254,23,39,...,33,13,15,19,5,177,161,217,173,214
top,ITA-Serie A,2223,Hellas Verona,Rodri,ESP,MF,25,1. Bayern Munich,1997,1,...,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0
freq,3713,3569,201,14,2500,6079,1341,16,73,1695,...,10948,18162,17888,6556,17557,10812,11250,8469,10948,8530

## TransferMarket Data

In [2]:
%pip install requests beautifulsoup4 lxml pandas

Requirement already satisfied: requests in /opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages (2.32.5)
Requirement already satisfied: beautifulsoup4 in /opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages (4.13.5)
Requirement already satisfied: lxml in /opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages (6.1.1)
Requirement already satisfied: pandas in /opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages (2.3.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages (from requests) (3.4.3)
Requirement already satisfied: idna<4,>=2.5 in /opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages (from requests) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages (from requests) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages (from requests) (2026.5.20)
Requirement already satisfied: soupsieve>1.2 in /opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages (from beautifulsoup4) (2.8.4)
Requirement already satisfied: typing-extensions>=4.0.0 in /opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages (from beautifulsoup4) (4.15.0)
Requirement already satisfied: numpy>=1.26.0 in /opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages (from pandas) (2.3.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in /opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/lib/python3.13/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 26.1.1 -> 26.1.2
[notice] To update, run: /opt/homebrew/Cellar/jupyterlab/4.4.7/libexec/bin/python -m pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.