In [7]:
import pandas as pd

In [8]:
current_positions = [
    "Goalkeeper",
    "Centre-Back",
    "Left-Back",
    "Right-Back",
    "Defensive Midfield",
    "Central Midfield",
    "Attacking Midfield",
    "Right Midfield",
    "Left Winger",
    "Right Winger",
    "Centre-Forward"
]

In [2]:
# Extract Playing Positions from Player names

def extract_position(text):
    """ A function that extracts a player's position from the Transfermarkt Player column.

        Parameters:
            text (str):
                A string containing both the player's name and position.

        Returns:
            str or None: The identified position if found. Returns None if no known position is detected.

    """
    
    for pos in current_positions:
        if text.endswith(pos):
            return pos
    return None

In [3]:
# Extract Player Names

def extract_player_name(text, position):
    """A function to extract the player's name from the Transfermarkt Player column.

        Parameters:
            text (str): Original Player column value containing both player name and position.

            position (str): Position extracted from the Player column.

        Returns:
            str: A clean player name with the position removed.
    """

    return text.replace(position, "").strip()

In [4]:
# Convert Market Value from characters to numbers

def convert_market_value(value):
    """To convert Transfermarkt market values from strings into numeric values.

    Parameters:
        value (str): Player Market value string from Transfermarkt

    Returns:
        float: Market value in euros.
    """

    value = value.replace("€", "")

    if "m" in value:
        return float(value.replace("m", "")) * 1_000_000

    elif "k" in value:
        return float(value.replace("k", "")) * 1_000

    return None

In [5]:
# Clean transfermarket data for every squad/clubs

def clean_transfermarkt_squad(df, club, season):
    """Clean and transform a Transfermarkt squad table.

        This function processes a raw Transfermarkt squad DataFrame by:
            - Removing rows with missing market values.
            - Extracting player positions from the Player column.
            - Extracting player names from the Player column.
            - Converting market values from text format into numeric values.
            - Adding club and season identifiers.
            - Returning a simplified dataset suitable for analysis.

        Parameters:
    
            df (pandas.DataFrame): Raw Transfermarkt squad table.

            club (str): Name of the football club.

            season (str): Season identifier (e.g. '2122', '2223').

        Returns:
        
            pandas.DataFrame: Cleaned squad dataset containing player name, position, age, market value, club, and season.
    """

    df = df[df["Market value"].notna()].copy()

    # extract positions

    df["position"] = df["Player"].apply(extract_position)

    # extract player name

    df["player_name"] = df.apply(
        lambda row: extract_player_name(
            row["Player"],
            row["position"]
        ),
        axis=1
    )

    # convert market value

    df["market_value_eur"] = (
        df["Market value"]
        .apply(convert_market_value)
    )

    df["club"] = club
    df["season"] = season

    return df[
        [
            "player_name",
            "position",
            "Age",
            "market_value_eur",
            "club",
            "season"
        ]
    ]

## Arsenal Squad 2025/2026 season

In [9]:
url = "https://www.transfermarkt.com/arsenal-fc/kader/verein/11/plus/0/galerie/0?saison_id=2025"

tables = pd.read_html(url)

arsenal_clean = clean_transfermarkt_squad(
    tables[1],
    "Arsenal",
    "2526"
)

arsenal_clean.head()

          player_name     position   Age  market_value_eur     club season
0          David Raya   Goalkeeper  30.0        30000000.0  Arsenal   2526
3   Kepa Arrizabalaga   Goalkeeper  31.0         5000000.0  Arsenal   2526
6      William Saliba  Centre-Back  25.0       100000000.0  Arsenal   2526
9             Gabriel  Centre-Back  28.0        75000000.0  Arsenal   2526
12     Piero Hincapié  Centre-Back  24.0        50000000.0  Arsenal   2526

In [10]:
arsenal_clean.info()

<class 'pandas.core.frame.DataFrame'>
Index: 24 entries, 0 to 69
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   player_name       24 non-null     object
 1   position          24 non-null     object
 2   Age               24 non-null     float64
 3   market_value_eur  24 non-null     float64
 4   club              24 non-null     object
 5   season            24 non-null     object
dtypes: float64(2), object(4)
memory usage: 1.3+ KB

In [11]:
arsenal_clean.isna().sum()

player_name         0
position            0
Age                 0
market_value_eur    0
club                0
season              0
dtype: int64

In [12]:
arsenal_clean.sample(10)

,player_name,position,Age,market_value_eur,club,season
57,Noni Madueke,Right Winger,24.0,50000000.0,Arsenal,2526
69,Gabriel Jesus,Centre-Forward,29.0,17000000.0,Arsenal,2526
54,Bukayo Saka,Right Winger,24.0,110000000.0,Arsenal,2526
24,Ben White,Right-Back,28.0,30000000.0,Arsenal,2526
21,Jurriën Timber,Right-Back,25.0,70000000.0,Arsenal,2526
30,Christian Nørgaard,Defensive Midfield,32.0,5000000.0,Arsenal,2526
3,Kepa Arrizabalaga,Goalkeeper,31.0,5000000.0,Arsenal,2526
15,Cristhian Mosquera,Centre-Back,21.0,40000000.0,Arsenal,2526
9,Gabriel,Centre-Back,28.0,75000000.0,Arsenal,2526
6,William Saliba,Centre-Back,25.0,100000000.0,Arsenal,2526

## Man city squad 2025/2026 season

In [17]:
url = "https://www.transfermarkt.com/manchester-city/kader/verein/281/plus/0/galerie/0?saison_id=2024"

tables = pd.read_html(url)

man_city_clean = clean_transfermarkt_squad(
    tables[1],
    "Manchester City",
    "2526"
)

man_city_clean.head()

,player_name,position,Age,market_value_eur,club,season
0,Ederson,Goalkeeper,31.0,20000000.0,Manchester City,2526
3,Stefan Ortega,Goalkeeper,32.0,8000000.0,Manchester City,2526
6,Marcus Bettinelli,Goalkeeper,33.0,600000.0,Manchester City,2526
9,Scott Carson,Goalkeeper,39.0,100000.0,Manchester City,2526
12,Spike Brits,Goalkeeper,18.0,NaN,Manchester City,2526

In [18]:
man_city_clean.info()

<class 'pandas.core.frame.DataFrame'>
Index: 44 entries, 0 to 129
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   player_name       44 non-null     object
 1   position          44 non-null     object
 2   Age               44 non-null     float64
 3   market_value_eur  40 non-null     float64
 4   club              44 non-null     object
 5   season            44 non-null     object
dtypes: float64(2), object(4)
memory usage: 2.4+ KB

In [19]:
man_city_clean.isna().sum()

player_name         0
position            0
Age                 0
market_value_eur    4
club                0
season              0
dtype: int64

In [20]:
man_city_clean.sample(10)

,player_name,position,Age,market_value_eur,club,season
75,Kalvin Phillips,Defensive Midfield,29.0,12000000.0,Manchester City,2526
90,Phil Foden,Attacking Midfield,25.0,100000000.0,Manchester City,2526
51,Nico O'Reilly,Left-Back,20.0,18000000.0,Manchester City,2526
18,Josko Gvardiol,Centre-Back,23.0,75000000.0,Manchester City,2526
36,Nathan Aké,Centre-Back,30.0,25000000.0,Manchester City,2526
111,Savinho,Left Winger,21.0,50000000.0,Manchester City,2526
84,Mateo Kovacic,Central Midfield,31.0,20000000.0,Manchester City,2526
87,İlkay Gündoğan,Central Midfield,34.0,5000000.0,Manchester City,2526
63,Kyle Walker,Right-Back,35.0,4000000.0,Manchester City,2526
99,Kevin De Bruyne,Attacking Midfield,34.0,20000000.0,Manchester City,2526

## Real Madrid 2025/2026 season

In [22]:
url = "https://www.transfermarkt.com/real-madrid/kader/verein/418/plus/0/galerie/0?saison_id=2025"

tables = pd.read_html(url)

real_madrid_clean = clean_transfermarkt_squad(
    tables[1],
    "Real Madrid",
    "2526"
)

real_madrid_clean.head()

         player_name     position   Age  market_value_eur         club season
0   Thibaut Courtois   Goalkeeper  34.0        15000000.0  Real Madrid   2526
3       Andriy Lunin   Goalkeeper  27.0        12000000.0  Real Madrid   2526
6      Fran González   Goalkeeper  20.0         3000000.0  Real Madrid   2526
9       Dean Huijsen  Centre-Back  21.0        60000000.0  Real Madrid   2526
12      Éder Militão  Centre-Back  28.0        20000000.0  Real Madrid   2526

In [23]:
real_madrid_clean.info()

<class 'pandas.core.frame.DataFrame'>
Index: 29 entries, 0 to 84
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   player_name       29 non-null     object
 1   position          29 non-null     object
 2   Age               29 non-null     float64
 3   market_value_eur  29 non-null     float64
 4   club              29 non-null     object
 5   season            29 non-null     object
dtypes: float64(2), object(4)
memory usage: 1.6+ KB

In [24]:
real_madrid_clean.isna().sum()

player_name         0
position            0
Age                 0
market_value_eur    0
club                0
season              0
dtype: int64

In [25]:
real_madrid_clean.sample(10)

,player_name,position,Age,market_value_eur,club,season
18,Antonio Rüdiger,Centre-Back,33.0,6000000.0,Real Madrid,2526
51,Jorge Cestero,Central Midfield,20.0,7500000.0,Real Madrid,2526
15,Raúl Asencio,Centre-Back,23.0,20000000.0,Real Madrid,2526
3,Andriy Lunin,Goalkeeper,27.0,12000000.0,Real Madrid,2526
39,Aurélien Tchouaméni,Defensive Midfield,26.0,70000000.0,Real Madrid,2526
63,Arda Güler,Attacking Midfield,21.0,90000000.0,Real Madrid,2526
48,Thiago Pitarch,Central Midfield,18.0,20000000.0,Real Madrid,2526
54,Dani Ceballos,Central Midfield,29.0,7000000.0,Real Madrid,2526
69,Vinicius Junior,Left Winger,25.0,140000000.0,Real Madrid,2526
27,Fran García,Left-Back,26.0,10000000.0,Real Madrid,2526

In [28]:
arsenal_clean.columns

Index(['player_name', 'position', 'Age', 'market_value_eur', 'club', 'season'], dtype='object')

In [29]:
man_city_clean.columns

Index(['player_name', 'position', 'Age', 'market_value_eur', 'club', 'season'], dtype='object')

In [31]:
real_madrid_clean.columns

Index(['player_name', 'position', 'Age', 'market_value_eur', 'club', 'season'], dtype='object')